### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#1]
This issue chain adds contributors to the repository using allcontributors bot.

The @all-contributors bot automatically adds contributor acknowledgements according to the all-contributors specification ✨

This issue will remain opeen throughout the projecet so new contributors can always be added.

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @JamesSCTJ for ideas, test, and review

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @JamesSCTJ for ideas

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @BrainonSilicon for planning and ideas

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @gedankenstuecke for planning, ideas, code, infrastructure, and tests

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @gedankenstuecke for infrastructure, tests, and code

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @sowmya9507 for planning, ideas, and code

**Comment by GeorgiaHCA** [comment]
@all-contributors bot please add @sowmya9507 for infrastructure, tests, and code

**Comment by lottycoupat** [comment]
@allcontributors add @mridubhatnagar for code and infrastructure

**Comment by mridubhatnagar** [comment]
@lottycoupat, I thing the bot is @all-contributors instead of @allcontributors. :)

**Comment by mridubhatnagar** [comment]
@all-contributors bot please add @mridubhatnagar to the contributor's list.

**Comment by GeorgiaHCA** [comment]
@all-contributors please add @mridubhatnagar for code and infrastructure

**Comment by GeorgiaHCA** [comment]
still no response from the bot...

**Comment by mridubhatnagar** [comment]
@GeorgiaHCA, yes. Should we re-configure?

**Comment by GeorgiaHCA** [comment]
Good idea @mridubhatnagar !

**Comment by mridubhatnagar** [comment]
Awesome, what I am not sure about is allcontributors bot to work on AutSpaces. It should be configured in the root repo that is alan-turing-institute or AutSpaces repo?

**Comment by GeorgiaHCA** [comment]
Hmm I think the root repo is the AutSPACEs one - I originally added it to the repo when it was still owned by me and it transfered to The Turing one just fine

**Comment by mridubhatnagar** [comment]
oh okay. Should I update the permission then? I hope nothing else breaks.

**Comment by GeorgiaHCA** [comment]
Hmm good point - I'm not sure what do you reckon could break?

**Comment by mridubhatnagar** [comment]
> Hmm good point - I'm not sure what do you reckon could break?

Yes makes sense. Nothing would break as such. Worst case scenario is seems to be the bot not working. I'll give it a shot.

**Comment by GeorgiaHCA** [comment]
Thanks @mridubhatnagar 🤞

**Comment by mridubhatnagar** [comment]
@all-contributors please add @mridubhatnagar for code and infrastructure

**Comment by mridubhatnagar** [comment]
@GeorgiaHCA all-contributors app says the updation action must be performed by the organization owner.

**Comment by gedankenstuecke** [comment]
Closing here, as #329 works
