### ISSUE TITLE
Moderator sign-in

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#100]
### Summary

Create **a specific moderator sign-in** (perhaps a specific kind of User ID?), which allows users to **access a private page of experience**s to be moderated so they can decide if they should be made public or not. 

### Updates

This is the most basic possible version of moderation for the platform MVP and will certainly be adaptd in Phase 2.

**Comment by jhlink** [comment]
Closing. Moderation implementation will need to be scoped, as it will involved Django's internal authentication system. 
It seems promising and a much shorter put than creating a dedicated moderator sign-in.
