### ISSUE TITLE
Allow user to save an experience and view experiences not yet submitted

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#101]
### Summary

Users need to have the option to "save" an experience so they can continue editing it before they submit it. They should also have the option to view unsubmitted experiences on their personal page.  

This links with #16 

### What needs to be done?

- [x] Design/decide will these experiences be stored and kept secure? - determine data flow. 
- [x] Create this code as a PR for the MVP

### Who can help?

Anyone with database knowledg or especially knowledge of the OH data managment system.

**Comment by GeorgiaHCA** [comment]
@gedankenstuecke if you have a moment, I wonder if you know how this would work with Open Humans? I think we've spoken about it before!

**Comment by gedankenstuecke** [comment]
We just discussed this during a call with @anoura12, @lottycoupat & @sowmya9507: 

One thing we needed to clear up first was what the difference between `save` and `submit` is. It would probably help if the `save` would be renamed as `save as draft` to be a bit more explicit. 

Regarding the implementation on Open Humans: I think an additional metadata tag for each experience file in Open Humans could help, along with the `public`, `private` etc. flags there could be a `draft` flag that would allow for easy filtering. :)

**Comment by GeorgiaHCA** [comment]
That sounds a good solution @gedankenstuecke - I imagine it would be treated in the same was a submitted experience that had no sharing permissions (so would just be viewable to the user)

**Comment by gedankenstuecke** [comment]
Right, that would be the same thing, but with the extra `draft` flag, so that you can highlight it as 'not submitted yet' in the front end for users to see it more clearly

**Comment by jhlink** [comment]
This feature is out of scope for milestone 3. Per Kirstie's comment some meetings ago, for the MVP, user's can write their experiences in a separate document and submit them on AutSPACEs once completed. 

Replacing milestone 3 tag for milestone 6.

**Comment by gedankenstuecke** [comment]
I think we can close this as users can now implicitly save drafts: Experiences not marked as research or public are stored privately for the user and they can edit and continue writing them at any time.
