### ISSUE TITLE
Integrate sign-in process using Open Humans with the interface

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#102]
### Summary

Open Humans already has an effective sign-in process that protects privacy. We want to make sure that users signing up do so through the OH process so that their accounts and inputs link up with the Open Humans system. 

### What needs to be done?

- [ ] data capture is done by OH in sign up process
- [ ] Make sure that this is a natural part of sign-up sign in for users
- [ ] Have a simple explanation of platform users why they are directed to Open Humans
- [ ] allow for different kinds of sign-in/up for moderators
- [ ] attach an account to user (so that they are able to see and edit their own experiences privately and track the moderation progress.)

**Comment by GeorgiaHCA** [comment]
Heya @gedankenstuecke - would you have a moment to help @sowmya9507 and @anoura12 with this? 🌟

**Comment by gedankenstuecke** [comment]
Yep, we're meeting this afternoon to discuss :)

**Comment by jhlink** [comment]
This ticket is outdated. Closing. 
A ticket describing the tasks needed for sign-in flow will follow.
