### ISSUE TITLE
Create "View experiences" page 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#105]
### Summary

With respect to the [user flow diagram](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/platform-designs/user-flow), there must be a page that showcases public, moderator approved experiences for non-logged-in and logged-in users. Please take extra care when add the `Logout` button.  

MVP requirements may be found [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/platform-designs/platform-requirements/mvp-requirements-list.md). 

- [x] Add Limited Navigation Bar at the top of the page
    - [x] Add Home button, which directs the user to the landing page.
    - [x] Add View Experiences button, which redirects user to current page.
        - (A placeholder URL will suffice.)
    - [x] Add `My Stories` button, which directs user to `My Stories` page (current page). 
        - Display *only* to signed-in user
        - [ ] Redirects to `Home` page if page is reloaded after user logs out. 
    - [x] Add `Share Experiences` button, which directs user to view experiences page. 
        - (A placeholder URL will suffice.)
        - Display *only* to signed-in user
        - [x] Redirects to `Home` page if page is reloaded after user logs out. 
    - [x] Add  `Logout` button, which logs current user out. 
        - **Display only when the user has logged in.**
        - [x] Redirects to `Home` page if page is reloaded after user logs out. 
- [x] Add `View Experiences` title.
- [x] List experiences 
    - Note: No public, moderator approved experiences are available for test. The following tasks describe creating the table headers. Displaying experiences from the OH database will be handled in the next milestone. 
    - [x] Show `date` header
    - [x] Show `Person's autism connection` header
    - [x] Show Ttruncated summary of `experience/story` header
        -  Arbitrarily truncate to maximum row height. 

### Who can help?

The dev team!

**Comment by israelvictory** [comment]
hello, @lottycoupat! I'd like to start working on this!

**Comment by lottycoupat** [comment]
@sowmya9507 @anoura12 is Israel okay to start on this?

**Comment by sowmya9507** [comment]
Hey @israelvictory thank you :) Unfortunately, I have already finished working on this and few changes are to be done. Would you like to work on the My stories page instead?

**Comment by israelvictory** [comment]
Yes, okay with me!

**Comment by jhlink** [comment]
I've revised the tasks for this ticket. Can you review @lottycoupat ? 
Additionally, @sowmya9507  and @anoura12 , can you check any tasks that are completed, and if the ticket has already been implemented, could you tag me in the PR as a reviewer?

**Comment by lottycoupat** [comment]
@jhlink so with this one - are we having the page with two navigation bars? As with the view experiences page you don't need an account for so if you were looking at it without having logged in it would be the smaller nav bar with less options - but if you are logged in you would have a nav bar with all the options? 

Not logged in options you see: Home, View Experiences, Login/Sign-up (?)
When logged in options you see: Home, View Experience, My Stories, Share Experience, Logout

What are your thoughts?

**Comment by jhlink** [comment]
@lottycoupat , that is correct. There will be two different states for the navigation bar depending on whether the user has logged in. 

Great catch!! I'll make the change to the ticket.
