### ISSUE TITLE
Create User Flows for MVP

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutSPACEs#107]
### Summary

Create user flow from James Kim's initial flow to inform how the user will interact with the platform and 

### Deadline 

02/06/21

### What needs to be done?

- [x] Get drawings from JK
- [ ] Tidy up 
- [ ] Add User flow for moderation perspective 
- [ ] Add navigation bar contents
- [ ] Add landing page difference when signed in/not signed in

### Who can help?

Will need review from @GeorgiaHCA @jhlink 

### Updates

LC to being on this ASAP to obtain review and share with developers.

**Comment by lottycoupat** [comment]
@GeorgiaHCA @jhlink FYI

@sowmya9507 @anoura12 here is the issue I am going off for creating the user flows.

**Comment by GeorgiaHCA** [comment]
Fab thanks @lottycoupat - 🚀

**Comment by lottycoupat** [comment]
@GeorgiaHCA @jhlink @anoura12 @sowmya9507 my progress so far: file:///C:/Users/ccoupat/Downloads/AutSPACEs%20-%20User%20Flow%20(2).pdf - does that link work?
