### ISSUE TITLE
Integrate all pages together to produce final MVP

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutSPACEs#119]
### Summary

With respect to the [user flow diagram](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/platform-designs/user-flow), all pages need to be integrated together to follow this flow and user interaction. 

Currently, each page in the prototype vary in navigation bar style, orientation, and selection options. This issue tracks progress for each web page that requires modification. 

### What needs to be done?

- [x] Home page (#134)
  -  aka "landing page" 
- [x] View Experiences (#135)
  - Non-logged-in users: Limited nav bar
  - Logged-in users: Full nav bar
- [x] My stories (#136)
   - Only displays to logged in users 
- [x] Moderation (#137)
- [x] Share experience (#138)
   - aka "Add Experience" 
- [x] Confirmation page  (#139)
 
### Who can help?

Dev team.

### Updates

Ticket captures remaining navigation tasks that must be updated now that all placeholder webpages have been created.

**Comment by lottycoupat** [comment]
hi @anoura12 could you possible add the tasks that need to be done for this please - such as linking the pages and figuring out the flow, and integrating into Django/Website version etc. (not sure if that's the correct wording)

**Comment by anoura12** [comment]
> hi @anoura12 could you possible add the tasks that need to be done for this please - such as linking the pages and figuring out the flow, and integrating into Django/Website version etc. (not sure if that's the correct wording)

Yes sure, @lottycoupat

**Comment by anoura12** [comment]
@jhlink @lottycoupat Would it be a good idea to make separate issues on the integration of each page because as I'm making the checklist, it may come out to be lengthier than usual.

**Comment by jhlink** [comment]
@anoura12 , let's complete the checklist first. 

If it's really big, then sure, split the issue into multiple tickets.

**Comment by anoura12** [comment]
@jhlink I've added the tasks to the issue. Is this the right way to go about integrating the pages? Please feel free to make any changes to this as I think this is still in its early stages. Here's some points which I had some doubts on.

> * [ ]  `Home`
>   
>   * [ ]  Change to landing page without sign up and sign in buttons and add additional items in the navbar

Should we go ahead with this idea for the home page? That way the user can refer to this page to understand the working of site without having to go to the landing page altogether.

Regarding the sign up flow, would we be having different views for each frame of the sign up?

**Comment by jhlink** [comment]
> Should we go ahead with this idea for the home page? That way the user can refer to this page to understand the working of site without having to go to the landing page altogether.

@anoura12 , I'm not really sure what you mean here. If the landing page becomes the home page, how would the user understand the site while avoiding the landing page? 

> Regarding the sign up flow, would we be having different views for each frame of the sign up?

Different views? Do you mean the post-signup questions? This might be a bit of challenge to handle since it's dependent on how we define the signup process with OpenHumans. Let's handle this in Milestone 3.

**Comment by anoura12** [comment]
> @anoura12 , I'm not really sure what you mean here. If the landing page becomes the home page, how would the user understand the site while avoiding the landing page?

Oh, what I meant was the home page has the same design as the landing page but with the updated navbar and sign in and sign up buttons removed like you saw in the MVP on Thursday. Basically, there should be some home page after the confirmation page. I thought keeping some of the content of the landing page same would help the user refer to the instructions easily. Should we have a different design for the home page if the two pages look too similar?
> 
> > Regarding the sign up flow, would we be having different views for each frame of the sign up?
> 
> Different views? Do you mean the post-signup questions? This might be a bit of challenge to handle since it's dependent on how we define the signup process with OpenHumans. Let's handle this in Milestone 3.
>


> To reiterate, the goal of this ticket is to ensure that all the nav bar items direct to the appropriate pages. There is no expectation of any changes beyond this. If you consider, for example, the `public experiences` page that @sowmya9507 is working on, the buttons are static. After she adds the requested change, the next step would be update the buttons, such that the nav bar buttons are functional.

Okay, I think i got bit mixed up there. Thanks for the clarification! Is the checklist fine then or do I need to make any changes?

**Comment by jhlink** [comment]
All tagged issues are complete. Milestone #2 is complete at last. 
Congrats to everyone!!
