### ISSUE TITLE
Create Confirmation - Navigation Screen

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#121]
## Summary
Create a confirmation page that directs the user to other web pages. 

This confirmation page appears after a sign up, sign in, and a successfully share experience. 

A wireframe of the confirmation page is shown here. 
![CleanShot 2021-06-28 at 22 30 29](https://user-images.githubusercontent.com/1872836/123727944-7bc68580-d860-11eb-8d66-318f1b2397fa.jpg)

What needs to be done?
- [x] Add the following text to the page, ordered according to the wire frame
    - [x] "Thank you for sharing your experience"
    - [x] "What happens next?"
    - [x] "What happens now?"
    - [x] Add following block of text.
```
    If you chose to share your experience with the world, an autistic moderator will check that it follows our code of conduct, and if it does, you will receive a confirmation and your experience will then be published on this website. 

If you told us to share it only with people who have signed up and told us they are autistic, an autistic moderator will check that it follows our code of conduct, and if it does you will receive a confirmation and your experience will then be published on our website. Only signed-in users who have told us they are autistic will be shown your experience.

If you chose to share it with researchers, it will be saved into a database, and researchers who follow our values will be able to use it for their research. 
```
    - [ ] "What would you like to do now?"
- [x] Add the following navigation buttons
    - [x] "Enter Another Experience"
        - [x] On click, should direct user to `Share Experiences` page
    - [x] "View Other Experiences"
        - [x] On click, should direct user to `View Experiences` page
    - [x] "Go to My Experiences Page"
        - [x] On click, should direct user to `My Stories` page
        - May leave blank if PR #120 hasn't been merged yet. 
    - [x] "Find out more about AutSPACE"
        - [x] On click, should direct user to `Landing` page
- [x] This screen should appear after the following screens
    - [x] After successfully submitting a shared experience
    - [x] After completing the sign-up process
    - [x] After completing the sign-in process

**Comment by lottycoupat** [comment]
@jhlink do you need someone to do this?

@israelvictory how do you feel about taking this page one?

**Comment by israelvictory** [comment]
Awesome! @lottycoupat I can do this. I'll finish "My Stories Page" today and begin working on this. 👍🏾

**Comment by lottycoupat** [comment]
@israelvictory fab thank you Israel! I have added you as the Assignee 👍

**Comment by jhlink** [comment]
Closing.
