### ISSUE TITLE
Landing Page: Second Phase 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#123]
### Summary 

The MVP landing page is complete 🎉 This issue is for the next iteration of the landing page. Please Add your comments below for suggestions for design features

**Comment by GeorgiaHCA** [comment]
Feedback from @suziqpid 

l object to wording on the landing page which has the clunky phrase, "collecting together Autistic experiences etc.". Collecting implies placing things together so that word is superfluous. Only need ‘ collecting'.

**Comment by GeorgiaHCA** [comment]
Commnts from @skfantoni: 

Add categorisation options

Decisions that need to be made:
- [ ] At what point in the process does categorisation take place?
- [ ] Who decides what stories go under what categories?
- [ ] How are categories displayed on the site?
- [ ] Can users limit which categories they see and when?

**Comment by SuziQpid** [comment]
Dear Suzanna,

Being so new to most of this process can you give me a few examples of category headings, then l can see what l ingredients l can add to the working pot if any.

Suzanne lwai
