### ISSUE TITLE
Sign-in flow: Second Phase 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#124]
### Summary

The MVP sign-up flow is complete 🎉 This issue is for the next iteration of the landing page. Please Add your comments below for suggestions for design features.

**Comment by GeorgiaHCA** [comment]
Feedback from @SuziQpid

On the sharing options does it say you can tick all that apply  not just one?

**Comment by gedankenstuecke** [comment]
These things are now all implemented 🙂
