### ISSUE TITLE
Share Experiences - Second Phase

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#125]
### Summary

The MVP share experiences page is complete 🎉 This issue is for the next iteration of the landing page. Please Add your comments below for suggestions for design features.

**Comment by GeorgiaHCA** [comment]
Feedback from @SuziQpid

For "my experiences", should we not have two different shades / colours to highlight label choice between viewable and research which link back to the option buttons on entering experience page and landing page.

**Comment by gedankenstuecke** [comment]
These things are now all implemented 🙂
