### ISSUE TITLE
Meet Up Website

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/AutSPACEs#126]
# Summary
This is the open issue that will capture discussion and workflow for the Meet Up's Website. 

# What needs to be done?

## Design ✍️ 
- [ ] finalize wireframe design
- [ ] finalize page content
- [x] decide on colour scheme ( 🟥 COMMUNITY LED DECISION)

## Develop 💻 
- [ ] create static version of the page
- [ ] add in active links (QA check)
- [ ] add in updating functioning for links section
- [ ] add in updating functionality for time zones 

### Technical 
* web developers (python/django)
* web designers 
* python for automation

#### Logistical 
* anyone involved in the project 

---

**Comment by gedankenstuecke** [comment]
Should we put this into the Wiki instead as well? 😄

**Comment by BrainonSilicon** [comment]
Yes!

**Comment by gedankenstuecke** [comment]
I've made a pretty empty page here: https://github.com/alan-turing-institute/AutSPACEs/wiki/Meetups 

If you have a link of links somewhere I'd be happy to add all the past information!

**Comment by gedankenstuecke** [comment]
Could be closing this as we just need to keep adding the old notes link to the Wiki. @BrainonSilicon do you want to keep this around and close once the notes are there or just close this? :)

**Comment by BrainonSilicon** [comment]
> Could be closing this as we just need to keep adding the old notes link to the Wiki. @BrainonSilicon do you want to keep this around and close once the notes are there or just close this? :)

Let's close this so that there's not a weird paper trail. We can open a new one about the wiki.
