### ISSUE TITLE
My Stories Page second Phase

### ISSUE THREAD

**Issue by sowmyaarajan** [alan-turing-institute/AutSPACEs#130]
### Summary
Now  that the MVP is almost complete in the Milestone 2. There are some additional changes that are required for the page. The stories are displayed for the user in the .json format. Instead of this, when the user click on "My Stories" button, the stories should be displayed on the page. The users should also be able edit them along with the option of whether to submit them for research. submit it for public. or not etc.

### What needs to be done?

* Displaying stories/experiences on the My Stories Page.
* Option to Edit.
* Option to be added such as Submit for research, submit for public etc.

### Who can help?
Anyone from the platform development team

**Comment by israelvictory** [comment]
Awesome! @lottycoupat can I take this?

**Comment by lottycoupat** [comment]
@israelvictory Sorry for the late reply! Yes absolutely go ahead on this one :)
