### ISSUE TITLE
Navigation: Standardize `Home` page navigation bar

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#134]
## Description

The landing page in the prototype is the `Home` page. When the user first loads `localhost:8000`, they should be directed to this page.

![CleanShot 2021-07-22 at 06 46 34](https://user-images.githubusercontent.com/1872836/126627642-03631569-1aea-4033-93c9-29649eb5171d.jpg)

## Definition of Done

- [x] Add `Moderate Experiences` button
- [x] Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
- [x] Clicking `My Stories` directs user to `my_stories.html`
- [x] Clicking `Share Experiences` directs user to `share_experiences.html`
- [x] Ensure navigation bar in Home page has the following buttons
   - [x] Home: Redirects to the current page
     - This is `landing.html` *not* `overview.html`  
   - [x] Rename `landing.html` to `home.html`
   - [x] View Experiences: Redirects to the `Experiences` page
     -  This is the `Experiences_Page.html` *not* `public_experiences.html`
   - [x] Logout:
     - Should *only* appear to logged in users. 
     - Should not appear to non-logged in users.
- [x] Clicking `Logout` should log out user.
- [x] Clicking `Logout` directs user to `Home` page.
   - This is `home.html` or `landing.html` *not* `overview.html` 
 - [x] Verify that the order of navigation bar items is the following:
     - [x] From left to right, `Home` - `View Experiences` - `Moderate Experiences` - `Share Experiences` - `My Stories` - `Logout`

**Comment by anoura12** [comment]
@lottycoupat I can take this up. 
@jhlink I can make the modifications for the navbar and the buttons here as I mentioned earlier in [#138](https://github.com/alan-turing-institute/AutSPACEs/issues/138)

**Comment by anoura12** [comment]
> ## Description
> The landing page in the prototype is the `Home` page. When the user first loads `localhost:8000`, they should be directed to this page.
> 
> ![CleanShot 2021-07-22 at 06 46 34](https://user-images.githubusercontent.com/1872836/126627642-03631569-1aea-4033-93c9-29649eb5171d.jpg)
> 
> ## Definition of Done
> * [ ]  Add `Moderate Experiences` button
> * [ ]  Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
> * [ ]  Ensure navigation bar in Home page has the following buttons
>   
>   * [ ]  Home: Redirects to the current page
>     
>     * This is `landing.html` _not_ `overview.html`
>   * [ ]  Rename `landing.html` to `home.html`
>   * [ ]  View Experiences: Redirects to the `Experiences` page
>     
>     * This is the `Experiences_Page.html` _not_ `public_experiences.html`
>   * [ ]  Logout:
>     
>     * Should _only_ appear to logged in users.
>     * Should not appear to non-logged in users.
> * [ ]  Verify that the order of navigation bar items is the following:
>   
>   * From left to right: `Home` - `View Experiences` - `Moderate Experiences` - `Logout`

@jhlink Just to clarify, the `Moderate Experiences` option will be available to only logged in users right?

**Comment by mridubhatnagar** [comment]
@jhlink @anoura12 I think there is a lot of confusion between files landing.html and home.html. Are these supposed to be two different files or we'll rename landing.html to home.html?

**Comment by GeorgiaHCA** [comment]
Hiya @mridubhatnagar - I think for the MVP they should be identical apart from the home.html being modified for people who are signed in?

**Comment by GeorgiaHCA** [comment]
The landing.html should be for people who are not signed in

**Comment by mridubhatnagar** [comment]
hey @GeorgiaHCA, just wanted to confirm what do you mean by 'home.html being modified for people who are signed in'? Does it mean that people who are signed in when they click on Home we would be rendering home.html and for people who are not signed in when they click Home then we would render landing.html?

Also, I think in the current implementation. If the user is signed in or not signed in, in both cases we are showing them home.html.

**Comment by GeorgiaHCA** [comment]
Yes, I agree @mridubhatnagar- in fact I think the only thing that would need to be changed for the MVP would be in the navigation options? What do you reckon @jhlink ?

**Comment by mridubhatnagar** [comment]
Depends on which case what page do we plan to show the user.
IMO navigation options would remain the same as Landing cannot be a navigation option. 
However, internally we can write the code in a way that signed-in users are redirected to home.html while not signed-in users are redirected to landing.html.

In case this functionality is what we need.

**Comment by anoura12** [comment]
I think what @jhlink meant is that by renaming landing.html to home.html, the file would be appropriately named as home page. The code structure for that page is almost same for logged in and non logged in users. So, having another file called landing.html isn't really required here I believe.

**Comment by GeorgiaHCA** [comment]
We would need additional options for signed in users to navigate to their own page from the navigation bar to view the experiences they've submitted, and a sign out or switch account option instead of a sign in option - but I don't think the content of the home page would need to change other than the navigation bar.

**Comment by anoura12** [comment]
@GeorgiaHCA Yes, I don't think it's explicitly mentioned in the task list but the sign in, sign out buttons are hidden and the navbar has additional items like moderate experiences, share experiences, my stories and logout visible only to logged in users. 
Having a switch account option is a good feature to add into the site. Thanks for pointing that out!

**Comment by jhlink** [comment]
PR is complete. Closing.
