### ISSUE TITLE
Navigation: Standardize `View Experiences` page nav bar

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#135]
## Description
The `View Experiences` page has two states: logged-in and logged-out view. The navigation bar will change based on whether an authenticated user exists.

## Definition of Done

- [x] Rename `Public Experiences` to `View Experiences` in URL path. 
- [x] Remove `Login` button in top right corner for logged-out users.
    - `Logout` button should still be present for logged-in users. 
- [x] Remove `About` link
- [x] Add `Moderate Experiences` button
- [x] Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
- [x] Reorder Navigation bar items. 
   - [x] Logged-In Users: From left to right, `Home` - `View Experiences` - `Moderate Experiences` - `Share Experiences` - `My Stories` - `Logout`
   - [x] Logged-Out Users: From left to right, `Home` - `View Experiences`
- [x] Clicking `Home` directs user to the `Home` page
   - This is `landing.html` *not* `overview.html`
- [x] Clicking `View Experiences` directs user to `experiences_page.html`
   - This should *not* direct user to `list.html` 
- [x] Clicking `My Stories` directs user to `my_stories.html`
- [x] Clicking `Share Experiences` directs user to `share_experiences.html`
- [x] Clicking `Logout` logs out user.
- [x] Clicking `Logout` directs user to `Home` page.
   - This is `home.html` or `landing.html` *not* `overview.html` 

For reference, the following is the current state of the navigation bar in the view experiences page for **logged-in** users.

![CleanShot 2021-07-22 at 05 17 17](https://user-images.githubusercontent.com/1872836/126616322-9e8a4c13-ea0a-4310-a9d7-f0bd329f31aa.jpg)

For reference, the following is the current state of the navigation bar in the view experiences page for **logged-out** users.

![CleanShot 2021-07-22 at 05 16 47](https://user-images.githubusercontent.com/1872836/126616260-e219a873-9fb8-48cc-82f8-72a11cc3bb9a.jpg)

**Comment by anoura12** [comment]
@lottycoupat I can take this up

**Comment by anoura12** [comment]
@jhlink In the first task where public experiences needs to be changed to view experiences, I would have to be changing all the urls in all the other html files that direct to view experiences right?

**Comment by mridubhatnagar** [comment]
@anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed. 

However, if you change name of the url too along with the url path then in all files url name will have to be changed.

**Comment by anoura12** [comment]
> @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> 
> However, if you change name of the url too along with the url path then in all files url name will have to be changed.

I think Django throws an error if the name and URL path aren't the same.

**Comment by mridubhatnagar** [comment]
> > @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> > However, if you change name of the url too along with the url path then in all files url name will have to be changed.
> 
> I think Django throws an error if the name and URL path aren't the same.

Tested it, Django doesn't throw an error.

**Comment by jhlink** [comment]
@mridubhatnagar , thanks for the help!
@anoura12 I specifically meant changing the URL path in `urls.py`. It's a bit confusing to see `public_experiences` in the URL path instead of `view_experiences`. You might have to change the corresponding `name` reference as well for clarity. 

Original
`url(r'^public_experiences/?$', views.list_public_experiences, name='public_experiences'),`

Modified
`url(r'^view_experiences/?$', views.list_public_experiences, name='view_experiences'),`

**Comment by anoura12** [comment]
> @mridubhatnagar , thanks for the help!
> @anoura12 I specifically meant changing the URL path in `urls.py`. It's a bit confusing to see `public_experiences` in the URL path instead of `view_experiences`. You might have to change the corresponding `name` reference as well for clarity.
> 
> Original
> `url(r'^public_experiences/?$', views.list_public_experiences, name='public_experiences'),`
> 
> Modified
> `url(r'^view_experiences/?$', views.list_public_experiences, name='view_experiences'),`

@jhlink Oh yes I understand what you mean. I just wanted to inquire that if I change it according to the modified version, I would also have to be changing the links of the `View Experiences` in other files that mention it as well right? Otherwise Django will throw a ReverseMatch error

**Comment by anoura12** [comment]
> @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> 
> However, if you change name of the url too along with the url path then in all files url name will have to be changed.

By name of url, you mean the one mentioned here right?
`url(r'^public_experiences/?$', views.list_public_experiences, name='public_experiences'),`

**Comment by anoura12** [comment]
> > > @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> > > However, if you change name of the url too along with the url path then in all files url name will have to be changed.
> > 
> > 
> > I think Django throws an error if the name and URL path aren't the same.
> 
> Tested it, Django doesn't throw an error.

Did you mean changing it like this?
![Screenshot from 2021-07-26 20-01-06](https://user-images.githubusercontent.com/73518403/127006474-71ae3a89-a625-4f81-b284-401c445c9056.png)

**Comment by mridubhatnagar** [comment]
> > @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> > However, if you change name of the url too along with the url path then in all files url name will have to be changed.
> 
> @mridubhatnagar By name of url, you mean the one mentioned here right?
> `url(r'^public_experiences/?$', views.list_public_experiences, name='public_experiences'),`

@anoura12 yes. 
In the snippet you shared: 
url name -> 'public_experiences' 
url path -> r'^public_experiences/?$'

**Comment by anoura12** [comment]
> > > @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> > > However, if you change name of the url too along with the url path then in all files url name will have to be changed.
> > 
> > 
> > @mridubhatnagar By name of url, you mean the one mentioned here right?
> > `url(r'^public_experiences/?$', views.list_public_experiences, name='public_experiences'),`
> 
> @anoura12 yes.
> In the snippet you shared:
> url name -> 'public_experiences'
> url path -> r'^public_experiences/?$'


Did you want me to change the code like in the screenshot I sent earlier then?

**Comment by anoura12** [comment]
Ah @mridubhatnagar, I see what you mean. 
@jhlink Should I keep the name as public_experiences then?

**Comment by mridubhatnagar** [comment]
> > > > @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> > > > However, if you change name of the url too along with the url path then in all files url name will have to be changed.
> > > 
> > > 
> > > I think Django throws an error if the name and URL path aren't the same.
> > 
> > 
> > Tested it, Django doesn't throw an error.
> 
> Did you mean changing it like this?
> ![Screenshot from 2021-07-26 20-01-06](https://user-images.githubusercontent.com/73518403/127006474-71ae3a89-a625-4f81-b284-401c445c9056.png)

I meant that if you change it in this manner then you won't have to make changes in all the html files. However, if you change the url name and url path both then in all the html files also you will have to change the url name. 

According to me, changing both URL path and URL name would be a better choice to go ahead with.

**Comment by anoura12** [comment]
> > > > > @anoura12 if you change the URL path corresponding to public experiences inside urls.py file the changed url path would get reflected everywhere. You won't have to change all the urls in the other html files as name of url is not changed.
> > > > > However, if you change name of the url too along with the url path then in all files url name will have to be changed.
> > > > 
> > > > 
> > > > I think Django throws an error if the name and URL path aren't the same.
> > > 
> > > 
> > > Tested it, Django doesn't throw an error.
> > 
> > 
> > Did you mean changing it like this?
> > ![Screenshot from 2021-07-26 20-01-06](https://user-images.githubusercontent.com/73518403/127006474-71ae3a89-a625-4f81-b284-401c445c9056.png)
> 
> I meant that if you change it in this manner then you won't have to make changes in all the html files. However, if you change the url name and url path both then in all the html files also you will have to change the url name.
> 
> According to me, changing both URL path and URL name would be a better choice to go ahead with.

Yes agreed. It would be better. So should I be changing it for all files in this one issue?

**Comment by mridubhatnagar** [comment]
Not sure what would be the right approach to do it. 

I think once all the navigation-related pull requests get merged then in 1 PR this replacement thing can be done. As there are lot of html files using view experiences. And, html files with navigation related fixes are yet to be merged.

**Comment by mridubhatnagar** [comment]
@anoura12 yes meant the same.

**Comment by anoura12** [comment]
> @anoura12 yes meant the same.

Oh sorry yes, my bad

**Comment by jhlink** [comment]
Reopening because I messed up the review/PR merge for #147

**Comment by jhlink** [comment]
Closing due to merge in #151
