### ISSUE TITLE
Navigation: Standardize `My Stories` page nav bar

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#136]
## Description
URL paths in navigation bar needs to be updated. 

![CleanShot 2021-07-22 at 05 40 06](https://user-images.githubusercontent.com/1872836/126619293-83b63bee-7754-4422-b9cf-e9de10ed2fa1.jpg)

## Definition of Done

- [x] Clicking `AutSPACEs` directs user to the `Home` page
   - This is `landing.html` *not* `overview.html`
- [x] Clicking `Home` directs user to the `Home` page
   - This is `landing.html` *not* `overview.html`
- [x] Clicking `View Experiences` directs user to `experiences_page.html`
- [x] Add `Moderate Experiences` button
- [x] Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
- [x] Clicking `Share Experiences` directs user to `share_experiences.html`
- [x] Clicking `Logout` directs user to `Home` page.
   - This is `home.html` or `landing.html` *not* `overview.html` 
- [x] Clicking `Logout` should logout user
- [x] Reorder navigation bar items: 
   - From left to right, `Home` - `View Experiences` - `Moderate Experiences` - `Share Experiences` - `My Stories` - `Logout`

**Comment by mridubhatnagar** [comment]
@lottycoupat, @jhlink I am interested in working on this issue.

**Comment by lottycoupat** [comment]
@mridubhatnagar awesome! Will assign you the issue!! 😄

**Comment by jhlink** [comment]
PR is complete. Closing.
