### ISSUE TITLE
Navigation: Standardize `Moderation` page nav bar

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#137]
## Description
The `Moderation` page needs to be updated. 

![CleanShot 2021-07-22 at 05 52 12](https://user-images.githubusercontent.com/1872836/126620908-5bf0d11f-a703-4cca-914b-a0a2c9e17bb1.jpg)

## Definition of Done

- [x] Remove `About` link
- [x] Clicking `Home` directs user to the `Home` page
   - This is `landing.html` *not* `overview.html`
- [x] Clicking `My Stories` directs user to `my_stories.html`
- [x] Clicking `Share Experiences` directs user to `share_experiences.html`
- [x] Add `Moderate Experiences` button
- [x] Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
- [x] Clicking `Logout` should log out user.
- [x] Clicking `Logout` directs user to `Home` page.
   - This is `home.html` or `landing.html` *not* `overview.html` 
- [x] Reorder Navigation bar items. 
   - [x] From left to right, `Home` - `View Experiences` - `Moderate Experiences` - `Share Experiences` - `My Stories` - `Logout`
- [x] Replace example text with `Lorem ipsum` excerpt or other arbitrary text.

**Comment by mridubhatnagar** [comment]
@lottycoupat, I can pick this up.

**Comment by jhlink** [comment]
PR is complete. Closing.
