### ISSUE TITLE
Navigation: Standardize `Share Experience` page nav bar

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#138]
## Description
Navigation bar in the `Share Experiences` page needs to be updated.  

![CleanShot 2021-07-22 at 06 11 46](https://user-images.githubusercontent.com/1872836/126623561-03db3948-0e8c-4cf2-87af-ab90413d2241.jpg)

## Definition of Done

- [x] Clicking `Home` directs user to the `Home` page
   - This is `landing.html` *not* `overview.html`
- [x] Clicking `View Experiences` directs user to `experiences_page.html`
- [x] Clicking `My Stories` directs user to `my_stories.html`
   - This should *not* direct the user to `list.html` or `/main/list` URL.  
- [x] Add `Moderate Experiences` button
- [x] Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
- [x] Clicking `Share Experiences` directs user to `share_experiences.html`
- [x] Hide `Sign up` and `Sign in` buttons on `Home` page after user has logged in. 
- [x] Clicking `Logout` logs user out.
- [x] Clicking `Logout` directs user to `Home` page.
   - This is `home.html` or `landing.html` *not* `overview.html` 
- [x] Reorder Navigation bar items. 
   - [x] From left to right, `Home` - `View Experiences` - `Moderate Experiences` - `Share Experiences` - `My Stories` - `Logout`

**Comment by anoura12** [comment]
@lottycoupat I can take this up.

**Comment by lottycoupat** [comment]
@anoura12 I have assigned 😄

**Comment by anoura12** [comment]
@jhlink I believe there would also need to be a rectification in the landing page once an authenticated user clicks Home. I guess the sign in and sign up buttons need to be hidden and the navbar would also need to updated to include Share Experiences, My stories etc...

**Comment by jhlink** [comment]
> @jhlink I believe there would also need to be a rectification in the landing page once an authenticated user clicks Home. I guess the sign in and sign up buttons need to be hidden and the navbar would also need to updated to include Share Experiences, My stories etc...

Good point. I'll add that to the list.
