### ISSUE TITLE
Navigation: Standardize `Confirmation` page nav bar

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#139]
## Description
The confirmation page has two sets of navigational buttons: items in the navigation bar and items on the web page. Updates need to be made for both.

### Navigation bar
![CleanShot 2021-07-22 at 06 12 01](https://user-images.githubusercontent.com/1872836/126623671-23b2fdbc-aad0-4b23-92fd-f348bba44026.jpg)

### Webpage Buttons
![CleanShot 2021-07-22 at 06 12 58](https://user-images.githubusercontent.com/1872836/126623711-7e689d2a-9bac-4dbc-8c4f-a138b9e1380b.jpg)

### Navigation Bar Tasks

- [x] Remove `About` link
- [x] Rename `Share` to `Share Experiences`. 
- [x] Rename `View` to `View Experiences`. 
- [x] Rename `MyPage` to `My Stories`. 
- [x] Clicking `View Experiences` directs user to `experiences_page.html`
- [x] Clicking `My Stories` directs user to `my_stories.html`
- [x] Add `Moderate Experiences` button
- [x] Clicking `Moderate Experiences` directs user to `moderate_public_experiences.html`
- [x] Add `Home` button
- [x] Clicking `Home` directs user to the `Home` page
   - This is `landing.html` *not* `overview.html`
- [x] Clicking `Logout` logs out user.
- [x] Clicking `Logout` directs user to `Home` page.
   - This is `home.html` or `landing.html` *not* `overview.html` 
- [x] Reorder Navigation bar items. 
   - From left to right, `Home` - `View Experiences` - `Moderate Experiences` - `Share Experiences` - `My Stories` - `Logout`

### Webpage Button Tasks

- [x] Rename `Go to My Experience page` to `Go to My Stories`
- [x] Clicking `Find out more about AutSPACEs` directs user to `Home` page. 
   - This is `home.html` or `landing.html` *not* `overview.html`

**Comment by mridubhatnagar** [comment]
@lottycoupat I can take this up.

**Comment by lottycoupat** [comment]
@mridubhatnagar fabulous!!

**Comment by jhlink** [comment]
PR is complete. Closing.
