### ISSUE TITLE
Milestone 3: OpenHumans Integration - Tasks

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#140]
## Description
The UI has been created with placeholders as needed. With the OpenHumans integration, the following categories of task exist: 
- [ ] #161
- [x] #158
- [x] #157
- [x] #162
- [x] #156
- [ ] Implement My Stories page (#153)
- [x] #166

Note: The Django models need to be defined for different user groups, experiences, and account questionnaire.  These will be handled by a need-based basis when implementing each page. 

Information about OpenHuman's API can be found in the following. 
  - [django-open-humans API](https://django-open-humans.readthedocs.io/en/latest/modules/interactions.html) 
  - [general open-humans api](https://open-humans-api.readthedocs.io/en/latest/ohapi.html)

- **Scope saving drafts of experiences  in share experiences**
- Scope fake data -- that's resettable. 
- Have a project that developers can connect with and test.

**Comment by GeorgiaHCA** [comment]
This is a fantastic issue @jhlink thanks for setting it out so clearly!

**Comment by GeorgiaHCA** [comment]
Is it worth haaving these as separate issues for people to work on @jhlink ? And possibly link them to the roadmap @lottycoupat ?

**Comment by jhlink** [comment]
@GeorgiaHCA , yes, for sure! I'm planning on spending some time soon to reconsolidate the milestone 3 tasks. Gotta hurry since milestone 2 is very close to completion!!

**Comment by jhlink** [comment]
Note: Access control issue - moderation
![CleanShot 2021-08-03 at 06 13 03](https://user-images.githubusercontent.com/1872836/127999010-ab8863a2-ec4a-4371-94e7-65dc68e2d0d7.jpg)

**Comment by GeorgiaHCA** [comment]
Thanks James!!

**Comment by mridubhatnagar** [comment]
@jhlink I am interested in working on the Django models issue. Also, is there a place where we have documented different user groups, experiences, and account questionnaires or does one need to figure this out on their own?

**Comment by GeorgiaHCA** [comment]
Adding comment from @badgermind here: 

Two issues came up during the developers co-working call this week:

(1) Are we keeping a record of the dialogue between users and moderators about specific posts (my view: yes) and who is it visible to (my view: that user and all moderators)? The may be a very small number of cases where a user is not happy about their post not being allowed and attempts to start a complaint process elsewhere or on social media. Keeping a record means that any discussion of the interaction in an external complaint process, or response to a complaint on social media, is based on fact and also protects the moderators. To do this we would need to add a django model/table to the database.

(2) from the bottom of https://django-open-humans.readthedocs.io/en/latest/modules/getting-started.html?highlight=hook#setting-up-your-open-humans-project ...there is a deauthorization hook that you can setup on Open Humans which will automatically inform you when people have de-authorized your application. django-open-humans accepts deauthorization requests at /openhumans/deauth ...
Do we want to bulid this into the process of keeping our Heroku database in sync with Open Humans, and what impact would someone deauthorising have on datasets (particularly those already provided) for research?

**Comment by jhlink** [comment]
> (1) Are we keeping a record of the dialogue between users and moderators about specific posts (my view: yes) and who is it visible to (my view: that user and all moderators)? The may be a very small number of cases where a user is not happy about their post not being allowed and attempts to start a complaint process elsewhere or on social media. Keeping a record means that any discussion of the interaction in an external complaint process, or response to a complaint on social media, is based on fact and also protects the moderators. To do this we would need to add a django model/table to the database.

Presently, no. The only communication between moderator and user during the review process is the Experience review status. If you wanted to keep track of a discussion between the moderator and user, that's something that'll have to be added later. 

> (2) from the bottom of https://django-open-humans.readthedocs.io/en/latest/modules/getting-started.html?highlight=hook#setting-up-your-open-humans-project ...there is a deauthorization hook that you can setup on Open Humans which will automatically inform you when people have de-authorized your application. django-open-humans accepts deauthorization requests at /openhumans/deauth ...
> Do we want to bulid this into the process of keeping our Heroku database in sync with Open Humans, and what impact would someone deauthorising have on datasets (particularly those already provided) for research?

So, if someone has deauthorized the AutSPACE account, what is the desired behavior? Eventually, we will take advantage of additional events that occur when a user has deauthorizes a project, but (correct me if I'm wrong, @gedankenstuecke) until then user data should still persist in the OpenHumans/Django database. 
- Do you want to delete all experiences/user data that was uploaded to OpenHumans?
- Delete a partial set of data (i.e. only experiences marked as public?)

**Comment by gedankenstuecke** [comment]
> So, if someone has deauthorized the AutSPACE account, what is the desired behavior? Eventually, we will take advantage of additional events that occur when a user has deauthorizes a project, but (correct me if I'm wrong, @gedankenstuecke) until then user data should still persist in the OpenHumans/Django database.  
> * Do you want to delete all experiences/user data that was uploaded to OpenHumans?
> * Delete a partial set of data (i.e. only experiences marked as public?)

When a person deauthorizes a project on Open Humans this project immediately looses all access to the project data that is stored on Open Humans. Which is fine, as the user gets the option to keep or delete the data stored on Open Humans when doing the deauthorization step. 

The hook is designed to give you a signal to remove user data stored in the AutSpaces database itself. How much data should be removed from AutSpaces is up for discussion I think, it could be removing the OpenHumansMember itself, which then would by inheritance remove all other data such as public experiences.

**Comment by gedankenstuecke** [comment]
The signup flow works along with all OH integrations for updating/writing/fetching data 🎉
