### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#15]
### Summary

Create an MVP landing page for the AutSPACEs platform 

A wireframe view of the simplified landing page is here:

[Simplified landing page design](https://www.figma.com/file/HxqTSdeyAUNMualnBV0PET/Autspace-(WIP)?node-id=172%3A641)

[User Flow Diagram](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/platform-designs/user-flow)

For reference, the MVP requirements can be found [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/platform-designs/platform-requirements/mvp-requirements-list.md). 

#### Functionality

- [x] Add Limited Navigation Bar at the top of the page
  - [x] Add `Home` button, which directs the user to the landing page. 
  - [x] Add `View Experiences` button, which directs user to view experiences page. 
      - (A placeholder URL will suffice.)
  - [x] Add  `Logout` button, which logs current user out. 
      - Display *only* when the user has logged in. 
- [x] Add sign-up button 
      - Existing implementation is OK, but eventually should link to [sign-up flow](#17)
- [x] Add sign-in button 
      - Existing implementation is OK, but eventually should integrate with OpenHumans Sign-In process defined in [sign-up flow](#17)

#### Aesthetics

- [ ] Add platform name at top of screen
- [ ] Add Turing and Autistica logos
- [x] Add simple explanatory text
- [ ] Add simple step-by-step "how it works" guide

### Who can help

* Anyone with web development skills to build
* Anyone from the community to review and test*
* the designs are already founded on substantial community feedback and user testing

**Comment by GeorgiaHCA** [comment]
@sowmya9507 - I created an html version of this however it was not fitted to Open Humans. Are you able to take on this issue? Does it have enough information?

**Comment by GeorgiaHCA** [comment]
![image](https://user-images.githubusercontent.com/46889966/118686717-2bd5b700-b7fc-11eb-82ce-fd2ba03d84d7.png)

**Comment by GeorgiaHCA** [comment]
![image](https://user-images.githubusercontent.com/46889966/118686842-4c057600-b7fc-11eb-871d-cf4ea91b3d80.png)

**Comment by GeorgiaHCA** [comment]
Hiya @sowmya9507 - would you be able to take a look at this issue and tick off the parts you have already done? Also comment on any part of this which is ambiguous - or which needs extra information?

**Comment by sowmya9507** [comment]
I was wondering whether we could break up the creating webpage on top of the Open Humans Backend. 

- Understanding how to create a project on Open Humans
- Splitting up the required components in the Open Humans backend.
- Also create a user flow of hosting a webpage with the Open Humans

@GeorgiaHCA please let me know if anything else can be added. :)

**Comment by GeorgiaHCA** [comment]
Thanks @sowmya9507 ! 🌻  - I think creating a project on open humans is documentation which was to do with GSOC - @jhlink, @gedankenstuecke - will open source contributors need to create a project on Open Humans in order to be able to work on the platform?/contribute with PRs?

**Comment by GeorgiaHCA** [comment]
The second part seems important. Would you be able to break that down @sowmya9507 into what those components are likely to be and if not what info is needed?

**Comment by GeorgiaHCA** [comment]
Have you managed to create a webpage on top of the open humans backend @sowmya9507 ?

**Comment by sowmya9507** [comment]
> The second part seems important. Would you be able to break that down @sowmya9507 into what those components are likely to be and if not what info is needed?
-- @GeorgiaHCA Sure I am jotting it down and will update it soon.



> Have you managed to create a webpage on top of the open humans backend @sowmya9507 ?
-- I haven't create a webpage but I have created the projected and hosted landing/starting page. I can create the webpage and record the things that I have done -- maybe this might be helpful.?

**Comment by GeorgiaHCA** [comment]
Heya @jhlink! It would be awesome if you could take a look at this issue (and the other ones Milestone 2 ones), and let me know if you I know you had some questions about the wireframe and how things fit together. The dream is for it be possible to follow the issues to make the platform - so if they are missing anything (e.g. work you've done, or complexities I hadn't realised, or missing info), please comment. Your insights would be enormously aappreciated.

**Comment by GeorgiaHCA** [comment]
Same for you @anoura12 and @sowmya9507 :D

**Comment by jhlink** [comment]
@GeorgiaHCA , yes absolutely!! Thanks for the reminder!!

My hands are tied with work at the moment, but I'll be sure to get to it today!

**Comment by jhlink** [comment]
Strong work, @GeorgiaHCA !! 👏  Most of these tasks are great to start. There are a couple that can be removed or updated, but overall I think this will be a great ticket for @sowmya9507 and @anoura12 to tackle!! Great job!!

```
Create a webpage on top of the Open Humans backend.
```
This is a moot task. There are multiple web pages created on top of the OH backend. 

---

```
 Add navigation bar at the top of the page- (this should link to other MVP pages (labelled Milestone 2)
```
The navigation bar in the [simplified wireframe](https://www.figma.com/file/HxqTSdeyAUNMualnBV0PET/Autspace-(WIP)?node-id=172%3A641) should be updated. I don't think the `Share` and `Login` button should be at the top of the page. It doesn't make intuitive design sense, unless this is preferred by the autistic community. 

My suggestion is hide the navigation bar until the user logs in. If the user successfully logs in, then they should see the following items in the nav bar. 

```
Home - My Stories - Share - Logout
```

----

The following tasks are mostly aesthetic, and I think these tasks are good tasks to start for @sowmya9507 and @anoura12 . For the simple explanatory text and the "how it works" guide, the text should be copied verbatim from the simplified wireframe. 
```
Add platform name at top of screen
Add Turing and Autistica logos
Add simple explanatory text
Add simple step-by-step "how it works" guide
```

----

These two buttons should be placed close to each other.  Remember, @sowmya9507 and @anoura12 , implement this visually first. Functional implementation is a stretch goal with respect to this milestone. 

```
 Add sign-up button - (this should link to sign-up flow)
 Add sign-in button (this should integrate with the open humans sign-up process, as users will be making their account with them)
```

----

This task should be lumped along with the moderator feature. This isn't defined in the [simplified wireframe](https://www.figma.com/file/HxqTSdeyAUNMualnBV0PET/Autspace-(WIP)?node-id=172%3A641) on where this might be. My  suggestion is dropping this task for milestone 2 since #16 has yet to be implemented.  Really, this task should be lumped with #99 
```
 Display public experiences (links to #99, #16, #20)
```

**Comment by GeorgiaHCA** [comment]
Hiya @sowmya9507 ! Here's the embed code for the Tinyletter mailing list: 

`<form style="border:1px solid #ccc;padding:3px;text-align:center;" action="https://tinyletter.com/AutisticaTuringCitizenScience" method="post" target="popupwindow" onsubmit="window.open('https://tinyletter.com/AutisticaTuringCitizenScience', 'popupwindow', 'scrollbars=yes,width=800,height=600');return true"><p><label for="tlemail">Enter your email address</label></p><p><input type="text" style="width:140px" name="email" id="tlemail" /></p><input type="hidden" value="1" name="embed"/><input type="submit" value="Subscribe" /><p><a href="https://tinyletter.com" target="_blank">powered by TinyLetter</a></p></form>
        `

**Comment by sowmya9507** [comment]
Thank you @GeorgiaHCA , I will add it immediately :)

**Comment by jhlink** [comment]
@lottycoupat , can you review this ticket for clarity and simplicity? If it looks good, 👍 . Otherwise, let me know if there's anything to change!
@anoura12  and @sowmya9507 , appreciate any feedback as well.

**Comment by lottycoupat** [comment]
@jhlink should we also link to the requirements for the MVP for info [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/platform-designs/platform-requirements/mvp-requirements-list.md?)

**Comment by jhlink** [comment]
Landing page was handled in #114. Closing.
