### ISSUE TITLE
Change the example text in the prototype 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#154]
### Summary

At the moment we have some example text in the prototype about dropping ice cream! It would be best, though to change this to something about autim and sensry processing. 

### What needs to be done?

Replace the text. Something like this could work: 

"Colour-coding on the floor of stations would make it easier for me"

**Comment by GeorgiaHCA** [comment]
Heya @anoura12 - would you be able to do this?

**Comment by mridubhatnagar** [comment]
@GeorgiaHCA I have already made this change in one of my PRs. We had removed the existing text and changed it to sample text.

**Comment by GeorgiaHCA** [comment]
Amazing thanks @mridubhatnagar

**Comment by mridubhatnagar** [comment]
@GeorgiaHCA sharing here the PR link for reference https://github.com/alan-turing-institute/AutSPACEs/pull/144
Also just wanted to confirm was this the page you were referring to?

**Comment by GeorgiaHCA** [comment]
Yep, this is the page - thanks :)

**Comment by mridubhatnagar** [comment]
@GeorgiaHCA so I checked the pages again. Looks like we have made the text change on the moderate experiences page but the view experiences page still has ice-cream text. I am raising a new PR with changed text. 

![Screenshot from 2021-08-09 15-28-39](https://user-images.githubusercontent.com/16894718/128689756-da0cf863-4fa7-4487-b778-d0ab697291db.png)
