### ISSUE TITLE
Implement View Experiences

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#157]
## Description 
This ticket defines functionality and data to be shown when the user views public experiences. 

The user scenarios are as follows: 
- A user clicks the view experience page
- A user scrolls through the list of experiences on the page

## Definition of Done
- Approved, public experiences are shown on the `View Experiences` page for both non-logged-in and logged-in users. 

### Tasks
- [ ] Using the Django database/models, query all experiences with the model property `public` and `approved`. 
- [ ] Display the following experience fields
   - [ ] Date created
   - [ ] Experience description

**Comment by anoura12** [comment]
@jhlink can I take this up?

**Comment by GeorgiaHCA** [comment]
Go for it @anoura12 ! I've assigned you the issue

**Comment by SuziQpid** [comment]
Sorry what's 'parse' through.

**Comment by jhlink** [comment]
@SuziQpid , it means getting all the text in each file and processing it into to some useable form. 
However, for this ticket, we assume that all experience data exists in the Django database. Although OpenHumans will possesses some data, the Django database will be the primary source of data.

Logic to send relevant research data to OpenHumans will be established a bit later in the current milestone.
