### ISSUE TITLE
Completing sign in flow

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#158]
## Description 
This ticket describes steps needed to complete the sign-in flow. 

The user scenarios are as follows: 
- A user signs in on the AutSPACEs webpage
- After completing the sign in flow, a user is shown the `confirmation page`. 

## Definition of Done
A user is able to sign in, through the OpenHumans portal, and upon login completion, the user is shown the confirmation navigation page. 

### Tasks
- [x] When the user clicks sign-in, show the OpenHumans login portal. 
- [x] After signing in, direct the user to the confirmation navigation page.

**Comment by mridubhatnagar** [comment]
@jhlink, both the tasks mentioned in this issue are already implemented and functional in the current project. Sign in currently works like this only.

**Comment by jhlink** [comment]
@mridubhatnagar , wonderful!! Thanks for pointing this out!!

----

Closing because task is already completed.
