### ISSUE TITLE
Fix allcontributors bot for AutSPACEs repo

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/AutSPACEs#159]
**Describe the bug**

Currently the contributor bot that adds users to our contributor list is not working on the AutSPACEs github repo. 

For reference, it is working on our project management repository as you can see [here](https://github.com/alan-turing-institute/AutSPACEs/issues/329).

**Expected behaviour**

1. Go to issue alan-turing-institute/AutisticaCitizenScience#1 
2. Comment "@allcontributors please add" 
3. Contributor bot should reply automatically having added the person as a contributor in a Pull Request
4. User reviews the PR, accepts and merges

Currently, steps 3 and 4 are not working.

**Comment by mridubhatnagar** [comment]
@lottycoupat just wanted to confirm if it is @allcontributors or @all-contributors?

**Comment by SuziQpid** [comment]
Could it therefore be a syntax issue that's easily corrected. Apologies if l've used wrong term.

**Comment by gedankenstuecke** [comment]
This worked on this repo when I used it recently, it only doesn't like adding multiple contributors in one go.
