### ISSUE TITLE
Create Share Experience MVP flow - Screen 1

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#16]
### Summary

Create an MVP share experience flow for the AutSPACEs platform

This consists of two webpages: a page to take user input and a confirmation page once the user has submitted.

A wireframe MVP of the share experience page:

[Simplified share experience flow](https://www.figma.com/file/HxqTSdeyAUNMualnBV0PET/Autspace-(WIP)?node-id=128%3A0)

#### Create Share Experience MVP Flow - Screen 1

- [x] Add navigation bar
  - [x] Add `Home` button, which directs the user to the landing page. 
  - [ ] Add `View Experiences` button, which directs user to view experiences page. 
      - (A placeholder URL will suffice.)
  - [ ] Add `My Stories` button, which directs user to `My Stories` page (current page). 
      - Display *only* to signed-in user
      - [ ] Redirects to `Home` page if page is reloaded after user logs out. 
  - [ ] Add `Share Experiences` button, which directs user to view experiences page. 
      - (A placeholder URL will suffice.)
      - Display *only* to signed-in user
  - [ ] Add  `Logout` button, which logs current user out. 
      - Display *only* to signed-in user
- [x] Add following text prompts with corresponding text inputs
  - [x] "Please Share your experience."
  - [x]  "Suggestions for what could have made your experience better"
- [x] Add check boxes for following items
  - [x] Researchers
  - [x] Publicly

#### For Posterity
Archiving the following tasks for posterity. 
- Store text input in Open Humans back end with appropriate tags - links with #99 
- Save button (#101)
- Submit button (#99)

### Who can help

* Anyone with web development skills to build
* Anyone from the community to review and test*
* the designs are already founded on substantial community feedback and user testing

**Comment by GeorgiaHCA** [comment]
Are you able to take this on @sowmya9507 ?

**Comment by GeorgiaHCA** [comment]
## Community Input

### Have different input options
(A g): “we want to make it as accessible to as wide a scope of the autistic community as we can”
(A d): “accommodate as many different preferences and styles for providing input within the realms of what’s actually achievable”
(A g): “…accommodate as many different preferences and styles for providing input within the realms of what’s actually achievable…some people would prefer the free text option…but others would like to be guided down a more structured process”

### Free text
No word limit (A P d): “please don’t put a word limit, and especially not seeing it count down, because it’s very horrible
Structured input
(A d): split the question up: “Where were you? What time was it? What happened? What effect did it have? and What would you like instead?
(A P d): “you could give options for options, so you could say, for example, ‘would you like a template?’”
(A d): split the question up: “Where were you? What time was it? What happened? What effect did it have? and What would you like instead?” 
Record (vid or speak); upload;
(A d): Have a non-verbal means of inputting information
(A d): “…having the option to…upload photos, or pictures, or voice recordings of people.”
Upload options
(A g): upload pictures of situations that were a problem, so that organisations can go onto the platform and easily see what to change, “because visual things can have much more impact than just…a dense script”

**Comment by GeorgiaHCA** [comment]
### Have a question about solutions or ideas for improvements/what would have made it better
autistic people want to be part of the solution. 
(A d): “…it’s crucial to have a field that can capture…learning and solutions” 
(A d): there are two important aspects: what can autistic people do to change their environments, and what can autistic people do to protect themselves from their environments. 
(A g): “if you’re autistic you want to know…[how] are other autistic people with their expertise…dealing with it? Have they got something to solve the problem?”
(A d): “I want to be able to say and this is what I think would have helped – you know, it may be that it’s not possible to do the thing, you know we can’t probably make the tube quieter very easily, but we do have ideas about what might help and we should be including those”

### Able to save drafts and input experience after event 
(R T d): drafts could be saved but would stay private, and would only be accessed by the person writing them
Other features - Hashtag
(P A d): highlight that as an option, “because I’m still very used to the hashtag”
Tag or hashtag option for people to search for experiences
Give clear confirmation once experience has been submitted.

**Comment by sowmya9507** [comment]
@GeorgiaHCA are there any solutions where community input can be included which might help us to Create Share Experience MVP flow ? Do we re-write these inputs in development perspective which can be told as requirements? It would be easier to understand as well.

**Comment by lottycoupat** [comment]
@GeorgiaHCA @sowmya9507 

Need to add a task/requirement on ensuring there is a bit within the Input Stories page which tells the user that their story will be moderated if made public.

**Comment by lottycoupat** [comment]
@jhlink do we need to add information on the "successfully submitted story" page?

**Comment by jhlink** [comment]
> @jhlink do we need to add information on the "successfully submitted story" page? 

Yes, I'll be sure to include that info when I rework this ticket.
