### ISSUE TITLE
Documentation Request: Add instructions on how to view Django Database

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#165]
## Description
After creating a django project, sometimes it's useful to see the tables, database, and any other information within the database itself. 

In the relevant documentation section, add steps to inform users on how to view a postgresql database. 

Gist 
- Run `docker exec -it autspaces_db_1 bash`
- In the subsequent terminal, run `psql --username=autspaces`

ét voila! 

For reference, [here are the PostgresSQL commands](https://www.postgresqltutorial.com/psql-commands/) that may be used to view tables, schemas, and recorsd.

**Comment by gedankenstuecke** [comment]
done!
