### ISSUE TITLE
Implement Share Experiences Page: Add Properties to PublicExperiences model

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#170]
## Description
Public Experiences must support additional data fields when displaying and storing experiences. 

## Definition of Done
Add the following properties to the Public Experiences model, if they do not already exist. 
- [x] Creation date
- [x] Unique ID 
- [x] User ID 
- [x] Experience Text
- [x] Suggestion Text
- [x] Sharing permissions, with values (public and research)
- [x] Moderation Review status
   - It should only have four states: `Draft`, `In Review`, `Approved`, `Rejected`. 

## Test
Verify that the changes to the Public Experiences model do not break the database schema

### Steps to Test
- After every model change, run `python3 manage.py makemigrations` then `python3 manage.py migrate` within the Docker web container. 
- If no errors occur, the change was successfully migrated.

**Comment by callummole** [comment]
Closed by #401 and #414
