### ISSUE TITLE
Implement Share Experiences: Experiences are stored in Django Database on Submission

### ISSUE THREAD

**Issue by jhlink** [alan-turing-institute/AutSPACEs#173]
## Description
After a user has populated all the data fields for a Public Experience, submitted experiences should be stored on the Django database while adhering to the following requirements. 

## Definition of Done
When the user has clicked the `Submit` button on the Share Experiences page...
- [x] `Creation Date` should be set to today's date
- [x] `Unique ID` field should be populated with a randomly generated UUID. 
- [x] `User ID` field should be populated with the user's OpenHumans ID, which is obtained through the OpenHumans member model. 
- [x] `Experience Text`, `Suggestion Text`, `Moderation Review Status`, and `Sharing permissions` are all saved according to their current state on the web page.

**Comment by callummole** [comment]
Closed in #401
