### ISSUE TITLE
Toggler View for Navbar

### ISSUE THREAD

**Issue by soledadli** [alan-turing-institute/AutSPACEs#176]
## Description
This task defines navigation bar design on the website.

A toggler view for navigation bar can help users view the contents when using different platforms.

## To Do
- [ ] Decides one consistent design for the navbar (Moderator & MyStories & Login Confirmation views are quite different than others)
- [ ]  Add Toggler View for all

**Comment by gedankenstuecke** [comment]
closed as stale for now!
