### ISSUE TITLE
Add design decision for location of css information to developer documentation

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/AutSPACEs#188]
### Summary

At the moment all the css is in the html files. This feels very repetitive and difficult to scale. Should we be pulling css from specific style files? If not, why not 😄 

### Deadline 

No deadline, this is a developer style decision.

### What needs to be done?

- [ ] Infrastructure team to discuss at a meeting (or in this issue)
- [ ] Decision added to developer contributing guidelines https://github.com/alan-turing-institute/AutSPACEs/blob/main/dev_readme.md

### Who can help?

* @jhlink 
* @sowmya9507 
* @anoura12 

---

**Comment by soledadli** [comment]
@jhlink Hi James. I am working on refactoring the CSS codes recently. Is there a folder where I should put the CSS codes inside? Should I put the CSS files in the `Static folder` with the image folder together? Thanks for the help!

**Comment by soledadli** [comment]
> @jhlink Hi James. I am working on refactoring the CSS codes recently. Is there a folder where I should put the CSS codes inside? Should I put the CSS files in the `Static folder` with the image folder together? Thanks for the help!

I have put the CSS files in '/static/css/' folder and am working on this branch: https://github.com/alan-turing-institute/AutSPACEs/tree/build-tmp to create templates and refactoring the codes on front-end.
