### ISSUE TITLE
Collect decisions for design system of the platform

### ISSUE THREAD

**Issue by soledadli** [alan-turing-institute/AutSPACEs#200]
### Summary
The issue is to collect decisions for design system of the platform.
For design systems, we are focusing on the following perspectives
* Typography 
* Colour palette (primary and secondary)
  * Accessible option with transparency/saturation
* Grid/Spacing/Padding
* Components
  * Buttons 
  * Components 
  * Toggles
  * Menus
  * Forms
  * Tables

### Deadline 
Before A/B testing on Nov. 14
### What needs to be done?

Add any ideas for design system and finalize decisions. 

### Who can help?

@soledadli  @BrainonSilicon

**Comment by soledadli** [comment]
Here is the [documentation](https://docs.google.com/presentation/d/1SCBVKfA6l2OlOuFOR2xKyU9804OpHr1DCq607bMJ2P8/edit?usp=sharing) for the design system.

**Comment by soledadli** [comment]
Here is the [resource document](https://hackmd.io/25eOYHB6TkGHdCJp8-JtXA) for the design system.

**Comment by soledadli** [comment]
The Autism Society has really great accessibility tools. https://autismsociety.org/

**Comment by gedankenstuecke** [comment]
Made issue https://github.com/alan-turing-institute/AutSPACEs/issues/369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
