### ISSUE TITLE
Add Reviewer role via Django Admin

### ISSUE THREAD

**Issue by anoura12** [alan-turing-institute/AutSPACEs#204]
### Summary
The goal of this issue is to create a reviewer role/permissions through Django admin. The reviewer would be reviewing ambiguous experiences and take decisions for user requests to revisit their experiences.

### What needs to be done?

- [ ] Create a Reviewer status
- [ ] Allow admin to set a moderator as a reviewer

### Who can help?

The dev team.

**Comment by anoura12** [comment]
@jhlink Could you add the rest of the tasks to this task list?

**Comment by gedankenstuecke** [comment]
I was just going through potentially stale issues. I think this is now actually implemented, do you agree @callummole & @helendduncan?

**Comment by gedankenstuecke** [comment]
Done thanks to @callummole & @helendduncan
