### ISSUE TITLE
Create a test deployment for the AutSPACEs platform 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#210]
### Summary

@badgermind will use a personal server to deploy a test version of the site for everyone to be able to look at and share ideas. This will be semi-public for now to help collaboratively design the platform. The deployed version can be changed so people can see different designs and compare easily to gather feedback. 

We could then consider circulating it more widely to gather more feedback.

**Comment by soledadli** [comment]
> I think this sounds good - we just have to be really careful with our ethics approval.
> 
> I don't think test deployment is a problem, we just have to put a banner on every page to make it clear that the deployment is for TEST purposes only and that the data should be considered entirely open - so no one should add anything sensitive!

I will add the banner per page then.

**Comment by soledadli** [comment]
@badgermind Let me know if you need help with the deployment. I'd love to contribute to the front-end part. 🎆

**Comment by badgermind** [comment]
@KirstieJane I'm also planning to restrict login to members of the wider team, defined initially as those who come to the Thursday meetups, and implemented by filtering on email address.

**Comment by badgermind** [comment]
@soledadli it's your front-end code I'm planning to deploy :)
