### ISSUE TITLE
Feedback on current platform prototype 

### ISSUE THREAD

**Issue by soledadli** [alan-turing-institute/AutSPACEs#213]
### Summary
Feedback on current platform prototype  
* If you have Docker installed, you can run the platform locally with the branch: [build-tmp](https://github.com/alan-turing-institute/AutSPACEs/tree/build-tmp).
* If you cannot run the platform locally, here are the screenshots I took for the current platform.
 * Homepage

A new design has been implemented on the platform. Please feel free to share your feedback. Here are some perspectives for advice inspiration:
* Navigation of the platform
  * Can you easily find the information you need on the platform? 
* Information layout per page 
  * Does the current layout help you quickly find the information you need?
  * Are the current information layout comfortable and convenient enough for you to read and use the platform?
* Color
  * Are the colors calm/comfortable enough for you? 
 * Anything else? 

### What needs to be done?
Please feel free to share your opinions and suggestions in the comment section.  

### Who can help?

Anyone!

### My Stories Page for Logged In Users
![storypage](https://user-images.githubusercontent.com/67457005/154502496-185e645c-eae2-459c-9a29-ce7e83ad1c36.png)
### Share Stories  Page for Logged In Users
![Share Stories](https://user-images.githubusercontent.com/67457005/154502807-1e67c76f-9b26-44e0-9320-db5d6a854b8a.png)

**Comment by soledadli** [comment]
# Homepage:
![AutSPACEs Landing Page (1)](https://user-images.githubusercontent.com/67457005/151981630-81f1d116-587b-4048-a396-f975271f2931.png)

**Comment by soledadli** [comment]
# View Stories
![View Stories](https://user-images.githubusercontent.com/67457005/151982151-a33b185f-64ec-45e4-a3ca-1bab587c2c02.png)

**Comment by soledadli** [comment]
# About Us
![AutSPACEs About Us Page](https://user-images.githubusercontent.com/67457005/151983150-67edce21-f9d1-4cbc-ac6f-3d7fe365ed00.png)
![AutSPACEs About Us Page (1)](https://user-images.githubusercontent.com/67457005/151983121-9a6a3389-4fbe-44a8-abcf-e4a5b25dd2e8.png)

**Comment by GeorgiaHCA** [comment]
Thanks @SuziQpid

**Comment by SuziQpid** [comment]
In both the opening page of the repository and the platform page describing AutSpaces the phrase ' collect together ' is used. It's clunky. Better to use ' collate' or simply leave it as ' collect'.

**Comment by SuziQpid** [comment]
I support Susannas comments about the colour choices at the top of the landing/ log in page. You need the main heading underneath the first menu bar to be a non blue shade. It doesn't offer a good enough contrast to the turquoise / green tone of the menu bar. Wasn't there a stronger lilac/ purple tone or a strong silver that could be used.

**Comment by SuziQpid** [comment]
Dear Georgina, 

There’s a difference between the goals mentioned on the welcome page of the repository and the landing / login area of the platform. There are four on the welcome page and three on the landing page. 

The extra one comes from the aspiration to collect the stories.

Also the  goal order is different. The order is better on the landing page and l think you should add the fourth one of collecting the stories at the top of those three. Then you’re consistent. There’s a slight difference in the wording too. The landing page flows the best. 

Where exactly are the ‘guidelines’ situated. I’ve commented on issue 213. Do you need to create another issue for me to look at the guideline language. Sorry to be so literal but this is all such foreign yet weirdly familiar territory. I just want to remain useful to the group. 

Suzanne lwai
