### ISSUE TITLE
Add moderator guidelines and code of conduct

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#220]
### Summary

It would be good to add moderator guidelines and the code of conduct to the platform.
They currently exist in the project management folder in a basic markdown file: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/Moderation/moderator-guidelines.md. A simple page which follows the design of the rest of the platform would be perfect! 

### What needs to be done?

- Add a page for moderator guidelines and a page for the code of conduct
- Use the text from the files here: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/Moderation/moderator-guidelines.md
- Stylise according to the platform design.

**Comment by GeorgiaHCA** [comment]
Additional steps would be to have a pop-up or reminder for people who are writing about others so they know to use the specific guidelines

**Comment by gedankenstuecke** [comment]
This is now closed thanks to #581!
