### ISSUE TITLE
Create test versions of remaining front end pages 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#240]
## Summary

While most of the platform has been deployed there are still pages that need to be created. This issue is not to build those pages but to design them and have them available for testing. 

## Date Due by

1st September 2022

## Details

Pages we are missing on the deployed platform 

* Enter experience page
* Sign up demographic info collection page

**Comment by gedankenstuecke** [comment]
Kept open issue on demographics in #453
