### ISSUE TITLE
Update design-system README 

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/AutSPACEs#251]
## Summary

The design-system folder is home to the resources and information about the overall style and design of the platform. The README is a description of what the folder contains and needs to be updated to reflect the recent files that have been added. 

## Details

* Some preliminary information has been added to the folder in a file titled 'design-code-20220222.md`. The README needs to be edited with a description of that file and what the prelimary style information is. 

## Suggestions for tasks that can fix this issue

* [ ] Edit the README file in [`design-system`](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/platform-designs/design-system) so that there is a bullet point list
* [ ] Add the file `design-code-20220222.md` to the list as a linked document. (see examples [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/platform-designs/ARCHIVE-fujitsu))
* [ ] Write a description of the `design-code-20220222.md` document.
* [ ] Submit a PR!

## Who can help

Anyone can help! 

Read over our [Contributors Guidelines](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/.github/CONTRIBUTING.md) to get started (and specifically the instructions [here](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/.github/CONTRIBUTING.md#making-a-change-with-a-pull-request) if you're new to GitHub). 

If you are unsure about any of the steps, please comment on this issue or reach out to one of the contributors.

**Comment by gedankenstuecke** [comment]
Closed as it's very stale and outdated by now
