### ISSUE TITLE
Gather information for moderation paper 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#256]
## Summary

Over the course of co-creating the code of conduct we have encountered a huge amount of nuance and a lot of thought has gone into it. We want to capture the thinking and insights from the work in a research paper. The first stage is to collect together the pieces of work, source materials and notes, and makee sure we keep a record as we continue to develop the work.

**Comment by GeorgiaHCA** [comment]
A great suggestion from @arronlacey is to use a consort diagram to methodically search published papers

**Comment by GeorgiaHCA** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC539417/

**Comment by GeorgiaHCA** [comment]
https://www.prisma-statement.org//

**Comment by gedankenstuecke** [comment]
Closing as moderation paper is drafted!
