### ISSUE TITLE
Present code of conduct and moderation guide

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#257]
## Summary

We want to present the finished code of conduct and guidelines on presenting on behalf of others to the community at the next meet-up session

## Date Due by

Thursday 27th January 

## Details

This is to collect precise feedback on the code of conduct and guidelines 

## Who can help

James, Georgia, and Susanna

**Comment by SuziQpid** [comment]
Dear Georgia,

I’ve actually added something to lssue#249 ….better late than never. 

Bit lost with how l test the site as it currently stands. Please advise. When do we think Meetups are starting again or will there only be one or two before the repository officially opens. 

Best Wishes 
Suzanne lwai

**Comment by GeorgiaHCA** [comment]
Hi @SuziQpid thanks for your contributions - it's really helpful 😸 ! We have a development team working on the platform and I'll update you as soon as we have the design ready for testing. We'll probably restart regular meet-up sessions in November and do lots more testing before it's launched.

**Comment by SuziQpid** [comment]
Cool. ! 

Suzanne lwai

**Comment by gedankenstuecke** [comment]
I'm closing this as we've further presented the moderation approach both technically and also the process 🙂
