### ISSUE TITLE
Design demographic collection 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#265]
## Summary

We need to design an inclusive and fine-grained sign-up process to collect information about users. 

## Details

This requires sensitivity and nuance. It would be wonderful to co-create this based on best practices. We will probably create a version of this as an MVP based on recommendations from researchers, along with existing recommendations from the community - and iterate from there. 

## Who can help

Anyone! If you have views on this topic please post them in the comments section.

**Comment by gedankenstuecke** [comment]
Kept remaining tasks in #453
