### ISSUE TITLE
Netlify page for meet-up sessons

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#270]
## Summary

Create a Netlify page to support community engagement in meet-up sessions 

latest version -----> https://www.notion.so/Welcome-to-the-AutSPACEs-Meet-Up-Page-0ad17d5c0f8045be8618686531068622 

## Details

We need a page to support fortnightly sessions which are 

* help orientate users with info such as time, agenda, schedules 
* accessible to diverse autistic collaborators
* clear and contain comprehensive information
* point to useful additional resources and links 

## Suggestions for tasks that can fix this issue

* [x] Survey rseearchers on info needed 
* [x] Create page 
* [ ] Upload design specs doc to repo
* [ ] Make sure it meets accessibility requirements 
* [ ] Test with diverse autistic users
* [ ] Iterate!

## Who can help

This task is owned by @BrainonSilicon but feedback/comments/suggestions welcome from the community!

**Comment by gedankenstuecke** [comment]
Got a wiki for that, cf https://github.com/alan-turing-institute/AutSPACEs/wiki/Meetups  😉
