### ISSUE TITLE
A list of all the decisions that need to be made about moderation

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#281]
## Summary

This issue contains all the decisions that need to be made about the moderation process. 

## Suggestions for tasks that can fix this issue

There are a number of different suggestions, and lots of useful discussion with many perspectives. Ultimately a decision has to be made. Below are options which need decisions:

To collect thoughts on the following decisions, we will put a survey together for the community to respond to. This will in turn help inform the output of our decisions.

**Comment by gedankenstuecke** [comment]
Superseded by moderation paper based on additional 2 years of work 😂
