### ISSUE TITLE
Make buttons work correctly

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#29]
### Summary

Currently the html in the PRs uses gov.uk template html. This is enabled as a prototype using gov.uk software.  

### Deadline 

20 Feb

### What needs to be done?

Modify the components so they do not require gov.uk prototypinig kit. 

Mozilla is a great rsource for html of functoining components and details broswer compatability: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit#using_submit_buttons

### Who can help?

Web developers/coders

**Comment by jhlink** [comment]
I'm not sure how relevant this is to Milestone 2. Going to remove the label and add this as an enhancement.

**Comment by GeorgiaHCA** [comment]
I'm going to close this issue as it is now outdated
