### ISSUE TITLE
Report broken links

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#296]
## Summary

If you find a broken link anywhere in the Autistica GitHub let us know by writing where it is or copying the url in a comment below 👇 and we will fix it ASAP. Thank you!! 

### Want to fix the links yourself? 

Go to issue [#423](https://github.com/alan-turing-institute/AutSPACEs/issues/297)

**Comment by SuziQpid** [comment]
Dear All,

Although fixing the broken links 423 is now closed, ld just like to say the Git Hub app on an iPad is incredibly glitzy.

I can only access open issues whatever the No is properly through the Safari Browser. Haven’t tried it via Chrome or Firefox. 

I don’t get a 404 labelled message on Git hub when l try through the app. I get a ‘something went wrong try again rectangle bordered box’ 

You’re doing well guys. 
Suzanne lwai

**Comment by GeorgiaHCA** [comment]
Thanks @SuziQpid! That's really useful feedback. We're currently merging the project management repository and the development repository and trying to make it more user-friendly in the process, although for a little while as the changeover happens it will be more confusing until we integrate everything fully. Thanks for testing on an iPad - by glitzy do you mean glitchy? I'm not sure how to make GitHub more iPad compatible but I can make it a new issue so we can try to solve it as part of the repo refresh.

**Comment by SuziQpid** [comment]
Dear Georgia,

Yes l meant glitchy! Tired typing lm afraid. I suspect iPads don’t like certain apps. I think it’s worth advising people using smaller devices on the move to access Git hub via their main browsers rather than the app.

When are we resuming meet-ups ? 

Suzanne lwai
