### ISSUE TITLE
Text-to-speech

### ISSUE THREAD

**Issue by osw** [alan-turing-institute/AutSPACEs#308]
# Overview
*As a user of the platform
I want to have the option of having the computer read text as speech
So that I can get a better understanding of what I need to do*

# Requirements
- [ ] Use a high-fidelity speech synthesiser
- [ ] Use a softer voice for the synthesiser
- [ ] Have the ability to slow down the rate of speech
- [ ] Have the ability to speed up the rate of speech

# To be confirmed
* Should users be given the option to select different voices?

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
