### ISSUE TITLE
Accessibility -  More Selective Screen Reader

### ISSUE THREAD

**Issue by ghost** [alan-turing-institute/AutSPACEs#319]
A wireframe design and justification that builds on the current showcase of the screen reader feature for accessibility. The screen reader will need to be more selective in its functionality.  Have a button that would allow the user to select a particular block of text clearly.

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
