### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#34]
# Summary

Design a navigation bar which links users across site. Must be simple and accesible. 

# Deadline

16th Feb 2021

# What needs to be done?

- [x] Find a good, useable nabigation bar with open source, open licensed code to adapt for the platform (simple design, obvs accesible, top of page)
- [x] Decide what pages the navigation bar needs to link to 
- [ ] Also what features should be there- e.g.
        - [ ]  crisis help
        - [ ] settings
        - [ ] some accesibility features
- [x] Take the code and modify it for AutSPACEs linking to the original source and referencing it in the repo
- [x] Keep the design as basic as possible for now as we are still at the MVP stage. 
- [x] Add this to the code for the website so that it becomes part of the MVP

# Who can help

JS is working on this.

**Comment by jhlink** [comment]
The navigation bar already exists. Further additions should be captured in a new ticket, not in an existing ticket. 

Simplicity is the name of the game for Milestone 2. 
Closing.
