### ISSUE TITLE
Rewrite previous issues so they are up to date

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#358]
### Summary

@jiraslama and @katoss did lots of work together on design features and user testing/community recommendations which are currently preserved in old issues. These also include feedback from the AutSPACEs community. We should rewrite the issues to reference the current platform and workflow while making sure to credit/keep a record of their work.

**Comment by gedankenstuecke** [comment]
I've linked them all up in #369 👍
