### ISSUE TITLE
Apply to demo at AI UK 2023

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#360]
### Summary

Submit AutSPACEs AI UK exhibition call: https://www.eventsforce.net/turingevents/frontend/reg/tOtherPage.csp?pageID=87652&eventID=242&traceRedir=2

### Deadline 

Wednesday 30th, 5pm 

### What needs to be done?

Decide on approach, submit application

Should be interactive. Some ideas: 
- demo the platorm 
- invite autistic collaborators
- research priorities - ranking game
- showcase the moderation? should we publish? 
- what sensory processing differences might be like? 

### The questions you'll be asked are below:

Applicant details, including collaborators
Demonstration title and description
How it links to the national scientific and technology capability priorities
Relevant links (content / journals / org websites)
How the demonstration will draw interest
 How it aligns to the Turing's EDI strategy and how the demonstration will be inclusive and accessible
Supporting statement

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA submitted the application on Nov 30. 🎉
