### ISSUE TITLE
Organise a meet-up session for Jan 2023

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#362]
### Summary

We want to start up regular AutSPACEs community meet-up sessions again throughout 2023. We will begin by organising an initial session and promote it, and we will use it to decide on the format, frequency and pattern of ongoing meetings.

**Comment by gedankenstuecke** [comment]
Decided on January 12, 1-2pm for the community meeting. Will advertise it in the newsletter (see #363) and do further outreach as well.
