### ISSUE TITLE
Apply for enrichment students 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#398]
### Summary

AutSPACEs is a great opportunity for Turing enrichment students. We want to submit an application and accept applicants on a rolling basis. 

### Deadline 

Submit before Christmas break 

Draft here: https://docs.google.com/document/d/1wHLxHhkT1mE-BXF2YH9UjVnfSqvHRPDY3BZOClcPs8I/edit

**Comment by gedankenstuecke** [comment]
Submitted [our project](https://docs.google.com/document/d/1Ots8Owhg6FD4UcD9o4SSX-XWdK_f6LvxZLI1h3ML7us/edit) now to give students a chance to read and apply.
