### ISSUE TITLE
Send Christmas newsletter 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#399]
### Summary

We want to send a Christmas newsletter inviting people to a co-working session in January and introducing the new team before the Christmas break

Draft is here: https://hackmd.io/@UvBViadIQhWQzrT5zhenTA/H1YU3pEdi

Georgia will write updates, Bastian will provide the interview

**Comment by gedankenstuecke** [comment]
Closing as duplicate of #363, will copy the link there!
