### ISSUE TITLE
Include Bypass links

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#40]
**Is your feature request related to a problem? Please describe.**

This feature is related to it being often more difficult to navigate a page using a screen reader. It would make the website more accessible. 

**Describe the solution you'd like**

Having a simple set of bypass links available, provides users the ability to bypass blocks of content that are repeated over multiple web pages. Useful for screen-readers and keyboard users, bypass links are visibly hidden until focused via the tab key, when they appear at the top of the viewport.

https://frend.co/components/bypasslinks/ 

**Additional context**

There is an open source, MIT licensed code for adding bypass links created bt Frend: https://github.com/frend/frend.co
This explains the reason for the bypass links as well as guidance for using them

This may be easier to intgrate at a later stage once the platform MVP has bn built?

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
