### ISSUE TITLE
Delete PublicExperience object on (local) database when deleted on OH

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#406]
### Summary

Currently when a user deletes a story from the OH database via the AutSPACEs site - the local PE object containing the contents of the story is not deleted

### Deadline 

Feb 2023

### What needs to be done?

- [x] In functions where `request.user.openhumansmember.delete_single_file` is called, delete the corresponding PE object at the same time

### Who can help?

* @helendduncan 
* @callummole 

---

**Comment by callummole** [comment]
Closed in #410
