### ISSUE TITLE
Add confirmation warning for deletion of files

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#407]
### Summary

Add a confirmation/warning step when a user is about to delete OH files

### Deadline 

Feb 2023

### What needs to be done?

- [ ] Enact a warning (?page?) when `request.user.openhumansmember.delete_single_file` is called

### Who can help?

* @callummole 
* @helendduncan 

---

**Comment by gedankenstuecke** [comment]
That's probably obvious, but just waned to spell it out regardless in case it helps: To me both this and #406 are somewhat related in that the `delete_single_file` method will in either cases not be called directly from the front-end but in both cases this will probably be encapsulated in a view that reacts on a `POST` request.

**Comment by gedankenstuecke** [comment]
I think this has been closed by #410?

**Comment by callummole** [comment]
Closed in #410
