### ISSUE TITLE
Align `PublicExperiences` model with `ShareExperienceForm`

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/AutSPACEs#412]
### Summary

Currently the `PublicExperiences` model and the `ShareExperienceForm` have different names for some fields. The `ShareExperienceForm` should ideally be a subset of the fields in `PublicExperiences`, so that the form can be created from the model itself, which would be neater and easy to follow.

### Deadline 

Jan 2023

### What needs to be done?

- [ ] Updating `PublicExperiences` model to match `ShareExperienceForm` 
- [ ] Make migrations.
- [ ] Remove redundant code.

### Who can help?

* @callummole 
* @helendduncan 

---

**Comment by gedankenstuecke** [comment]
I think this is actually the case by now as much as it can be (e.g. the `PublicExperience` model doesn't have the `viewable` flag as only public experiences fall within that model)! 🎉
