### ISSUE TITLE
Prepare for Seminar on "Public Space, Play and Neurodiversity"

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#415]
### Summary

We will be delivering a 10 minute online presentation about AutSPACEs followed by a Q&A

### Detail

This seminiar relates to [ASD Publics](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fasdpublics.eu%2F&data=05%7C01%7Cgaitkenhead%40turing.ac.uk%7C44712e4700a741f3ff7208daf3f4d385%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638090530090933694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t%2FKJPaQ%2ByuvLMFugElHszcnAeJzutkiN0180NlC%2BxKQ%3D&reserved=0), which was funded through the New European Bauhaus. The project aims to improve public space, and particularly public playgrounds, for and with children with autism and their families.

There will be speakers from Play Wales (children and play spaces), Talamaca (autism and public space & participation, Italy), and Centre National de la Recherche Scientifique (Paris, autism & public space). 

### Deadline 

20th Sending presentation to organisers
The event will take place on **January 24 11-13H CET.** 

### What needs to be done?

- [x] Create and send slides
- [x] Time and run through
- [ ] Deliver presentation
- [x] Upload slides to Zenodo and add to repository 

### Updates

Our title is "AutSPACEs: co-creating a citizen science platform"

The seminar will be delivered by Bastian (2 min intro), Georgia (6 min presentation), Otis (1 min speech), and Helen (1 min run through)

We may adapt slides from the most recent Autistica conference as it has a similar themes

**Comment by helendduncan** [comment]
[AutSPACES_github_and_frontend_images.pptx](https://github.com/alan-turing-institute/AutSPACEs/files/10446884/AutSPACES_github_and_frontend_images.pptx)

Selected screenshots if useful @GeorgiaHCA

**Comment by GeorgiaHCA** [comment]
Thanks @helendduncan !

**Comment by GeorgiaHCA** [comment]
Zenodo link to the slides: https://zenodo.org/record/7550764

**Comment by gedankenstuecke** [comment]
Great, I think with this we could close the issue or do folks want to keep it open until we've delivered the talk? :)

**Comment by helendduncan** [comment]
No strong feelings either way
