### ISSUE TITLE
Arrange next meet-up session

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#416]
### Summary

We need to arrange the next AutSPACEs meet-up session!

Georgia will be on leave from 4th Feb so if we want to keep it on Thursday the 2nd might be best?
Feedback from the focus group was to have a 90 minute session and to 

### Deadline 

Meet-up session will be Thursday 2nd Feb 12-13:30
Future meet-ups will be on the first Thursday of the month

### What needs to be done?

- [x] Decide on date 
- [x] Create agenda
- [x] Prepare resources
- [x] Advertise session and send invite

**Comment by GeorgiaHCA** [comment]
@BrainonSilicon is there a time on Thursday 2nd Feb that works for you?
@callummole and @helendduncan would one of you be available to screen-share and run through the current platform?

**Comment by BrainonSilicon** [comment]
I think the hope was to continue keeping it across a lunchtime so first thursday of the month 12-1:30?

**Comment by GeorgiaHCA** [comment]
Perfect let's go with that!

**Comment by gedankenstuecke** [comment]
The event happened!
