### ISSUE TITLE
Send out January newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#417]
### Deadline 

Try to send out by end of this week (Friday 20th)

### What needs to be done?

- [x] Draft newsletter: include invites to meet-up session and seminar and link to podcast
- [x] Interview community member for spotlight
- [x] Review
- [x] Send!
- [ ] Upload to GitHub

**Comment by GeorgiaHCA** [comment]
@callummole would you still like to do the interview for the newsletter? It would involve answering a few short questions and sending a photo or image you'd like to go with the interview

**Comment by gedankenstuecke** [comment]
Link to register for the seminar at the 24th is: https://symposium.uoc.edu/93279/detail/international-online-seminar-lpublic-space-play-and-neurodiversityr.html

**Comment by gedankenstuecke** [comment]
This has been sent, skipped the interview this time to send it in time for tomorrow's seminar. Still needs to be put into the GH repo though!

**Comment by gedankenstuecke** [comment]
closed as part of #427
