### ISSUE TITLE
Check you’re using proper headings

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#42]
### Summary

It’s important that any headings you’re using are styled properly. This is because some users with visual impairments use tools called ‘screen readers’ that read out page content to them

### Deadline 

20/02/2021

### What needs to be done?

Screen reader users often jump through the list of headings in a document so they can skip to the content they’re looking for.

* If you’re styling headings just using bold, or by using bigger font, then screen readers will not recognise them as headings. This will stop users from skipping straight to the content they need.

* To check your headings are styled properly, open up the tool you use to edit your website (often known as a ‘content management system’) and check the headings on your sample pages. They’re styled correctly if something like one of the following applies:

    * your headings are styled as things like ‘Heading level 2’, rather than ‘Normal text’
    * you can see tags like ##, ###, H2 or H3 in <>

### Who can help?

Requires basic html knowledge

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
