### ISSUE TITLE
Tidy codebase

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/AutSPACEs#421]
### Summary

Catch-all issue for some code refactoring and tidying up. 

### Deadline 

Feb 2023

### What needs to be done?

Removing redundant code:
- [x] Unused url patterns 
- [x] unused views

- [x] Separate helper functions from views
- [x] remove unused html
- [x] abstract repeated html.
- [ ] check the app logic is in model, not views, to avoid repetition (https://django-best-practices.readthedocs.io/en/latest/applications.html#make-em-fat)

Coding style
- [x] Ensure readability and django coding style: https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/.
- [x] Add linter.
- [x] add comments.

### Who can help?

* @helendduncan 
* @callummole

**Comment by callummole** [comment]
Adding this aspirationally to Milestone 2. Thought process is that once we have an MVP we will want to look more widely for contribution, user testing etc. To help with this the codebase should be clear and easy to follow.

**Comment by gedankenstuecke** [comment]
I think we're now basically done with this one after @helendduncan already added the linter in the GH action setup!
