### ISSUE TITLE
Check pages are usable when stylesheets are disabled

### ISSUE THREAD

**Issue by Angelsaur** [alan-turing-institute/AutSPACEs#43]
### Summary
The way a page looks is controlled by something called a ‘stylesheet’. It defines things like the way a page is laid out and any font colours.

Your content should still be usable even if stylesheets are disabled, or are not loading properly. This means it’s still possible for users to complete any relevant tasks or find important information - for example, look for opening hours or contact details, or navigate their way to the form they need to fill out.

### Deadline 
20/02/2021

### What needs to be done?
You’ll need to check your sample pages are still usable when stylesheets are disabled. Test this by copying a URL from your website and pasting it into the WAVE tool. Once you’ve done that, select ‘no styles’ from the panel on the left-hand side of the tool. This should give you a much more basic view of the page.

Check whether you can still use the content to complete any relevant tasks

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
