### ISSUE TITLE
Submit to EU Citizen Science prize

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#434]
### Summary

As part of the _IMPETUS_ project – which was funded by the European Commission – the folks at Ars Electronica are [organizing the first _European Union Prize for Citizen Science_](https://ars.electronica.art/citizenscience/en/opencall/), with prize money between 20k and 60k € being awarded in the categories _Grand Prize_, _Diversity & Collaboration Award_, and _Digital Communities Award_. 

By now the commission has clarified that UK projects can apply despite the issues around the Horizon Europe participation, so AutSPACEs is eligible to apply for the award.

### Deadline 

March 13, 2023

### What needs to be done?

- [x] Check forms to see what is needed
- [x] Write application
- [x] Submit application before deadline

### Who can help?

* @BrainonSilicon 
* @GeorgiaHCA 

---

**Comment by gedankenstuecke** [comment]
Items asked for in the application/submission: 

* Timeframe
* Abstract (1000 characters) 
* Description (5000 characters)
* Research question (1500 characters)
* Initiative Team (1500 characters)
* Citizen Engagement: give a profile of the community of citizen scientists and their role, incl recruitment (1500 characters)
* How will the prize money benefit your community? (1500 characters)
* Credit / Please provide credit information if any (1000 characters)
* Support received from / Funding (1000 characters)
* Keywords
* Software used (1000 characters)
* Hardware (1000 characters)
* Creators / Creator groups (Names, Biography/History)

**Comment by BrainonSilicon** [comment]
So down! Let's do it 🚀

**Comment by gedankenstuecke** [comment]
Thanks for chiming in @BrainonSilicon! I've managed to set aside enough time to get a first draft of the whole application materials written up. My [first draft is here](https://docs.google.com/document/d/1UlzzF3MsSRe9V-04xlkRBtFGueSxG3HsltxaNUvR1SQ/edit?usp=sharing), and I'd absolutely love and appreciate anyone that could find some time to read over it, suggest improvements etc. 

In particular I've tried my best to outline the historic process behind AutSPACEs but if someone could double check those that would be amazing!

**Comment by BrainonSilicon** [comment]
Will take a look at it this week 🚀

**Comment by gedankenstuecke** [comment]
Thanks! 🙏

**Comment by GeorgiaHCA** [comment]
We have the Scriberia sketches which might be helpful? I think it would also be fab to have some community members speak directly for the video? Maybe also testimonials and screenshots of the platform?

**Comment by gedankenstuecke** [comment]
I can check with the folks that did the recording of our last talk how close they are to get a copy of that, otherwise making a multi-participant video at this stage could be quite last minute with the looming deadline?

**Comment by GeorgiaHCA** [comment]
Yeah, agreed - if there is a recording of that it would be great - there's also earlier recordings available with community members which is maybe an option but it would be good to have a recent one

**Comment by GeorgiaHCA** [comment]
Yes! They are listed here: https://github.com/alan-turing-institute/AutisticaCitizenScience/tree/master/project-communications/presentations

**Comment by gedankenstuecke** [comment]
Thanks!

**Comment by gedankenstuecke** [comment]
A big thanks to @KirstieJane for doing some additional reviewing after @BrainonSilicon had already done an amazing pass as well! I've just submitted it through their online portal and [deposited a copy of the final application on GH](https://github.com/alan-turing-institute/AutSPACEs/blob/main/00-project-documentation/communication/applications/2023-EU-CS-Prize.md). 

The jury for the prize is meeting between April 20-23. Successful applicants are expected to be informed within 30 days of that meeting, a public announcement will be made in June! 🤞
