### ISSUE TITLE
Logging activity on files.

### ISSUE THREAD

**Issue by callummole** [alan-turing-institute/AutSPACEs#440]
### Summary

We do not track activity across a file's history. For auditing we should track this information.

### Deadline 

Feb 2023

### What needs to be done?

This is a suggested list. Please update as the task gets clearer.

- [x] Include an originally posted date (or originally/most recently made public)
- [x] Decide what actions should be logged
- [ ] Write a module that, given an action, returns a logging string.
- [x] Decide how to track the logs within a file. The simplest method would be to have a field `log` that is just a list of strings. But there might be more sophisticated or well-thought through ways out there.
- [ ] Decide how we want to display the logging information. For example, we could have a 'last edited' column in `my stories`

### Who can help?

@helendduncan 
@callummole

**Comment by helendduncan** [comment]
Comments from chat
Proposed layout of database table:
- [ ] key UUID
- [ ] Action: Made public/edited/moderated
- [ ] user who triggered it (member)
- [ ] timestamp
- [ ] store moderation comments (ie rejected because of XYZ)
