### ISSUE TITLE
Implement demographics / profile after signup

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#453]
# Summary

*This issue is a more targeted replacement for parts of the stale issues #265 & #240.*

To better contextualize the data – both for research but also public display – it is useful to have some demographic data about users / the writers of a given experience. 

For the MVP it might be enough to ask people would fill out demographics after their initial sign-up (requires post-login differentiation between new users/returning user) and potentially a profile-page that allows people to adjust their demographics. 

In the long-term we might want to offer people to adapt those demographics on a per-experience level.

### What needs to be done?

For the MVP:

- [ ] Decide on demographic items (age bracket? gender? self-identification with respect to autism?)
- [x] Decide on technical implementation? (Maybe a User profile attached to `User` object?)
- [x] Implement back & frontend parts of this 

For the implementation we would like a new model `UserProfile` (or similar) that is a 1:1 relationship to the actual `User`, and which stores: 

- demographic data 
- binary flag for whether user has ever entered an experience to allow for first-time contributor support

### Who can help?

* Wider community for high-level design
* @helendduncan, @callummole, @gedankenstuecke for technical implementation

**Comment by gedankenstuecke** [comment]
Currently the technical implementation is on hold in favor of #421, and also needs to have a discussion on potential categories in the March community meetup (#451).

**Comment by gedankenstuecke** [comment]
I've updated the details on the implementation above, following a brainstorming with @helendduncan!

**Comment by helendduncan** [comment]
Adding to this the idea of profiles being able to set default trigger labels that they don't want to see. RE meeting 21/04/23

**Comment by llewelld** [comment]
This initial WIP implementation adds a profile page and the ability to edit/view profile info in/from the database. It still needs a bunch of work to turn it into a proper profile page: https://github.com/alan-turing-institute/AutSPACEs/pull/510

**Comment by llewelld** [comment]
For reference, the demographics were discussed during the [March meeting](https://docs.google.com/document/d/1DAir3_FMzZ5vSSVINiLHoiMv3bc2t2dMHWpG9jSIH80/edit#) and will be discussed again during the [June meeting](https://docs.google.com/document/d/1dUGx5RyqpPI7-imccKlpAi3e464FXgH_7g8SUatrg_M/edit#).

**Comment by gedankenstuecke** [comment]
Closing this as #543 is the issue to refine the demographics
