### ISSUE TITLE
Add pagination to my_stories, shared_stories pages, and search results

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#455]
### Summary
When the db contains a significant number of stories, it will be unwieldy to have them all page. Suggest use of pagination to limit the number of stories visible per page
### Deadline 
March 2023
### What needs to be done?
Update appropriate templates to allow for pagination
Decide on a sensible number of stories per page
Update views.py
### Who can help?

* 
* 

---

**Comment by gedankenstuecke** [comment]
Missing: Pagination on search/overview page
