### ISSUE TITLE
Make cassettes for testing

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#458]
### Summary

Using vcrpy we need to make several cassettes of the OpenHumans response when submitting, editing, and deleting experiences.

### Deadline 
March 2023
### What needs to be done?

- [x] List of scenarios
- [x] Cassettes made
- [x] Remove sensitive information from cassettes

### Who can help?

* @gedankenstuecke 
* @helendduncan 

---

### Updates

List of scenarios:
~-[ ] Logging into AutSPACES through OH~
- [x] Upload new experience
- [x] Edit text in existing experience
- [x] Edit sharing permissions in existing experience
- [x] List all of the OH experiences the user has written 
- [x] Deleting an experience

**Comment by gedankenstuecke** [comment]
- [ ] Logging in into AutSPACEs through OH
- [ ] Deleting an experience 

Also I think _List all users OH experiences_ is _List all experiences that a user has_, right? As I don't think we do ever query for all experiences across all users?

**Comment by helendduncan** [comment]
Yes - I was thinking of my stories which lists all of a single user's OH stories (even those not shared with AutSPACEs). So will need to check the view experiences (show all users' moderated experiences) too. Updating list

**Comment by gedankenstuecke** [comment]
Thanks! 

And the viewing of moderated experiences searching in moderated experiences should probably not result in any API calls to Open Humans, as those are using our local public experience DB, or am I missing something? :)
