### ISSUE TITLE
Write moderation copy for platform

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#460]
### Summary

We need a user-friendly, simple guide on which stories to share on AutSPACEs and how we decide what to publish. 

Working on a draft here: https://docs.google.com/document/d/106Ma7lEWZksRf58UCP8XFNjlivMQXz2yQCrcNEbxyTQ/edit?usp=sharing

**Comment by helendduncan** [comment]
Code of conduct (users) [Link Here](https://docs.google.com/document/d/1qhBlUxMVv8F_QGuY1re2xbLLZ-mNmak4TISmC-nFW58/edit#heading=h.1jjr0ujslups)

Code of conduct (moderators)

**Comment by llewelld** [comment]
This PR adds the draft Code of Conduct copy to the site: https://github.com/alan-turing-institute/AutSPACEs/pull/477

**Comment by gedankenstuecke** [comment]
Done thanks to @llewelld
