### ISSUE TITLE
Filter "View Stories" page based on trigger labels

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#462]
### Summary

This issue partially relates to the question fo pagination in #455: In its current form, the _Public Experiences_ pages does not allow for filtering for certain trigger categories (and does not display the detailed labels). To both improve navigation and allow people make informed decisions we could improve this page by allowing filtering:

### Deadline 

Mid-April, 2023;

### Suggested solution

- [ ] Implement pagination (#455)
- [ ] Change trigger-display on experience cards to include detail of which labels are present
- [x] Add filtering buttons on top of page to allow people to select which trigger categories should be included in results

For the last point:

- The filtering options/buttons should probably be "No triggering experiences", the individual trigger categories, as well as "All experiences" 
- The default should be "no triggering experiences" 
- Filtering needs to persist both for search and changes pagination pages

### Who can help?

* @helendduncan 
* @gedankenstuecke 

---

**Comment by helendduncan** [comment]
This idea was further cemented in a meeting on 21/04/23
