### ISSUE TITLE
Run a May meet-up session

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#479]
### Summary

Our next meet-up session will be the first Thursday of May which is May 4th. We should plan the session and send out invites! 

### Deadline 

Let's try to send out an agenda by Monday 1st May and include details in the April newsletter

### What needs to be done?

- [ ] Decide on date and time
- [ ] Decide who will run and facilitate session
- [ ] Write agenda and prepare google doc
- [ ] Send out invites

### Who can help?

* Please add any suggestions in the comments below

**Comment by GeorgiaHCA** [comment]
Heya @BrainonSilicon - you've run these sessions so far and they've been great! Do you have capacity for this session or do you have too much on?

@helendduncan, @llewelld, @mastoffel - would this be a reasonable date to present a version of the platform people can interact with and give feedback on?

Any other important agenda items?

**Comment by helendduncan** [comment]
Hi @GeorgiaHCA only just catching up on emails now. I'd be happy to show platform in its current state in May if needed. I am not sure of the other's allocations on projects after April

**Comment by GeorgiaHCA** [comment]
That would be brilliant - thanks @helendduncan ! Hope you're feeling better

**Comment by gedankenstuecke** [comment]
Having a hosted demo version somewhere would of course be great, but I'm not 100% sure what the pathway to that would be! I think there's two aspects to that: 

1. What would the legal/governance/data privacy pathway for that be (or could that be comparatively easy if it's only spun up for the duration of the call and all data being destroyed afterwards?)
2. Where would be spin up a hosted version for this? In the past Heroku gave free compute for such use-cases but unfortunately they've destroyed that part of their business!

@KirstieJane @GeorgiaHCA Is there maybe a precedent for this? I vaguely remember that there was a very simple prototype online at some point?

**Comment by GeorgiaHCA** [comment]
Thanks @gedankenstuecke - for a while there was a version that @badgermind kindly deployed on his own server so that it could be easily viewed. I guess we would want one with a large banner disclaimer so people know to only enter demo data? We could share it privately with a few community members first to get their sense of the design and navigation of the site? Maybe @helendduncan's suggestion of screen sharing is best for now?

**Comment by gedankenstuecke** [comment]
Yes, let's maybe stick with that for the May meet-up given that it's not too far in the future!

**Comment by gedankenstuecke** [comment]
This meetup happened, [see wiki](https://github.com/alan-turing-institute/AutSPACEs/wiki/Meetups).
