### ISSUE TITLE
Send out April newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#480]
### Summary

It's time to send out an April newsletter!

### Deadline 

Friday 28t April

### What needs to be done?

- [x] Gather updates
- [x] Contributor highlight
- [x] Draft and review
- [x] Send out
- [x] Upload to GitHub

### Who can help?

* Anyone - please suggest updates in the comments below

**Comment by GeorgiaHCA** [comment]
@mastoffel and @llewelld - we always have a "contributor spotlight" which is a straightforward interview with an AutSPACEs community member. As new members of the team, would either of you be interested in answering a few qs/sharing a pic to be featured in the newsletter?

**Comment by llewelld** [comment]
I'm happy to add myself to the queue as well.

**Comment by GeorgiaHCA** [comment]
Thanks so much @mastoffel and @llewelld ! I also had a parent of an autistic person (Lucinda) who would like to be in a contributor spotlight. How about we go for - Lucinda (April), @mastoffel (May), @llewelld (June)?

**Comment by GeorgiaHCA** [comment]
Here's the qs: 

Tell us a little about yourself…
What are your favourite hobbies/things to do?
What have you been working on for the AutSPACEs project?
Give your best tips and tricks for contributing

**Comment by GeorgiaHCA** [comment]
Hi everyone! I'm working on a draft here: https://hackmd.io/pb66RLy3RWeh8oD4kus0xQ 

Please let me know if you have any more updates you would like to have included! @gedankenstuecke @BrainonSilicon @mastoffel @helendduncan @mastoffel

**Comment by gedankenstuecke** [comment]
I've did some edits to the CSVconf & BOSC parts and left some comments on the hackmd, @GeorgiaHCA have a look over it when you get a chance (and also maybe do one more pass with a spell-checker, I tried fixing some typos but I'm sure I introduced a whole bunch of new ones 😂)

**Comment by GeorgiaHCA** [comment]
Fab thank you! I'll take another look and check it over

**Comment by GeorgiaHCA** [comment]
Hiya @gedankenstuecke I sent you a preview of the April newsletter would you be able to give it a last look it over/let me know if it's ready to send?

**Comment by gedankenstuecke** [comment]
LGTM! I would say send it out and also deposit the markdown version on GH!
