### ISSUE TITLE
Prepare for pheomenolgy of autism working group

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#481]
### Summary

We've been invited by autism professor Jonathan Green to present on AutSPACEs and citizen science for a working group on the phenomenology of autism. The audience will be researchers, members of Autistica and autistic collaborators. 

### Deadline 

The event takes place on the 25th April

### What needs to be done?

- [x] Prepare and review presentation 

Bastian Greshake and Georgia Aikenhead – The Turing Institute Platform for broad reach of experience. We have 20 minutes in the programme Jonathan sent through - may be useful to have time for discussion as well  

Working on the slides here: https://docs.google.com/presentation/d/13R0qqtmH55LsZyTjWlzO_dGQ4UVMpCV7YDEjsH8_NGM/edit?usp=sharing

**Comment by GeorgiaHCA** [comment]
I think the 6 minutes was an original plan we made but looking at the schedule we have 20 mins (2:55-3:15). Jonathan also asks if there's anyone else we think we should invite - perhaps Susanna or James and maybe also Lucinda?

**Comment by GeorgiaHCA** [comment]
Presentation is currently 22 minutes

**Comment by gedankenstuecke** [comment]
Right, I think the 20 minutes are the whole slot though, which I guess should include time for Q&A/discussion. Given the small group it would probably be best to leave at least half of the time for the discussion as there's a concrete overlap in interests!

**Comment by GeorgiaHCA** [comment]
Yep, agreed! I emailed Jonathan to double check but it would seem most useful to have discussion time

**Comment by GeorgiaHCA** [comment]
So should we aim for around 10 minutes/20 or so slides?

**Comment by gedankenstuecke** [comment]
Yes, I would aim for 10 minutes presentation including AutSPACEs as an online platform, so I would keep the introduction/context quite low and no more than 1-2 minutes and really use the screenshots of the platform to talk about some of the design issues to motivate why AutSPACEs works as it does!

**Comment by GeorgiaHCA** [comment]
Here's an updated version: https://docs.google.com/presentation/d/13R0qqtmH55LsZyTjWlzO_dGQ4UVMpCV7YDEjsH8_NGM/edit?usp=sharing

**Comment by GeorgiaHCA** [comment]
There's still a lot of slides but I think they should be fairly quick to run through!

**Comment by gedankenstuecke** [comment]
okay, looks good to me!

**Comment by gedankenstuecke** [comment]
We went to the event and gave the talk! 🎉
