### ISSUE TITLE
Deliver poster presentation for C*Sci 2023

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#482]
### Summary

The C*Sci 2023 conference is taking place in Arizona. Georgia will be delivering a poster presentation and attending the conference to disseminate AutSPACEs to a wider community. 

### Deadline 

May 1: 	Registered presenters granted access to event platform to draft poster content 
May 3: 	Poster Office Hours for support with posters
May 11: 	Poster Peer Reviews

### What needs to be done?

- [x]  Complete registration
- [x] Book travel and accommodation
- [x] Prepare poster
- [ ] Deliver poster

### Who can help?

* Suggestions for the poster format and content would be appreciated!  
* Anyone able to help review would also be awesome!

**Comment by gedankenstuecke** [comment]
For the format I'd check out if C*Sci has guidelines on sizes, orientation etc. Content-wise it's typically best to err on the side of having less text that one might think one would need!

**Comment by GeorgiaHCA** [comment]
There's a guide here which is useful: https://docs.google.com/document/d/1t8CnsBQlyXe81jarfBE9_Y0xDVJLG9a-evvAkP8rxas/edit?usp=sharing

**Comment by GeorgiaHCA** [comment]
Hiya! Here's where I'm working on the poster: https://docs.google.com/presentation/d/1YiHFNzCA1TTBdswnCixtgcdvDpfOOeHU/edit?usp=sharing&ouid=118051576780162781860&rtpof=true&sd=true . Would be amazing to have your feedback @gedankenstuecke I'm using the poster guide "butterposter" template recommended by the organisers. There's a peer review session on **Thursday 11th** for posters

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA I'll close this as I guess there's little to do beyond showing up at C*Sci next week!
