### ISSUE TITLE
Submit conference abstract for BOSC 2023

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#483]
### Summary

The [2023 Bioinformatics Open Source Conference](https://www.open-bio.org/events/bosc-2023/bosc-2023-keynotes/) wants to organize a panel on _Open & Ethical Data Sharing_ and has asked @gedankenstuecke if he'd be willing to participate in it. If he were to go it would also be a good use of the travel to give a talk on AutSPACEs at the conference. 

The submission deadline is on the 20th of April, so techncially there's enough time left! 

### Deadline 

April 20

### What needs to be done?

- [x] Write abstract 
- [x] Submit abstract 

### Who can help?

* Mostly on @gedankenstuecke given the late notice

---

**Comment by gedankenstuecke** [comment]
I've [pulled together a quick abstract](https://docs.google.com/document/d/1sWGgykeK1HhRgvzvAiK_GNj0fOAFAb58cuZKdrDc_0w/edit), if anyone would have time to do a quick pass over it for both language and content that would be great (but no worries if it's too last minute!)

**Comment by GeorgiaHCA** [comment]
Amazing, sounds like a great opportunity. I'll take a look today!

**Comment by GeorgiaHCA** [comment]
I've made a few small recommendations for grammar and flow - but this looks excellent overall! Captures the essence of AutSPACEs really well!

**Comment by gedankenstuecke** [comment]
Great, thanks so much!

**Comment by gedankenstuecke** [comment]
Also, so far I've listed the following as authors: @gedankenstuecke @GeorgiaHCA @helendduncan @callummole @mastoffel @llewelld @badgermind, Susanna Fantoni, James Scott, @KirstieJane, and "the AutSPACEs community" as a catch-all. Given that I quite quickly threw the list together, did I accidentally forget anyone? :)

**Comment by GeorgiaHCA** [comment]
Looks good to me! AutSPACEs community is a good overall inclusion. I'd also suggest including Otis Smith as he helped with the key for the community recommendations

**Comment by gedankenstuecke** [comment]
Great news everyone, AutSPACEs was accepted for a short lightning talk! ⚡

**Comment by GeorgiaHCA** [comment]
[celebrate]     Georgia Aitkenhead reacted to your message:
________________________________

**Comment by gedankenstuecke** [comment]
[Slides are now on Zenodo](https://zenodo.org/record/8164376) 🎉
