### ISSUE TITLE
Hide triggering stories by default

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#488]
### Summary

The default view of the (moderated, approved) experiences should be only non-triggering stories

~~No preview text for stories that contain content warnings~~

Users opt into viewing potentially triggering content. On a per-label basis (i.e only allow "abuse" trigger tag)
### Deadline 

May 2023

### What needs to be done?

- [x] Switch default behaviour in view stories
- [x] Investigate toggles/dropdowns/checkboxes
- [ ] Have options for user testing

### Who can help?

* @helendduncan 

---

### Updates

4th May 2023 - after meet up ([Google doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.caqz9vddyyxh)):
Current implementation (checkboxes under search bar) is potentially confusing as you have to "search" to view triggering stories.
HD's other idea of a dropdown with multiple options seems to fall under the same sub-optimal implementation (searching). 
Suggested alternatives: toggles (dynamically update page)
#### Some selected relevant comments from 4th May meet up:
* Can it default to everything is clicked, and you can unclick what isn’t okay?
* May result in some people being triggered because they didn’t recognise the opt-out buttons
* Neither checkboxes nor drop-down may be what we want? Perhaps we need a toggle? - dynamically reload - this is an expected behaviour
* https://www.bootstraptoggle.com This is a random “bootstrap plugin” for the frontend that would provide such toggle-switches
* Be more explicit and declared - we have excluded triggering content/now you are opting in for triggering content
* Guidance for seeing people through: “We have excluded potentially triggering content, if you would like to see more content please choose which categories you would like to see”
* Add a text box about what is shown, and what happens when you select the triggers 
* Toggles vs. check boxes - when does the search refresh? Toggle could have a yes or no side on it to make it clear which selection opts in. Check boxes are a more ubiquitous UI 
* Consistency is the most important part so we need to be fully team check box or fully team toggle
* Worth user testing? Could be different for autistic users because more sensitivity to regularity and different

**Comment by gedankenstuecke** [comment]
Closed by #492
