### ISSUE TITLE
Check the default font size is large enough

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#490]
### Summary

Ensure the font size is large enough

### What needs to be done?

- [x] Check if there is a style sheet
- [ ] Identify good "minimum" size
- [ ] Update it

### Who can help?

* 
* 

---

**Comment by helendduncan** [comment]
Tagging @BrainonSilicon in this to ask what the ideal font size should be

**Comment by gedankenstuecke** [comment]
thanks! 🙏

**Comment by llewelld** [comment]
Some background about the current font size and how it's set.

The current value is set to `1em` which is both the browser default, and the Bootstrap defult. Here's the relevant code from [the imported](https://github.com/alan-turing-institute/AutSPACEs/blob/d82f22a83c0b63dc977de78dc4ad78901d7cf281/server/apps/main/templates/main/partials/jquery.html#L3C56-L3C56) `bootstrap.min.css`:
```
body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto 
Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";font-size:1rem;
font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff}
```
In amongst all that you can sees `font-size:1rem;`.

Bootstrap 4.3 CSS is [generated using SASS](https://getbootstrap.com/docs/4.3/getting-started/theming/#sass), so this value is controllable as long as we don't mind generating the css file again from the Bootstrap scss files. The releveant definitions can be found in Bootstrap's [`_variables.scss` file](https://github.com/twbs/bootstrap/blob/fa4fbc8798e432b37d6734e66c08da3985a75c89/scss/_variables.scss#L283C65-L283C65). For context, we don't currently using these scss files directly, they all get boiled down to create the `boostrap.min.css` which we're pulling in directly from the Bootstrap servers.

What does `1em` actually mean in practice? An `em` is a proportional length [relative to the font size of the element](https://www.w3.org/TR/css-values-4/#relative-lengths). So `1em` is literally just the default font size as configured in the browser. For desktop [Firefox](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#) and [Chrome](https://support.google.com/chrome/answer/96810?hl=en&co=GENIE.Platform%3DDesktop) this will be 16pt unless the user has changed it. In practice this is a bit arbitrary &mdash; it'll depend on monitor size, dpi settings, etc. &mdash; but we could certainly adjust it to be proportionally larger or smaller than the user's setting if needed.

**Comment by llewelld** [comment]
Maybe one other point to note is that Bootstrap apparently supports ["Responsive font sizes"](https://getbootstrap.com/docs/4.3/content/typography/#responsive-font-sizes) for "allowing text to scale more naturally across device and viewport sizes". This is disbled by default, but we could potentially consider enabling it.

**Comment by llewelld** [comment]
The [Web Content Accessibility Guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/) don't seem to specify any minimum font or text size. They do have requirements around [text spacing](https://www.w3.org/TR/WCAG21/#text-spacing) and [text resizing](https://www.w3.org/TR/WCAG21/#resize-text) which may be relevant. The focus seems to be on allowing the user to control the text size, rather than choosing a particular default size.

**Comment by llewelld** [comment]
From what I can tell the gov.uk checklist also focuses on [checking content is usable when zoomed in or magnified](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/accessibility/gov-checklist.md#summary-6) rather than specifying sensible default font sizes.

**Comment by helendduncan** [comment]
I think @BrainonSilicon might be worth checking with if there is some guidance from her networks?
