### ISSUE TITLE
Forms: increase the character limit

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#491]
### Summary

Currently there is a 500 character limit in forms.py for the experience and difference text and a 150 character limit for the title text. This is not long enough for the current placeholder stories that we are using.

Note there is no limit in the models, just the form

Need to decide if to place a limit on the number of characters and if so what it should be.

### Deadline 

May 2023

### What needs to be done?

- [X] Decide new character limit - "Very large" - HD suggests 10,000 characters
- [ ] Implement change (have done it locally and works)

### Who can help?

* @gedankenstuecke 
* @GeorgiaHCA 

---

### Updates

4th May 2023:
Cut and paste from [Google doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.caqz9vddyyxh) from today's monthly meet up
We’ll begin by implementing no or a very large word [character] count for the MVP, and do user testing and iterate if people send in unworkable large experiences.
Titles should be consistent and readable and fitted to user screen size - this is the most important part to get right- we should also impose a length and cut off rest from story - but don’t cut off title.

HD: In practice I think setting a 10,000 character limit for the experience and the same for the recommendation would be a sensible for the first iteration. This approximately corresponds to three sides of A4 with 12 point font (and some line/paragraph breaks)
It has been suggested by @gedankenstuecke that once we have users interacting with the platform we can analyse story lengths and modify any limits based on that.

HD: Currently there is a 150 character limit for the title text. RE: limiting length will either remove cap or set it to be 10,000 characters. RE: viewing. Currently the title remains fully visible for rescaling of the page in my test environment (using Chrome) may want to think of a systematic way to monitor these visual requirements?

#### Some selected relevant comments from 4th May meet up:
* Feedback from a community member: it can be distressing to have a limit and count down. Response: Count up would be better than count down
* From a psychological perspective it might put people off if there is a cap - some autistic people may like to submit a large amount of text - this is part off accessibility to include autistic people’s preferred mode of expression
* You shouldn’t allow more than a moderator could reasonably moderate
* Is there a number of characters after which the software breaks?
* Could you chunk up the text for the moderators, while giving the users a more seamless experience
* MVP should be particularly focussed on being sensitive to user needs so people aren’t put off on the initial stages
* We shouldn’t try to over-engineer it without finding out what happens - let’s focus on a simple solution for the MVP - plan A = no or very large word count; but worth having

**Comment by gedankenstuecke** [comment]
I would err on the side of being quite liberal with the character limits, maybe more so in the actual experience than in the title. 

But that's purely a gut feeling, maybe we can ask in the May meeting what people think. I guess there's a trade-off between "enforcing" brevity and people getting frustrated with not having enough space and maybe collectively we can explore where to make that cut-off :)

**Comment by helendduncan** [comment]
Cut and paste from google doc from monthly meet up (4th May 2023)

We’ll begin by implementing no or a very large word [character] count for the MVP, and do user testing and iterate if people send in unworkable large experiences.
Titles should be consistent and readable and fitted to user screen size - this is the most important part to get right-  we should also impose a length and cut off rest from story - but don’t cut off title.

**Comment by gedankenstuecke** [comment]
Closed by #512
