### ISSUE TITLE
[Conference] Systems & Design

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#496]
### Summary

During the AIM RSF conference @BrainonSilicon and I met a PPIE Lead that is [co-organizing a local hub for the  _Relating Systems Thinking and Design_ (RSD) conference on Octobre 13/14 in Loughborough](https://rsdsymposium.org/rsd12-loughborough-gbr/). 

The motto of the conference is _systems science, design science, citizen science, and data science_ and AutSPACEs could be a fit for that from a variety of angles and the co-organizer was quite interested in our experiences. 

I'm curious, what are people's feelings on this? Shall we think about submitting? 

### Deadline 

May 31, 2023

### What needs to be done?

- [ ] Think about potential topics 
- [ ] If yes: write & submit

### Who can help?

* Most immediately probably @BrainonSilicon and @GeorgiaHCA, 
* but also anyone else who thinks the topic is interesting!

---

**Comment by GeorgiaHCA** [comment]
Citizen science in engaging communities in research and decision-making seems perfect! Maybe one of the community members would like to share experiences of co-design? We could discuss it in the meet-up tomorrow

**Comment by GeorgiaHCA** [comment]
My thinking is we could present a participatory workflow for developing an aspect of the platform (e.g. moderation design) and include people who were involved at different stages.

**Comment by gedankenstuecke** [comment]
I think given the timeline and formats they support it's unrealistic to make a successful abstract for this (i.e. a full paper). But I think there might be a pathway to propose a talk directly to the local hub instead, which could just be a lightning talk, which we can figure out post-submission deadline.
