### ISSUE TITLE
Specify behaviour when form is not valid - views `share_experience.py`

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#497]
### Summary

There is no "else" to the if form.is_valid() in `share_experience` function in `views.py`
This means invalid forms (eg character length too long see #491) you will get a None Http response and an error

### Deadline 

May 2023

### What needs to be done?

Decide on sensible action for invalid form (back to the edit page perhaps?) and implement it

### Who can help?

* @helendduncan 
* 

---

**Comment by gedankenstuecke** [comment]
Great catch! I would say returning the user to the edit/enter page would be the best. I think by re-using the invalid `form` this should also include the error message we can display on the frontend side alongside the existing data!

**Comment by gedankenstuecke** [comment]
Closed by #512
