### ISSUE TITLE
View a single story on a single page

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#498]
### Summary
Following a comment at the May meet up (Google doc [here](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.caqz9vddyyxh)):
Would it be possible, when you click “read the story”, will it remain on the page or go onto another page - if there’s one immediately after, it may be too much, and having it separate would be easier to share.

> Another page might make it easy to copy and paste content and share a link with others/bookmark a story that you want to come back to

> Can the default be the infinite scroll on the expanded story be an option to “open in a new page” 

> Adding a button of “open in a new page”

> “Continue reading?” button/option after a certain cut off so that you are not bound on continuing 

> Having all on one page might clutter the experiences page 

> Reactive to screen width - we can alter text display based on size of screen 

> There is a minimum recommended font size - make sure it doesn’t drop below that font size.
(see issue #490)

### Deadline 
June 2023
### What needs to be done?
- [ ] Make template for single story page
- [ ] Add "read as standalone" button to accordion (? once opened or when closed ?)
- [ ] Add a views function to send contents of story with given uuid to the template

### Who can help?

* 
* 

---

**Comment by gedankenstuecke** [comment]
>  Add "read as standalone" button to accordion (? once opened or when closed ?)

I would say after the accordion is opened. I think the following format could work well for the opened accordion

> **EXPERIENCE TITLE**
> *First X characters of experience/recommendation as discussed to fit into screen size comfortably*
> **<button: open full experience>**
