### ISSUE TITLE
Send May newsletter

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#506]
### Summary

With the next community meet-up happening soon, we want to send out a newsletter in advance to make sure folks know about it. We should have some general updates as well as a contributor spotlight. 

### Deadline 

May 26 

### What needs to be done?

- [ ] Pick topics
- [ ] Draft newsletter
- [ ] Put into tinyletter & test
- [ ] Send out the week before the meetup

### Who can help?

* @GeorgiaHCA 
* @mastoffel 

---

### Potential topics to cover

- Georgia at C*Sci conference, link to poster
- Contributor spotlight: Last month we suggested @mastoffel, if he's still up for it!
- Next community meet-up, June 1st

**Comment by gedankenstuecke** [comment]
A draft of the newsletter is here: https://hackmd.io/t2x2cmjESAq3iBnhWPwfdw 

@mastoffel Are you still up to answer that little interview? I put your name in for now, but if the timing doesn't fit  (early next week would be great!) then we could gently ask @llewelld instead 😉

**Comment by mastoffel** [comment]
Cool! Done :)

**Comment by gedankenstuecke** [comment]
Perfect, thanks so much! I'll send it out later today!

**Comment by gedankenstuecke** [comment]
And sent, Newsletter is archived here: https://github.com/alan-turing-institute/AutSPACEs/blob/main/00-project-documentation/communication/newsletters/newsletter-2023-05.md
