### ISSUE TITLE
Check form fields are marked up appropriately

### ISSUE THREAD

**Issue by Angelsaur** [alan-turing-institute/AutSPACEs#51]
### Summary

You need to make sure any form fields are marked up correctly. If they’re not marked up properly, screen readers will not be able to tell what a form field is for, or what information the user should enter into it.

### Deadline 

20/02/2021

### What needs to be done?

You can check your form fields are marked up properly by going to a form and clicking on a field label (the text above, below or next to the field that explains what it’s for). If the field is marked up correctly, clicking the field label should cause your cursor to appear inside the corresponding field.

Do this test on a few of your forms to check whether the fields respond as they should

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
