### ISSUE TITLE
Send June newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#514]
### Summary

With the next community meet-up happening soon, we want to send out a newsletter in advance to make sure folks know about it. We should have some general updates as well as a contributor spotlight. 

### Deadline 

June 30th 

### What needs to be done?

- [x] Pick topics
- [x] Draft newsletter
- [x] Put into tinyletter & test
- [x] Send out the week before the meetup

### Who can help?

* @GeorgiaHCA 
* @llewelld 
* Any suggestions for topics please add in comments 

---

### Potential topics to cover

- Georgia at C*Sci conference, link to poster
- Contributor spotlight: @llewelld ?
- Next community meet-up, July 6th

### Updates

Drafting Newsletter here: 
https://hackmd.io/pb66RLy3RWeh8oD4kus0xQ

**Comment by gedankenstuecke** [comment]
I know you're still busy, but @llewelld @helendduncan @mastoffel Do you think a fun little paragraph on your hack week could fit the newsletter? 🙁

**Comment by gedankenstuecke** [comment]
See below for a draft of the bit on the hackweek. Thanks to @helendduncan for that!

### Hack week at the Turing
Helen, Martin & David – our amazing members of the Turing's Research Engineering (REG) Group – took part in their second annual _Hack Week_. Hack week is a time when the whole REG group collaborates, and hones their skills in data science and programming. This year the projects ranged from making a REG chatbot, managing project allocations, to teaching a virtual T-Rex to walk via reinforcement learning or picking the best Pokemon team using genetic algorithms. If you want to learn more about the fun projects the teams worked on, you can [find details (and videos!) in this twitter thread](https://twitter.com/turinghut23/status/1669692047203225601?s=20).

**Comment by GeorgiaHCA** [comment]
Newsletter has been sent and uploaded to GitHub. Thanks so much for your wonderful spotlight contribution @llewelld
