### ISSUE TITLE
July Meet-Up

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#515]
### Summary

We need to plan for the July meet-up

### Deadline 

Session will be on July 6th

### What needs to be done?

- [x] Decide on agenda
- [x] Create Google Doc
- [x] Send out Invites

### Who can help?

* Any suggestions please add to the comments 
---

### Updates

I made a [Google Doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit?usp=sharing) with a suggested agenda and icebreaker

**Comment by gedankenstuecke** [comment]
@llewelld @helendduncan @mastoffel Will there be any agenda topics from your end that we didn't get to during the last meetup? I think we didn't manage to get to the user profile/demographics PR work by @llewelld, but was there anything else? 🙂

**Comment by helendduncan** [comment]
I think there may have been something from @mastoffel too?

**Comment by GeorgiaHCA** [comment]
Plan out user tests with the community

**Comment by gedankenstuecke** [comment]
I'm not 100% sure if we should discuss the user testing in that setting. I'm worried that we'll have a large overlap between participants in the community meet-up and potential usability testing participants. 

If we co-design the usability studies with the people that take participate in the usability-tests we have a very biased sample – that is unless we exclude the people that co-designed from becoming study participants. Are we okay with those limitations?

I lean towards yes, mainly as the meet-up participants in a sense are already heavily biased given that they have seen the development and different prototypes through screenshare in any case.

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA could you also check that the dates etc. are updated throughout the agenda (currently still uses May as date) and then add the link to the doc here: https://github.com/alan-turing-institute/AutSPACEs/wiki/Meetups ? 🙂

**Comment by GeorgiaHCA** [comment]
Yep, all done - also I changed the link text for last month's session from July to June as it had the wrong month :)

**Comment by gedankenstuecke** [comment]
Great, thanks! Then let's send out a reminder next week and otherwise I think we're done with this 🙂

**Comment by GeorgiaHCA** [comment]
Fab meet-up everyone!
