### ISSUE TITLE
Write an abstract for moderation paper

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#516]
### Summary

The moderation paper needs an abstract <250 words

### Deadline 

Friday 16th June to share with James S and Bastian 
Draft is here: https://docs.google.com/document/d/1hN7ct8WYVUe1z2LhNy5e_sP5MYWJ8iUiyeJXR5OwbyA/edit?usp=sharing

**Comment by gedankenstuecke** [comment]
Closing as done :)
