### ISSUE TITLE
Plan out user testing session and engagement plan 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#517]
### Summary

Now we are close to having an MVP deployed, we  should start strategising user testing. 

### What needs to be done?

- [ ]  Plan out some user testing and engagement options for testing the platform
- [ ] Questions to think about: Which features do we want to test/with which priority? Which demographics do we want to test with (gender, age, autistic adult/caretaker, new to project or existing community member, researchers? …)
- [ ] Try to find time with Kirstie to agree on those aspects of what/how to test

### Who can help?

Please add any suggestions in the comments 
---

### Updates

I've made a Google Doc to start us off here: https://docs.google.com/document/d/1P6Lw-2vl0CamEYH3G1wbHRQxWX4M4HmHXUd4cp3CSrM/edit?usp=sharing

**Comment by GeorgiaHCA** [comment]
I think it would be good to define how many user testing sessions we want to run? I think if we did around 6-8 we could get a reasonable sample for making iterations?

**Comment by gedankenstuecke** [comment]
I guess the number of testing sessions probably also heavily depends on what exactly we want to test. For her PhD @katoss did testing in two batches to evaluate the impact of the changes made between the edits. 

Maybe it's worth to check if there's TPS folks that have also done user testing in the past for doing a brainstorming with them? 🙂

**Comment by dingaaling** [comment]
A few thoughts from my end (informed by testing a data platform with local government users):
- can be helpful to record the screen (if conducted by video) to compare what a user "does" vs. what they "say" regarding the platform
- can be nice to have a combo of 1) structured interview questions for direct comparison between users 2) open explore time where the user uses the platform freely to surface things that might not have come up in questions
- if you are inviting the same users back for multiple rounds of interview it can be nice to compare their answers and platform usage as the transition from being unfamiliar with to more familiar with the platform and how that changes their actions

But of course the utility ^ of any of this feedback depends largely on what you're hoping to test!

**Comment by Arielle-Bennett** [comment]
Another point to consider is asking people to talk their thoughts aloud if they can during user testing - when we did this for testing a website at an old job we got some really interesting and surprising feedback.

I know that this level of ad hoc verbalising may not always be feasible or appropriate with the users you want to test with so it might be worth considering whether there are other ways to get this type of feedback (c.f. Jen's point about screen recording above).

**Comment by gedankenstuecke** [comment]
Thanks @dingaaling & @Arielle-Bennett, some great points there! 

Recording the screen along with the audio for the think-aloud aspect will definitely something we'll plan for in the 1:1 meetings for usability testing. Along with a combination of planned tasks "can you do X" as well as a more free-form exploration of the platform! (btw. any recommendations on whether to do the planned tasks or the free exploration first?)

**Comment by KirstieJane** [comment]
These comments are great so far!!

One question I don't really know the answer to (but that I'd like to make sure we have developed an answer for) is how to do user testing on a platform we know isn't finished / done / perfected!

On the one hand we could end up wasting time on user testing where our community tell us what we already know. On the other we could go way too far down our own path and not ask and therefore miss major opportunities.

I think probably the structured tasks mitigate the worries about just hearing what we're already know. And that it is worse to not ask than to ask and hear what we know.

I hope that makes sense!

**Comment by KirstieJane** [comment]
@gedankenstuecke - I think that's right. If we thought we were done I think free exploration first is great. But maybe in our scenario then structured first, while capturing anything else that the users say as broad feedback too.

**Comment by gedankenstuecke** [comment]
I'll double-check with @katoss how she did it for her PhD work, I know the testing she did for her Wiki also included a free exploration and tasks!

**Comment by KirstieJane** [comment]
Are we going to transcribe? Transcriptions are a lot a lot of effort and I wonder if it would be more efficient to capture an assessment of the recording? We need that anyway, it's just whether we also need the transcriptions.

We need a list of headings in that assessment. I'm not sure what they would be but happy to brainstorm if I can be helpful!

Something like:
* things that went well
* things that were confusing
* things that broke 
* suggestions

etc...

**Comment by gedankenstuecke** [comment]
According to our ethics we will transcribe ;-) 

I think there's multiple aspects to that: 

- I do think we want some "partial" transcription to have some actual quotes of participants on what their feedback was. 
- But: We don't want/need a full transcript of the whole sessions and can take notes during the session with both rough timestamps of when things went well/bad and notes of according to those categories!

**Comment by aldenc** [comment]
For the structured interview part, I would suggest that you really take some time to write the correct questions - examine each question and think about how it's worded, what kind of response that will elicit, and if that response actually will help you understand pain points and what changes you need to make. Often questions that make a lot of sense intuitively might not actually yield actionable data. 

One trick that I like to use is asking people to rank things against each other - if you ask them about the importance of some attribute or feature on its own, you might find that everything is really important. But if you make them rank things against each other, you'll learn that people care more about x compared to y and you can prioritise accordingly.

**Comment by gedankenstuecke** [comment]
Thanks @aldenc, great points as well! I'm not sure we'll have a set of features to rank but if we get there that will be super helpful!

**Comment by gedankenstuecke** [comment]
Closed as superseeded by #545!
