### ISSUE TITLE
Check moderation reply implementation for potential XSS vulnerabilities

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#524]
### Summary

The moderation reply implementation stores structured json data in a database text field. This has the potential to be vulnerable to cross-site scripting (XSS)/injection attacks, since an attacker could send malformed JSON, potentially with HTML/Javascript subelements, which may not be detected.

It may be fine, but this is probably something we should carefully double (triple) check.

### What needs to be done?

- [ ] Check whether there is any potential for injection attacks.
- [ ] If there are, fix them.

### Who can help?

* Anyone who wants to contribute to the AutSPACEs codebase.

---

**Comment by gedankenstuecke** [comment]
Good thinking @llewelld! I'll keep that in mind when looking at #494!

**Comment by gedankenstuecke** [comment]
@mastoffel I just wanted to check in whether that assignment is now outdated? Of course we'd be super excited to have you contribute this in a less-formal open source contributor manner, but I wanna be mindful that you might not have the time for that 😉

**Comment by gedankenstuecke** [comment]
Thanks @mastoffel! Great point on the templating engine, the page also covers the second half of the issue, which is about SQL injections as we try to parse JSON that is submitted through the user-form. 

Also given that it's _only_ moderators that are able to write JSON to the DB and the existing injection protection is in place, I guess the risk is quite low? We explicitly trust moderators to act responsibly for AutSPACEs as a whole. 

One approach to expand on this a bit would be to parse the JSON file and double check that only the keys we allow are in there and nothing else.

@llewelld What do you think on this?

**Comment by llewelld** [comment]
Thanks both for looking in to this; given what you've both explained, and the docs @mastoffel flagged, you've convinced me that this is okay. I'm actually a little surprised the escaping doesn't mess up the client-side json parsing, but `JSON.parse()` is happily consuming everything as intended.

Just for info, there's currently no checking of valid JSON as data goes into the database, but when it's pulled out again the validity is checked before passing it back to the client. We could strip out irrelevant JSON tags as you suggest @gedankenstuecke, but security-wise I don't personally think it's necessary: as it stands unknown keys will be stored in the database but otherwise ignored. I'd be happy to make the change anyway?

Finallly, just to double check that django's escaping isn't messed up by the JSON parse step or anything like that, I manually injected some non-escaped HTML into the database. The result was positive: everything gets appropriate escaped and rendered verbatim (see screenshot below).

Happy for this to be closed, or I can refine the JSON check to strip unused tags?

![XSS-test](https://github.com/alan-turing-institute/AutSPACEs/assets/1446122/a5b696bd-e9eb-4eb9-b17f-507c6db713cc)

**Comment by gedankenstuecke** [comment]
I think you're right that stripping those unused keys isn't really necessary. So I'd be happy to close this issue as well 👍
