### ISSUE TITLE
Remind the user to fill out their profile

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#534]
### Summary

Figure out a sensible flow in case the user never fills out their profile.

There may be multiple reasons why a user unintentionally doesn't fill out profile information:
1. In case the functionality that redirects the user to the Profile page on first entry fails, the user may be unaware that they have to.
2. The user may want to get straight to the content, skip profile creation, and later forget about it.

We should decide on an appropriate flow to try to avoid this situation arising. For example, if the `UserProfile` is found not to exist, or if the user has never submitted a profile, it might make sense to redirect them to the profile page at various points. The points at which it makes sense to do this will need to be decided (e.g. after a period of time; when the user next logs in; when the user performs specific actions; etc.)

### What needs to be done?

- [ ] Decide on when appropriate triggers for reminding the user.
- [ ] Implement them.

### Who can help?

* Wider community for high-level design
* Developers for technical implementation.

---

**Comment by gedankenstuecke** [comment]
One place where a reminder would be appropriate: After sharing an experience that is marked as "for research" or "public". If a user has not entered the minimum demographics (whether they are autistic or not), then their experience will not be usable for research and probably also not super useful for readers. It would make sense to send a reminder when that happens (that optionally could be marked as "never remind me again"?)

**Comment by gedankenstuecke** [comment]
Closing as done with the flexible success pages
