### ISSUE TITLE
Support users to submit their first experience

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#535]
### Summary

There is evidence from previous focus groups that the research question is quite broad and it may be unclear or ambiguous to new users what to enter and how to enter it. It would be helpful to have a walkthrough, tutorial or other method to support people to enter stories - create an AutSPACEs onboarding process. 

### What needs to be done?

- [ ] Look at existing citizen science projects and how they onboard people
- [ ] Research into what is possible
- [x] Create a diagram or diagrams to support onboarding

### Who can help?
 
* Please  add any suggestions or feedback in the comments below. 

---

**Comment by gedankenstuecke** [comment]
Here's a few JS walkthrough libraries: 

- [IntroJS](https://introjs.com/)
- [ShepherdJS](https://shepherdjs.dev/)
- [TourGuide](https://tourguidejs.com/)

Having said that, I don't have 1st-hand experience with either of them!

**Comment by GeorgiaHCA** [comment]
I've made a basic flow chart diagram using [draw.io](https://drive.google.com/file/d/16nX5IvyiaQ9DgzJlnE3mfnxHmWxLsk2o/view?usp=drive_link) - would it be helpful to include screenshots?

**Comment by gedankenstuecke** [comment]
Do you mean including screenshots of the flowcharts here? Or including screenshots in the flowcharts? 

Oh, and the draw.io link requires permission to view!

**Comment by GeorgiaHCA** [comment]
I was meaning that it could be helpful to users to have screenshots of the platform alongside the steps in the flowchart, maybe with arrows or elements highlighted? Here's another link to the flowchart: https://drive.google.com/file/d/1J3zaYyY01WCvc0On6Q2LxAB7xvq2o4UU/view?usp=sharing

**Comment by gedankenstuecke** [comment]
thanks, the link now works! I wouldn't add screenshots into the flowchart, as I think the point would be to have a quicker overview of the process and adding screenshots could expand on that too much?

**Comment by GeorgiaHCA** [comment]
Hi @llewelld  - I think a couple of sentences would be enough for now in the Help section. Maybe something like: 

To share an experience on AutSPACEs, please go to the share experience page when you are logged in and write about any time you have been effected by your senses in the text box. Then you can submit your experience for research or to share publicly on our website. The flow chart below shows the steps you can take to share an experience on AutSPACEs. 

How does that sound @llewelld, @gedankenstuecke ?

**Comment by gedankenstuecke** [comment]
Yes, that sounds good! Can also link the 'share experience' page from the text :)

**Comment by llewelld** [comment]
Thanks for the text and suggestion; that's great! This PR shows what it looks like with this added in: https://github.com/alan-turing-institute/AutSPACEs/pull/561

**Comment by llewelld** [comment]
> Here's a few JS walkthrough libraries:
> 
>  * [IntroJS](https://introjs.com/)
>  * [ShepherdJS](https://shepherdjs.dev/)
>  * [TourGuide](https://tourguidejs.com/)

Examples of usage for Shepherd.js and TourGuide can be found in #564 and #575 respectively.

I had a quick look at IntroJS but this has a [GNU AGPLv3 licence](https://introjs.com/docs/getting-started/license) which will conflict with our [MIT licence](https://github.com/alan-turing-institute/AutSPACEs/blob/main/LICENSE), so I didn't look into that further.

**Comment by gedankenstuecke** [comment]
Based on the feedback of the September 2023 user testing, it seems like this might be a feature some people would use, but generally not too many people wanted/seemed to need a tour as improvements could be made through clearer signposting of existing pages. Should we shelve this for now?

**Comment by gedankenstuecke** [comment]
Given the updates to usability so far I will close this as stale/outdated or now. 

If the second round of user testing uncovers that this remains an open need we can pick up the two PRs that @llewelld made and that are still open as drafts
