### ISSUE TITLE
[FEATURE]: Add moderation status to profile page

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#537]
### Feature for…

Frontend

### What is the problem you want to solve?

As a user I'd like to know my moderation status, so that I can understand what capabilities I have access to on the site.

### How do you want to solve the problem?

1. I propose to solve the problem by adding a read-only field to the profile which indicates whether the the user has moderator rights or not (in case the use doesn't the field can be hidden).
2. Alternatives include:
   1. Not adding anything: it's already obliquely clear from the existence of the 'Moderator' menu item that the user is a moderator.
   2. Adding a section for 'badges'. It could be quite cool to have badges for things like 'author' (after posting a story), 'moderator', 'profile complete'. But these could also be seen as manipulative.
   3. Adding an enrolment process for moderators. This could be useful in other ways, and maybe makes highlighting moderator status more redundant.
3. I propose simply adding a field to the profile, as it's a relatively straightforward change that can be iterated on later.

**Comment by llewelld** [comment]
Would it make sense therefore to close this issue, given there are higher priority tasks, and at any rate it might make more sense to wait until/if it fits into something broader (e.g. badges for other reasons)?

**Comment by gedankenstuecke** [comment]
Yeah, let's do that! 👍
