### ISSUE TITLE
Where to find support page

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#541]
### Summary

Following the July 2023 meet up ([Google doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.7f28vh3w1oai)): list organisations that may be able to help individuals

### Deadline 
October 2023

### What needs to be done?
- [ ] Decide on appropriate list of organisations
- [ ] Decide where to place this information
- [ ] If on separate page, add page with content. If not update existing page

### Who can help?

Anyone who is interested
---

**Comment by helendduncan** [comment]
Question: As this will link to external resources, should this page have a "last updated on"?

**Comment by gedankenstuecke** [comment]
I might not have fully understood that part, what types of organisations would we have in mind for this broadly speaking etc/ what would the goal be? 

Just wondering how much of this is already covered in our current footer (which only has names so far iirc but no links)

**Comment by helendduncan** [comment]
Parked until user experience highlights what could be needed.

Suggested that it could go on the help page if implemented
