### ISSUE TITLE
Update `PublicExperience` to include an "author" category

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#544]
### Summary
When sharing an experience it will be necessary to know if the story about a user's experience or are they sharing it on behalf of someone else
### Deadline 
August 2023

### What needs to be done?
- [x] Decide on categories to be chosen from
- [x] Add this to the form and model
- [x] Update the share experience page
- [x] Update the view experiences page from the placeholder "AutSPACEs Contributor"

### Who can help?

Anyone interested

---

**Comment by gedankenstuecke** [comment]
To get our brainstorming started on this: I'd say the MVP of this would be to have people 

1. check a box on "Story reports on behalf of someone else" when submitting a story 
2. also ask for a brief description of "for whom and why is this a second-hand report?" (wording not suggested to be final 😉) when checking that box

**Comment by GeorgiaHCA** [comment]
This links to [Issue 543](https://github.com/alan-turing-institute/AutSPACEs/issues/543) around user profiles - in particular the additional questions: During the meeting we discussed whether to have a question on "(additional) relationship to autism", e.g. being a parent/carer/friend/co-worker etc. of someone with autism? I think generally it would be good to have this, maybe could fit in between Items 1 & 2?

**Comment by GeorgiaHCA** [comment]
One option would be to include some examples of what we mean by "(additional) relationship to autism" - e.g. "I am the non-autistic parent of an autistic adult", "I am the autistic parent of autistic children", "I am a teacher who works with autistic people", "I am best friends of an autistic person".

**Comment by GeorgiaHCA** [comment]
It could also be helpful to have moderators attach labels to stories which are more binary than the free text on the basis of the self-descriptions - e.g. assign, "autistic", "non-autistic", or "unsure" to the author and "self-report", "report for another", or "unsure" to the experiences

**Comment by GeorgiaHCA** [comment]
Probably the simplest thing is to allow people to write their own authorship descriptions and allow moderators to moderate that on the same basis as the content of the experiences

**Comment by gedankenstuecke** [comment]
Just to flag one thing re: the overlap with user profiles: The user profiles could be used to set a default for that user, but i think we want to allow people to share the reporting on behalf of others for each experience (e.g. for autistic parents of autistic children)
