### ISSUE TITLE
Identify user testing requirements

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#545]
### Summary
If ethics approval is received - need to pick key parts of the platform to go through user testing
This is a summary following the July 2023 meet up ([Google doc](https://docs.google.com/document/d/1mYcTs0kfh8HWK1X87Wc5whARrhH_Rm9xaw2a-uT6UFs/edit#heading=h.7f28vh3w1oai)) and can be edited as needed

### Deadline 
September 2023

### What needs to be done?
Features to investigate
 - [ ] Understandability of CoC
 - [ ] The overall UX and workflow of adding stories 
 - [ ] Viewing stories 
 - [ ] Can you change permission
 - [ ] Can you share an experience
 - [ ] Do people understand what sharing their experiences mean
 - [ ] User testing the copy on the homepage (do they understand the ask) - Not sure what that means

### Who can help?

Anyone interested

**Comment by gedankenstuecke** [comment]
I've linked back to #517 which had a few suggestions for the overall planning, and there's a [Google Doc Georgia made for planning](https://docs.google.com/document/d/1P6Lw-2vl0CamEYH3G1wbHRQxWX4M4HmHXUd4cp3CSrM/edit). 

Regarding the last point on "do people understand the ask": What I meant was whether people understand what we would like them to do when engaging with AutSPACEs. A typical user-testing approach might be to give people clear asks of "can you use our product to do XYZ". But, would a new user themselves find out what we would like them to do/what the overarching goal of AutSPACEs is from _just_ looking at the platform or not?

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA and I just had a co-working session on the usability testing have come up with a rough outline and the tasks here: https://docs.google.com/document/d/1P6Lw-2vl0CamEYH3G1wbHRQxWX4M4HmHXUd4cp3CSrM/edit

**Comment by gedankenstuecke** [comment]
The two rounds of user-testing are now done! 🚀
