### ISSUE TITLE
[FEATURE]: Hover effects on the Nav links.

### ISSUE THREAD

**Issue by obinnaofomah** [alan-turing-institute/AutSPACEs#546]
### Feature for…

Frontend

### What is the problem you want to solve?

I believe we can modify the behavior of the links embedded in the nav bar. I would like the links to become visible to the user upon hovering over the nav bar, rather than being visible only upon click

### How do you want to solve the problem?
This feature can be implemented using JavaScript
_No response_

**Comment by gedankenstuecke** [comment]
It's a good consideration but we should also keep the accessibility in mind as those automatically opening menus can be hard for people to navigate if they erratically appear/disappear on hover. https://www.w3.org/WAI/tutorials/menus/flyout/ has some considerations for the flyouts
