### ISSUE TITLE
Upgrade to django 4.2.3 or newer

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#548]
### Summary

GitHub's [dependabot](https://github.com/advisories/GHSA-jh3w-4vvf-mjgr) informs that:

>  Django has regular expression denial of service vulnerability in EmailValidator/URLValidator 

I'm pretty sure we're not using either of these (and grep says the same), but we probably shouldn't be running a version with high severity security alerts anyway.

We're currently already on 4.2, so it should be an easy upgrade.

### What needs to be done?

- [ ] Update the dependences to django >= 4.2.3
- [ ] Check the docker deployment, unit tests and site still work after the upgrade.

### Who can help?

* Anyone with an interest in Poetry (the [python kind](https://python-poetry.org/), not the [other kind](https://peps.python.org/pep-0020/)).

---

**Comment by gedankenstuecke** [comment]
Would you want to give it a try or shall I claim this? I did the last Django upgrade, but would be happy to give someone else the opportunity to learn it anyone wants :-)

**Comment by llewelld** [comment]
I'm personally very happy either way; please feel free to claim it (you already know what you're doing with it!). I'm unlikely to get the chance to look at this before Friday morning, but if it's still unclaimed by then I can have a go myself.
