### ISSUE TITLE
Send out July Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#549]
### Summary

It's time to start writing our monthly newsletter for July. We should have some general updates as well as a contributor spotlight. 

### Deadline 

July 31st 

### What needs to be done?

- [x] Pick topics
- [x] Draft newsletter
- [x] Put into tinyletter & test
- [x] Send out the week before the meetup

### Who can help?

 
* Any suggestions for topics please add in comments 

---

### Updates

Draft newsletter is here: https://hackmd.io/@rj8H3yXSS7yBKr1z43JZCw/rJw1c0mQh/edit

**Comment by gedankenstuecke** [comment]
@obinnaofomah would you be interested in contributing as a "new contributor" highlight? You can see how it looks like in last month's newsletter which featured @llewelld: https://tinyletter.com/AutisticaTuringCitizenScience/letters/autspaces-june-newsletter

**Comment by obinnaofomah** [comment]
@gedankenstuecke Yeah, I would like to give it a shot. I am already working on the interview questions provided by Georgia.

**Comment by gedankenstuecke** [comment]
Perfect, thanks so much! 

The item I told @GeorgiaHCA about today: 

### AutSPACEs at Bioinformatics Open Source Conference

Our team member Bastian Greshake Tzovaras will be presenting our work with AutSPACEs at this year's _Bioinformatics Open Source Conference_ in Lyon, France. The conference brings together researchers, software developers and others in the field of developing open source tools for biology to learn from each other. Beyond his talk, Bastian will also be part of a panel on "Open & Ethical Data Sharing"

Links: https://www.open-bio.org/events/bosc-2023/ and https://www.open-bio.org/events/bosc-2023/bosc-2023-panel/

**Comment by GeorgiaHCA** [comment]
Thanks so much @obinnaofomah and @gedankenstuecke - closing this issue now
