### ISSUE TITLE
[BUG]: Viewing public experience crashes for Anon. users

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#552]
### Describe the bug

Currently it is not possible to view the publicly shared experiences unless one is logged in. As a logged-out user one encounters the following error:

`Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x400f471df0>>.`

The problem is that in line 335 of the `views.py` we load the user profile as `profile = UserProfile.objects.get(user=request.user)`, but non-logged in users have no expanded profile, so we need to catch that case :-) 

### Steps to reproduce

1. Log out of AutSPACEs, 
2. browse to `/main/public_experiences`
3. et voilà 😉

**Comment by llewelld** [comment]
Sorry for this, my fault, but thanks for discovering it! Probably we need a unit test to cover this case too.

**Comment by llewelld** [comment]
PR #555 is intended to fix this.
