### ISSUE TITLE
Create a presentation on the moderation paper 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#558]
### Summary

Presentation should outline the work we've done on moderation and the content of the paper for an unfamiliar audience. 

### Deadline 

Wednesday 2nd August (in case we deliver it for PPIE meeting), otherwise 3rd August for meet-up session

### What needs to be done?

- [x] Draft presentation
- [x] Co-working with JS and SF
- [x] Time and practice
- [x] Deliver

### Who can help?

Anyone! Please give comments, ideas, and feedback in comments to this issue

### Updates

Working on the slides [here](https://docs.google.com/presentation/d/1SGnUDP-bUQKIsjdKy9WxVZxQPSSjSZPoq0JKqeFk6vQ/edit?usp=sharing)

**Comment by GeorgiaHCA** [comment]
@JamesSCTJ @gedankenstuecke - would appreciate your input! Also Susanna although I'm not sure she's on this repo?

**Comment by gedankenstuecke** [comment]
Those slides are amazing! I merged in my slides that I just used at BOSC to give some context on what AutSPACEs is, so that people less familiar with our project have an easier time to understand our reasoning!

**Comment by gedankenstuecke** [comment]
We gave the talk and it's uploaded to Zenodo and linked from the project management directory! 🎉
