### ISSUE TITLE
Check users can review their answers before submitting a form

### ISSUE THREAD

**Issue by Angelsaur** [alan-turing-institute/AutSPACEs#56]
### Summary

Users need to be able to check their answers before submitting certain types of form, to confirm they’ve entered the correct information. This only applies to forms where there would be serious consequences to them making a mistake - for example, financial transactions or something that enters them into a legal contract.

### Deadline 

20/02/2021

### What needs to be done?

You can test this by going to any of your sample forms that meet these criteria and working your way through them. See if you’re presented with a page that lets you check your answers before submitting the form

**Comment by gedankenstuecke** [comment]
Made issue #369 to create an accessibility checklist that can be used for the MVP and going forward. Closing this along with other accessibility checklist items for now.
