### ISSUE TITLE
Schedule & Plan: Autistica Webinar

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#562]
### Summary

In recent meetings with Autistica we discussed presenting the progress on the content moderation policies and associated preprint in one of their webinars. We now heard back with some general advice for planning: 

* **Format:**
  * Live webinars – we use Zoom Webinars for the event and Eventbrite for ticket sales (tickets are free)
  * 1- 1.5 hours, depending on our preference
  * Either between 12-2pm or 5.30-7.30pm.
  * Agenda: for a one-hour session: 5 minutes for introduction, 40 minutes presentation, 10-15 minutes for questions and a thank you to the audience.
  * Hosts and panellists: host & tech supports from Autistica and ideally at least one autistic collaborator 
  * Should include audience involvement, e.g. through mentimeter for poll, word map, or something similar.
* **Date:**
  * Typically they host 1 webinar a month, next empty spot would be _November_. But they can be flexible if we want to do it earlier
  * Monday/Fridays are **not** recommended due to typically lower attendance

### Deadline 

~ mid-late august to schedule with enough advance notice

### What needs to be done?

- [x] Decide who wants to co-present on the work (@skfantoni & @JamesSCTJ would be obvious co-presenters given their key role in the moderation work) 
- [x] Pick a few potential dates/times to offer to Autistica
- [x] Decide on 1 vs 1.5 hour slot
- [x] Plan audience involvement 
- [x] Write [title & abstract](https://hackmd.io/@gedankenstuecke/ry3h3SJC2)
- [x] Prepare slides

### Who can help?

* @GeorgiaHCA, @skfantoni & @JamesSCTJ 
* Anyone else involved & interested in the moderation design

---

### Status

**Date:** Date now confirmed with Mercedes:

October 5th

Practice: 17:30 – 18:00
Webinar 18:00 – 19:00

#### For the interactive elements we brainstormed:

1. Asking people in a simple poll. Have you seen/been target of/reported inappropriate content online?
2. Word cloud: Which topics/things should be considered when making a moderation approach?
3. Moderation game: Give some (harmless) examples and ask people to rate green/amber/red

**Comment by GeorgiaHCA** [comment]
I agree an earlier date would be good - maybe we can also use it as a way to find people who might be interested in doing some user testing - in which case we should make sure we have what we need in place for that as well?

**Comment by gedankenstuecke** [comment]
I think that's a really great point, being able to use this for recruiting for the user testing would be user helpful. 

@KirstieJane: @GeorgiaHCA & I also wondered if you had an opinion!

**Comment by gedankenstuecke** [comment]
Okay, we got a slot for October 5th, exact time in the pm to be defined!

**Comment by gedankenstuecke** [comment]
And time is fixed now as well: October 5th, 6-7pm. 🎉

**Comment by gedankenstuecke** [comment]
We also need to provide a title, abstract & short bios of the presenters. I've made a document to draft it here: https://hackmd.io/@gedankenstuecke/ry3h3SJC2

**Comment by GeorgiaHCA** [comment]
I'm working on the slides here: https://docs.google.com/presentation/d/1Jn_JhZQQUWMHfxx4z3OtkUupw5DyWYkrUVLChWCq5sM/edit?usp=sharing
