### ISSUE TITLE
Apply to Autistica to recruit people for user testing 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#572]
### Summary

Autistica has a process for using their autism insight group and discover network to recruit autistic people. We need to fill in a form justifying why we should be able to recruit from their network. 

Form must be submitted here: https://www.autistica.org.uk/our-research/network-application 

### Deadline 

They suggest that you need to apply 2 months in advance of recruitment, so we should do it soon (by COP this week?) and potentially try to find other people to test with in the meantime. 
 
### Updates 

Working on the form here:

https://hackmd.io/10xD-_LfSXmldkOUG1CETA

Creating an onboarding/info page for people interested in user testing here: 

https://hackmd.io/6etcYwylQLmj5GEWFEtV1w

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA and I have finalized the documents: 

- [Landing page on the Wiki](https://github.com/alan-turing-institute/AutSPACEs/wiki/User-testing)
- [Participant Information Sheet](https://github.com/alan-turing-institute/AutSPACEs/blob/main/00-project-documentation/community/user-tests/AutSPACEs%20User%20Testing_%20Participant%20Information%20Sheet.pdf)
- [Consent form](https://github.com/alan-turing-institute/AutSPACEs/blob/main/00-project-documentation/community/user-tests/AutSPACEs-consent-form.pdf) 

With this I've filled out the Autistica form for requesting distribution of the recruitment, see full resonses here: [Response Data.pdf](https://github.com/alan-turing-institute/AutSPACEs/files/12357247/Response.Data.pdf)
