### ISSUE TITLE
September 7 Meetup

### ISSUE THREAD

**Issue by gedankenstuecke** [alan-turing-institute/AutSPACEs#574]
### Summary

We gotta prepare the September 7 meet-up plan & invites

### What needs to be done?

- [x] Pick topics for the meet-ups
- [x] Prepare agenda
- [x] Send out email reminder/invites

### Who can help?

* @GeorgiaHCA 
* anyone with topic ideas!

---

#### Agenda

* Announce user testing and enrolment for it
* Discussion on terminology: Experience/Story (c.f. #566)
* Platform updates:
  * @llewelld: #535 
  *  @helendduncan: #544

**Comment by gedankenstuecke** [comment]
In terms of topic ideas:

- My question regarding the wording/terminology could make a topic of discussion, cf. #566 
- We could chat about potential user testing approaches/open questions
- @llewelld, @helendduncan & @obinnaofomah might have potential updates to ask for feedback on?

**Comment by gedankenstuecke** [comment]
* @llewelld can present the JS-based walkthrough/tutorial

**Comment by gedankenstuecke** [comment]
* @helendduncan to share progress on #544

**Comment by gedankenstuecke** [comment]
That's great, thanks! I've updated the links etc. on the Wiki page for the meetups as well!

**Comment by GeorgiaHCA** [comment]
Done! Looking forward to the meet-up
