### ISSUE TITLE
User Testing: Update front page

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#586]
### Summary

During user testing the following comments/issues were noted with the from page

- [x] No links to reading experiences
- [x] No links to writing experiences (or logging in)
- [x] Get involved and what autism is can be removed from front page
- [x] Add description of the platform
- [x] Increase/share/advise -> "our goals" or similar
- [x] How to use platform -> "Get Involved - use yellow" Reading stories + Contributing stories (with links) (- "Read More")
- [x] Shared stories: Replace placeholder stories with published stories (? pull from DB - set env variable to pick from selected uuids?) If not use current placeholder/seed stories
- [x] Original get involved (GitHub links etc) can go
- [x] Original what autism is can go
### Deadline 
Mid October 2023

### What needs to be done?
See checklist above

### Who can help?

---

**Comment by llewelld** [comment]
In relation to the **"Increase/share/advise -> "our goals" or similar"** item, there was a comment made during user testing that relates to this and which it might make sense to tackle at the same time:

"Unsure about meaning of "advise" text - thinks it should link to "advice" page and potentially link to other websites"

This relates to the wording of the text on the front page that says "Advise - organisations how to create better environments for autistic people". We should consider tweaking the wording (e.g. to remove the term "Advise") to try to avoid this confusion.

Note @GeorgiaHCA's PR #581 updates the copy on the page, so it should be checked whether this already fixes the issue.
