### ISSUE TITLE
User Testing: Flexible Success Page

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/AutSPACEs#588]
### Summary

During user testing there was some confusion around the wording of the success page after story submission. As users are presented with the same page if they have edited a story, submitted for the first time, or made private.
In issue #587 - it has been suggested that a success page framework can be used with appropriate links and wording based on the situation (including after profile submission) 

### Deadline 
Mid October 2023

### What needs to be done?

- [x] Decide how the info on previous page is sent to the success page (request/session)
- [x] Populate with appropriate links
- [x] Also use the page for the reminder of not having filled in the user profile yet if not done yet (see #534 / #578)

**Comment by gedankenstuecke** [comment]
This has now also been addressed by #633 🚀 :shipit:
