### ISSUE TITLE
User testing: Add process to registration info page

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#590]
### Summary

After selecting the option to register the user is presented with a Registration page. It would be helpful to include a bullet-point list describing the registration process (e.g. 1. You'll be asked to create a profile on OpenHumans; 2. Authorise AutSPACEs; 3. fill in your profile).

The relevant page:
http://\<domain\>/main/registration/

### Deadline 

Mid-October.

### What needs to be done?

- [ ] Add content to the Registration page.
- [ ] Update the link to OpenHumans to correctly start the authorisation process.
- [ ] Open the link in a new tab/window.

### Who can help?

* Anyone will to edit the page or suggest wording.

---

**Comment by gedankenstuecke** [comment]
This was addressed by #632 thanks to @llewelld!
