### ISSUE TITLE
User testing: Navigation bar

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#592]
### Summary

Changes to the menu bar along the top.

AutSPACEs
1. View Stories
2. Share Storeis (when logged in)
3. My Stories (when logged in)
4. Moderation -> Pending, Approved, Rejected (tabs?) (when logged in)
5. Learn More -> What is Autism, About Us, CoC, Help

### What needs to be done?

- [ ] Update the menu bar to reflect the structure above.

### Who can help?

* Anyone who wants to hack the menu bar.

---

**Comment by llewelld** [comment]
Would it make sense to change the title on the 'Shared Stories' page to 'View Stories' to match the menu item?

![Screenshot 2023-09-25 at 17 49 48](https://github.com/alan-turing-institute/AutSPACEs/assets/1446122/e2d02f65-e985-4fd2-9414-dc17765ba5f3)

**Comment by gedankenstuecke** [comment]
Yes, I think that would be great! :)

**Comment by gedankenstuecke** [comment]
<img width="527" alt="Screenshot 2023-10-05 at 21 47 31" src="https://github.com/alan-turing-institute/AutSPACEs/assets/674899/4d5a9648-262d-4ef9-b2d1-8493227c5abd">

Looking at the mobile/collapsed view, the "account" sub-menu looks like it's indented a bit for some reason. I'm not sure if this was always the case or is a result of recent changes, but should we try to get it into the same "depth"? 🙂
