### ISSUE TITLE
Make it easier to add a story 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#599]
### Summary

Multiple testers found it difficult to know how to add a story on AutSPACEs and the instructions were quite hidden away. It would be useful to have an obvious add story button on the main homepage that would link to a diagram which takes you through the process and let you click on a registration link, and include other "add story" options throughout the platform. 

### What needs to be done?

- [x] Include an "add story" in nav bar for non-logged in users which takes you to the register or login page
- [x] Include on the register page information a clear user journey in the form of text and a diagram, plus a link to register, as well as clear text saying, "if you are already a user click here to log in" 
- [x] Include an obvious "add story" button on the homepage that would lead to the registration page if you are not logged in and the submit experience story if you are 
- [x] Include an "add story" button in the "view experiences" section of the website that would lead to the registration page if you are not logged in and the submit experience story if you are
- [x] Include a separate "add story" section on the nav bar for signed in users instead of it being part of a drop down menu

**Comment by gedankenstuecke** [comment]
Also interacts with #591, #586, #592
