### ISSUE TITLE
Change placeholder text on Open Humans Authorisation Page

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#600]
### Summary

When you register it takes you to an authorisation page via. Open Humans. This page currently confuses users, but the format can't be change all that much as it is part of the universal Open Humans interface design. 

### What needs to be done?

- [x] Change placeholder text on authorisation page to clearly explain what Open Humans is and how to proceed with registration.

**Comment by gedankenstuecke** [comment]
I've updated the text on OH and also added a bit more information on the registration page ❤️
