### ISSUE TITLE
BUG: Text on Homepage under "How to Use the Platform" overlaps when page enlarged 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#601]
### Summary

When page is enlarged for those who need larger text, the text on the "How to Use Platform" overlaps with other text making it hard to read.

### What needs to be done?

- [ ] Fix the bug and test it with enlarged text

**Comment by gedankenstuecke** [comment]
This also relates to #576 and closing this in favor of it
