### ISSUE TITLE
[FEATURE]: Add a dark theme

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#604]
### Feature for…

Frontend

### What is the problem you want to solve?

Suggestion made during user testing.

Some users prefer or find text more legible when using a dark theme (light text on a darker background). Many sites now support this and most browsers have support for switching themes based on a system-wide default. Users have therefore come to expect that an accessible site will support both a light and dark theme.

### How do you want to solve the problem?

Possible solutions:
 1. [ ] Provide a CSS dark theme and a switch on every page to toggle between the dark and light theme.
 2. [ ] Provide a CSS dark theme that toggles based on the system defult.
 3. [ ] Provide a CSS dark theme and a switch that can be toggled in the user profile.

### Other comments

Examples of sites with a dark theme:
1. [Github](https://github.com)
2. [Google](https://www.google.com)
3. [DuckDuckGo](https://duckduckgo.com)

Potentially useful reference material:
1. [The Ultimate Guide to Enabling Dark Mode Everywhere](https://www.howtogeek.com/449742/the-ultimate-guide-to-enabling-dark-mode-everywhere/)
2. [A Complete Guide to Dark Mode on the Web ](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)

**Comment by gedankenstuecke** [comment]
With the new bootstrap update we already have this partially in place, currently the website auto-adjusts to the OS settings. 

What's still to do :
1. Implement mode picker: https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode 
2. Check that the colours are compatible with dark mode
