### ISSUE TITLE
Make platform more comfortable for R/G colour-blind users 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#605]
### Summary

Currently, the platform uses variants of reds and greens. These are visible to colour blind users but are still uncomfortable and can make eyes tired. We need to adjust the colour palette so it is more comfortable for people with R/G colour blindness. 

### What needs to be done?

- [ ] Adjust colour palette on all pages 
- [ ] Test again with people with R/G colour blindness

**Comment by gedankenstuecke** [comment]
The colour red was generally commented on as potentially problematic as it is a warning colour

**Comment by GeorgiaHCA** [comment]
Multiple users didn't like the red colour - it was considered too much of a "warning colour"
Other users felt that there were too many colours and this was overwhelming
-- Suggest restricting the colour palette so their are fewer colours, focussing on the turquoise as a main colour

**Comment by gedankenstuecke** [comment]
Partially addressed with the dark mode in #604, colours will be addressed in #667
