### ISSUE TITLE
Include pointers to other websites for support and resources

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#608]
### Summary

AutSPACEs has a specific function but we want to support users by directing them to support and resources. It would be useful to include pointers to other websites both so we can support users and to make sure the purpose of AutSPACEs is clear and distinct from other services. 

### What needs to be done?

- [ ] List some possible links to other resources based on what needs there are likely to be in the community (e.g. samaritans, support for getting a diagnosis)
- [ ] Include suitable copy and link to these sites in sensible places on the website

**Comment by GeorgiaHCA** [comment]
I think this may relate to an existing issue where we started to compile some possible external sites to link to?

**Comment by gedankenstuecke** [comment]
@Davsarper, @GeorgiaHCA & I discussed this at the last meeting and decided to not link out to resources just yet, as we do not want to endorse particular ones until we're sure which ones based on community input
