### ISSUE TITLE
[FEATURE]: Add RSS feeds

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#610]
### Feature for…

Frontend and Backend

### What is the problem you want to solve?

Suggested during user testing.

RSS feeds would be useful: uses these to filter information and return to websites.

An RSS feed would allow users to access the content in a different way, supporting different workflows (e.g. where a user is interested to see all the material that's added, or is only interested in the latest changes).

A separate app is often used to read RSS feeds, which means the user can have greater control over how viewing is configured compared to using the website.

Adding an RSS feed might improve accessibility for some users.

### How do you want to solve the problem?

1. [ ] Provide a URL where the RSS feed can be accessed.
2. [ ] Add links to the URL on the main website.

### Other comments

RSS feeds can usually be accessed without a login. Would different RSS feeds therefore need to be made available in order to ensure different forms of triggering content are omitted?

Potentially useful references:
1. [RSS docs on W3Schools](https://www.w3schools.com/XML/xml_rss.asp).
2. [RSS spec](https://cyber.harvard.edu/rss/rss.html).
3. [Atom docs](https://validator.w3.org/feed/docs/atom.html).

**Comment by gedankenstuecke** [comment]
It seems that Django has a simple method to create feeds throught he `Feed` class: https://docs.djangoproject.com/en/4.2/ref/contrib/syndication/
