### ISSUE TITLE
Make it clear triggering content preferences can be changed any time

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#612]
### Summary

We currently allow people to select their preferences for what kinds of potentially triggering content they would like to view when they set up their profile. We should make it clear on the profile page that this is not a permanent choice and they will be able to change their preferences any time after they have registered. 

### What needs to be done?

- [ ] Include a clear sentence to say the preferences can be changed at any time, but that these will be used as a default
- [ ] Include clear instructions on how to change preferences

**Comment by gedankenstuecke** [comment]
Potentially relates to #587
