### ISSUE TITLE
Make sharing options clearer

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#613]
### Summary

This is an issue that arose during user testing.

"Make sharing options clearer, e.g. "would you like this private or public?""

Currently the sharing options are given using the following text:

```
Sharing Options
Please indicate if you want to share your experience
[ ] Share on AutSPACE website
[ ] Share for research
```
As they're checkboxes there are actually four options here.

The text may not be as clear as "public" and "private". It would be good to improve on this.

### What needs to be done?

- [ ] Decide on clearer text and/or layout.
- [ ] Update the front end to use the new text.

### Who can help?

* Front end design/wording.
* Front end implementation.

**Comment by gedankenstuecke** [comment]
Rename labels to
1. "Share _publicly_ on AutSPACEs" 
2. "Allow story to be used for research" 
3. 
also give help text "If neither of these boxes are checked, the story is only visible to you"
