### ISSUE TITLE
Support users to navigate the platform more easily 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#615]
### Summary

Currently, a lot of users find that there is a lot of information and different things to click on, but would like a map or some kind of guide to navigating the website. 

### What needs to be done?

- [ ] Map out all the different AutSPACEs pages and functions
- [ ] Create an interactive map of contents so people can find how to get to different parts of the website
- [ ] Present this so that it is clear and easy to follow and understand. 
- [ ] Include this in a sensible place (e.g. help section or even a new "site map" page)

**Comment by gedankenstuecke** [comment]
Overall, this seemed like a minority opinion during the user testing, I'd shelf this for now in favour of bigger changes (also cf. #535)

**Comment by gedankenstuecke** [comment]
Also see #617 for next round of user tests

**Comment by gedankenstuecke** [comment]
Closing this as second round of user testing shows that the user flow has been improved! 🚀
