### ISSUE TITLE
Make "my stories" page easier to use and its functions clearer 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#616]
### Summary

Currently the "my stories" page is quite confusing to users:

- Currently the dashboard doesn't update to show when stories have been added 
- Users expect to be able to view their stories from the main dashboard and don't always realise they can scroll down to see a table of their stories 
- It is not clear to some users how to edit stories from their "my stories" page or change sharing options 

### What needs to be done?

- [ ] Make the text consistent: we have "in process" and pending but these are the same things
- [ ] Make sure the dashboard updates according to stories added/moderated etc. 
- [ ] Have the top of the table clearly visible as soon as you enter the page so users don't have to scroll down to see it
- [ ] Include a clear option to change privacy settings without having to edit the whole story - ideally find a way to do this without having to go back to the editing page.

**Comment by gedankenstuecke** [comment]
This is already being addressed in #595 (also c.f. #591)
