### ISSUE TITLE
Test to see if users find it clear what you need to register for

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/AutSPACEs#617]
### Summary

This issue came out of user testing:

"Lack of clarity for which things an account is or isn’t needed?"

For example, currently no registration is necessary to view stories, but registration is necessary to add stories. Some users therefore found it difficult to understand which actions required registration and which did not.

We've already got quite a few changes related to the user flow through the site, so it would be good to return to this later and decide whether it's still an issue after the changes.

### What needs to be done?

- [ ] Review clarity once the current front-end changes have been completed. 

### Who can help?

* Anyone can please express their opinion on the matter.
* If changes are needed design suggestions.
* If changes are needed, implementation.

**Comment by gedankenstuecke** [comment]
We have adapted the user flows accordingly, in the second round of user tests this did not seem to be a big issue anymore! 🚀
