### ISSUE TITLE
Co-write copy for the website on Autism 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#621]
### Summary

It would be useful to have more information on autism on the "about" page. This should ideally be written or co-written with an autistic person and checked with Autistica to make sure it is accurate, value-aligned and reflects the lived experience of autistic people. 

### What needs to be done?

- [x] Ask an autistic person to support writing the copy for the platform 
- [x] Co-write the copy with autistic collaborator 
- [x] If possible, find a way of "thanking" them for their time (potentially via. the SSI?)
- [x] Implement copy on platform
- [ ] Test with users

**Comment by gedankenstuecke** [comment]
Some main issues that emerged during the user testing regarding the copy or the way we introduce concepts: 

1. The "triggering label" settings are provided in the profile creating, but it's not fully explained what that means
2. similarly, the "notify when moderated" setting hints at moderation but doesn't explain what the moderation means

**Comment by gedankenstuecke** [comment]
Also worth to check for #566, @GeorgiaHCA maybe worth mentioning to AM? :-)

**Comment by gedankenstuecke** [comment]
I'm closing this issue for now, as we've merged the copy into the platform. We have no concrete user testing plans for the copy itself, but will keep an eye on it post-launch
