### ISSUE TITLE
December Newsletter 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#638]
# Summary
It's time to draft the next AutSPACEs newsletter!

# Deadline
December 22nd

# What needs to be done?

-  select topics
-  draft newsletter
-  review
-  send out

# Who can help?

Add updates in comments below or in the #autspaces Slack!

**Comment by gedankenstuecke** [comment]
Topic ideas: 
- Submission for ECSA was accepted (cf #594)
- Did the AutSPACEs ethics submission

**Comment by GeorgiaHCA** [comment]
Newsletter preview sent :)
