### ISSUE TITLE
Respond to reviewer feedback on Moderation Paper

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#641]
### Summary

We need to make revisions to the paper to respond to reviewer feedback. 

### What needs to be done?

- [x] Initial thoughts about how to approach changes
- [x] Meet as a team to discuss
- [x] Initial redraft
- [ ] Authors review
- [ ] Resubmit

### Who can help?

* Bastian and Georgia tackling it initially
* James and Susanna to meet to input
* Any thoughts by any of the authors welcome!

**Comment by gedankenstuecke** [comment]
Resubmitted and updated the preprint! Thanks everyone!
