### ISSUE TITLE
January Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#646]
# Summary

It's time to darft the next AutSPACEs newsletter!

# Deadline

January 31st

# What needs to be done?

-  select topics
-  draft newsletter
-  review
-  send out

# Who can help?

Add updates in comments below or in the #autspaces Slack!

**Comment by GeorgiaHCA** [comment]
Can you think of who might be a good person to invite for the spotlight interview?

**Comment by gedankenstuecke** [comment]
Just so we don't forget, the event that @KirstieJane had shared on the slack: https://www.eventbrite.co.uk/e/lgbtq-in-stem-networking-symposium-tickets-790045245597

**Comment by gedankenstuecke** [comment]
[CW24](https://www.software.ac.uk/news/call-cw24-mini-workshops-and-demos-and-lightning-talks-open) has opened the call for mini-workshops/demos/lightning talks and citizen science is one of the topics. 

we can for sure add it to the newsletter, but the question is whether we want to include a few words on that we might aim to submit a demo or something and are looking for co-presenters, following our discussion on inclusive co-facilitation?

**Comment by GeorgiaHCA** [comment]
Should we also include AI UK?

**Comment by gedankenstuecke** [comment]
Yes, I think we can include AI UK as a "we are currently making plans to have a short talk on citizen engagment we will co-present" but not more, as I'm not sure how much detail there has been fixed?

**Comment by GeorgiaHCA** [comment]
Draft newsletter is here: https://hackmd.io/S5I81b21RDydLNo1t1Z0HA - still waiting to hear from potential spotlight interviewees.

**Comment by gedankenstuecke** [comment]
The draft is currently inaccessible, could you change the permissions @GeorgiaHCA ?

**Comment by GeorgiaHCA** [comment]
Oops sorry - yep: https://hackmd.io/@rj8H3yXSS7yBKr1z43JZCw/By_ZkfB9p/edit

**Comment by gedankenstuecke** [comment]
Thanks, could you also make it editable to make some suggestions? :D

**Comment by GeorgiaHCA** [comment]
Great news - we have a spotlight interviewee! He'd rather speak than write so I'm interviewing him later and he shared a few pointers in the meantime about what to include. 😄

**Comment by gedankenstuecke** [comment]
Sent out, thanks to @GeorgiaHCA's great drafting! 🚀
