### ISSUE TITLE
Prepare for AI UK 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#650]
### Summary

A 25 min research talk on participatory methods. Georgia will introduce what participatory methods are and their importance, then two usecases will be presented:
- Connected by Data will explain their work
- AutSPACEs contributor (remote) will talk about their experience as a participant, why they chose to participate and keep doing it and what it has meant to him. Georgia will make 3 brief questions to prompt the answers and bring a more conversational tone to the talk.

| 0-5' | Intro to Participatory methods |
|--|--|
| 5 - 15 | Connected by Data |
| 15 - 25' | AutSPACEs

### Deadline 

Our slot is: Tues 19 March at 10:25 - 10:50am on the Future Stage.

### What needs to be done?

- [x] Invite co-presenters 
- [x] Plan session
- [x] Feedback and finalise
- [x] Practice run
- [x] Present 

### Who can help?

Any suggestions welcome in the comments below. 

### Updates

David has done a fab outline here: https://hackmd.io/ujfSSW4PQ5ywvhdT-nckgA 
Here's a Hackmd with a run through: https://hackmd.io/4-qHhbFfQ566u6-4B8Ppqw

**Comment by gedankenstuecke** [comment]
might be worth to send a reminder for this one at some point to have enough time to plan the session?

**Comment by gedankenstuecke** [comment]
Perfect, thanks! 🙏
