### ISSUE TITLE
February newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#656]
# Summary

It's time to draft the next AutSPACEs newsletter!

# Deadline

February 28th 

# What needs to be done?

-  select topics
-  draft newsletter
-  review
-  send out

# Who can help?

Add updates in comments below or in the #autspaces Slack!

**Comment by gedankenstuecke** [comment]
topic to include: the SSI blog post about our first round of user testing! https://www.software.ac.uk/blog/user-testing-citizen-science-platform

**Comment by GeorgiaHCA** [comment]
I've added it in the draft: https://hackmd.io/8NujwtJsRDm6yZlmklG9EA

**Comment by GeorgiaHCA** [comment]
I'll send DM a reminder prompt Monday or Friday for the spotlight interview too

**Comment by gedankenstuecke** [comment]
Newsletter has been send out without the interview feat. DM, will be put in the next newsletter instead. 

The newsletter is also archived on GH & on the new wordpress newsletter
