### ISSUE TITLE
Send March Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#664]
# Summary

It's time to draft the next AutSPACEs newsletter!

Draft is here: https://hackmd.io/0gbef2oHQJiI1KJ1DdmvGQ

# Deadline

March 31st 

# What needs to be done?

-  select topics
-  draft newsletter
-  review
-  send out

# Who can help?

Add updates in comments below or in the #autspaces Slack!

**Comment by GeorgiaHCA** [comment]
Thanks @Davsarper and @gedankenstuecke !!

**Comment by gedankenstuecke** [comment]
@GeorgiaHCA could you also upload the newsletter into the project management folder so that we have a copy of it here too? :)
