### ISSUE TITLE
[FEATURE]: Add 'Help' button on navigation bar

### ISSUE THREAD

**Issue by Davsarper** [alan-turing-institute/AutSPACEs#668]
### Feature for…

Frontend

### What is the problem you want to solve?

A user tester suggested that it could be helpful to also find the 'Help' button on the navigation bar.
Not a repeated request but it makes sense as key sections/features should be available via at least two interactions pathways

### How do you want to solve the problem?

Add Help to navigation bar

**Comment by gedankenstuecke** [comment]
We've reordered the menu bar as part of the copy edits :-)
