### ISSUE TITLE
Run a mini workshop for the SSI CW 2024

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#671]
### Summary

We're running a workshop on inclusive community co-creation. The theme is on participatory/community-led practices in general using AutSPACEs as a case study. There will be a brief presentation followed by discussion sessions and a group share out. 

### Deadline 

Session is going to be held on Tuesday, 30 April 2024, 14:40 - 15:40 BST (13:40 - 14:40 UTC)

### What needs to be done?

- [x] Organise facilitation (Georgia and Bastian online, @KirstieJane  in-person ❤️ )
- [x] Create presentation
- [x] Create google doc
- [x] Trial run through
- [x] Host session

### Who can help?

* Any suggestions queries or comments please add in comments below!  

### Updates

Co-working with @gedankenstuecke tomorrow morning at 10am. 
Working on slides here: https://docs.google.com/presentation/d/17syRbwNO_rN5KSmcXEO7QBcUBU_RY4Jv_6RKdwBrBQQ/edit?usp=sharing
Working on the notes doc here: https://docs.google.com/document/d/1jLsGgnd0KgV67UUaJqSyghLaF0FC_j8aL7U3Li03qXc/edit?usp=sharing
Original submission is here: https://hackmd.io/@rj8H3yXSS7yBKr1z43JZCw/rJwxHwjna

**Comment by gedankenstuecke** [comment]
Huge thanks to @KirstieJane & @GeorgiaHCA for facilitating the workshop in person & remotely! We've started to plan out #234 with the workshop!
