### ISSUE TITLE
Send out April Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#672]
# Summary

It's time to draft the next AutSPACEs newsletter!

Draft is here: https://hackmd.io/0gbef2oHQJiI1KJ1DdmvGQ

# Deadline

April 30th

# What needs to be done?

- [ ] -  select topics
- [ ] -  draft newsletter
- [ ] -  spotlight interview  
- [ ] -  review
- [ ] -  send out

# Who can help?

Add updates in comments below or in the #autspaces Slack!

**Comment by GeorgiaHCA** [comment]
We have a wonderful reflection by Margaret who took part in AI UK it could be good to include that either as spotlight or as an extra addition

**Comment by GeorgiaHCA** [comment]
Topics I have so far: AI UK reflections, CW SSI, Platform Updates, potentially a short section on autism and music by KB

**Comment by gedankenstuecke** [comment]
This is sent out thanks to @Davsarper!
