### ISSUE TITLE
Send May Newsletter

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#679]
# Summary

It's time to draft the next AutSPACEs newsletter!

# Deadline

May 31st

# What needs to be done?

- [x] -  select topics
- [x] -  draft newsletter
- [x] -  spotlight interview  
- [x] -  review
- [x] -  send out

Newsletter is here: https://hackmd.io/@rj8H3yXSS7yBKr1z43JZCw/HJVYF037C/edit - still waiting for contributions from Bryony and Kat :) 

# Who can help?

Add updates in comments below or in the #autspaces Slack!

**Comment by GeorgiaHCA** [comment]
Bryony is going to do the spotlight interview

**Comment by GeorgiaHCA** [comment]
Any topics you'd like included @gedankenstuecke, @Davsarper?

**Comment by gedankenstuecke** [comment]
Newsletter was sent out, thanks @Davsarper for handling it! ❤️ 

I've also put this one (and the last one) into the project documentation folder!
