### ISSUE TITLE
Plan June Meet-Up Session 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#680]
### Summary

We need to plan the next Community Meet-up in June

### Deadline 

Thursday 6th June 2024 

### What needs to be done?

- [x] Choose Agenda and create google doc
- [x] Add details into newsletter 
- [ ] Send reminder email 

### Who can help?

* 
* 

---

### Updates

Proposed agenda/notes doc is here: https://docs.google.com/document/d/1BugX18HOadIVo8ABqo1E_Cgs6ldFn9XTEYSm85nITgg/edit

**Comment by GeorgiaHCA** [comment]
I was thinking that co-working on the glossary would be a good activity to do for the June meet-up session since it's been brought up a few times recently by community members.

**Comment by GeorgiaHCA** [comment]
This could also be a good time to talk about the co-creation chapter for The Turing Way?

**Comment by gedankenstuecke** [comment]
Yes, those sound like two good discussion topics!
