### ISSUE TITLE
Respond to Queries about Platform 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#686]
### Summary

There are a few queries from Alex about the wording for the platform. I'm putting them here so we can discuss them visibly. 

## 1. Add stories page - Welcome to AutSPACEs registration
There was an unresolved query for Bastian to decide from your earlier comments about a sentence on the relationship between Open Humans and the AT Institute. I currently have:
The Alan Turing Institute has been working with Open Humans to create AutSPACEs. Is this wording okay?

## 2. Learn more page - Our goals
These are in a different order on the home page – and the wording is a little different (ie influencing rather than advising). Which is the preferred order/wording?

## 3. Content guidelines - What and who AutSPACEs is for
Do you still plan to add links for professional support, or should I delete the reference to these?

## 4. Content guidelines - What is and isn't okay to mention
Do you still plan to add a link for racial slurs?

## 5. Content guidelines - Writing on behalf of others
Do you still plan to add links for resources for parents/carers, or should I remove the mention of these?

## 6. Help - What does being an AutSPACEs moderator involve?
The current wording implies, but doesn't state outright, that moderators need to be autistic. Is this correct or yet to be decided? If correct, I'll make it explicit.

**Comment by GeorgiaHCA** [comment]
## Learn more page - Our goals
These are in a different order on the home page – and the wording is a little different (ie influencing rather than advising). Which is the preferred order/wording?

I believe the wording on the home page is the more up-to-date one - I think the "influencing" wording comes from community feedback.

**Comment by GeorgiaHCA** [comment]
## Content guidelines - What and who AutSPACEs is for

We decided on taking out references to other organisations as we don't have affiliations with them - however there were a lot of requests for linking to other organisations for support (e.g. Samaritans). Don't know if we ever settled this one.

**Comment by GeorgiaHCA** [comment]
## Content guidelines - Writing on behalf of others

Do you still plan to add links for resources for parents/carers, or should I remove the mention of these? As above. A lot of this is around clarifying what the platform is and isn't for which is in the moderation guidelines

**Comment by GeorgiaHCA** [comment]
## Help - What does being an AutSPACEs moderator involve?

The current wording implies, but doesn't state outright, that moderators need to be autistic. Is this correct or yet to be decided? If correct, I'll make it explicit.

A lot of people felt very strongly that moderators should be autistic, or that at least one autistic person should look over submissions - but we need to make sure that's feasible? One option to balance it might be to have an autistic person overseeing, or supporting, moderation overall who people could appeal to - but that might create a lot of pressure.

**Comment by gedankenstuecke** [comment]
Following the co-working: 

## 1. Welcome to AutSPACEs

Wording is okay as is but make a link to the PIS where we have more details on the connection between AutSPACEs & OH

## 2. Learn more page - Our goals

Keep the order from the front page (share, influence & educate) and then also add the headings on the "learn more" page

## 3. Content guidelines - who AutSPACEs is for: 

Remove _AutSPACEs cannot offer professional support, however, we can link you to appropriate sources if necessary._

## 4. Do we plan to link to a list racial slurs?

Remove reference to link as we don't have a good resource at hand

## 5. Links for resources for carers

Remove reference to _If you need more support as a carer or parent, we recommend these resources: [link to resources?]_

## 6. Who are the moderators?

> What does being an AutSPACEs moderator involve?
> 
> Thank you for your interest in becoming a moderator for AutSPACEs. This is a hugely important and valuable role. As a moderator you will have a direct impact on the experiences of people using the AutSPACEs platform. You can help ensure that AutSPACEs is a welcoming and inclusive space where autistic people can be heard.

Need to be clear here that we are in the process of developing the process for community members to become moderators. Not live yet, reasons: data protection, ethics responsibility, …
