### ISSUE TITLE
 Brief explanation of explore stories page

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#69]
### Summary

A few sentences only to describe the explore stories page and what can be done there. 

### Deadline 

31 Jan 2021

### What needs to be done?
This is fixable with a simple commit by adding some html text to the "explore-stories.html" file in "main".

### Who can help?
This is a really good first issue for anyone beginning on their web development journey .

**Comment by sowmya9507** [comment]
@GeorgiaHCA is there any specific explanation that has to be added to this page ?
