### ISSUE TITLE
[BUG]: inconsistent stories

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#698]
### Describe the bug

The carousel on the main page of AutSPACEs shows a different set of stories compared to the view experiences page. I think these are older ones we used as template examples following a meet-up session and uploaded to the site. They are real stories therefore, but haven't been submitted in the usual way. 
It does mean the carousel is not automatically updating with new experiences added!

**Comment by gedankenstuecke** [comment]
Great catch, I've added in links to some real stories in 2f4a581, so those show up now!
