### ISSUE TITLE
Newsletter August 2024

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#699]
### Summary

Write an August newsletter. As AutSPACEs is coming to a close at least at The Turing, it's important to get the tone right and offer explanations and leave open channels for questions. It would also be good to use the newsletter to invite people to a celebratory September meet-up session! 

### Deadline 

31st August

### What needs to be done?

- [ ] create _HackMD_ [from template](https://hackmd.io/@gedankenstuecke/BypHfzPEC) for drafting
- [ ] add link to HackMD to this issue
- [ ] collect topics & potential spotlight interview person
- [ ] draft newsletter
- [ ] get newsletter reviewed
- [ ] send out newsletter
- [ ] add newsletter to [GitHub Folder](https://github.com/alan-turing-institute/AutSPACEs/tree/main/00-project-documentation/communication/newsletters)

---

### Updates

Link to the draft newsletter is here: https://hackmd.io/@gedankenstuecke/B10yA3ajR (editable version, replaces read-only one from @GeorgiaHCA)

**Comment by gedankenstuecke** [comment]
I edited a version of the newsletter here: https://hackmd.io/@gedankenstuecke/B10yA3ajR

**Comment by gedankenstuecke** [comment]
Closed as sent and added to archive on GH
