### ISSUE TITLE
[BUG]: Registration

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#701]
### Describe the bug

1. Register in Open Humans using Google results in a server error 
2. Verification using email loops round (resolved as wrong link clicked)

**Comment by gedankenstuecke** [comment]
Whops, sorry for that. I’ve fixed that just now!


On 14 Aug 2024, at 14:20, Georgia ***@***.***> wrote:


Describe the bug

  1.  Register in Open Humans using Google results in a server error

Steps to reproduce

No response

In which environment are you using AutSPACEs?

No response

Other comments

No response
