### ISSUE TITLE
Add Autistica and Turing logos

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#71]
### Summary

Add Autistica and Turing logos to the MVP website on the landing page. 

### Deadline 

20/02/2021

### What needs to be done

New imags can be included by adding them to the folder https://github.com/GeorgiaHCA/AutSPACEs/blob/main/, and then creating a path to them via. changing the html code in  https://github.com/GeorgiaHCA/AutSPACEs/blob/main/server/apps/main/templates/main/index.html

Work on this has already been done by the Fujitsu team and is in the [Autistica platform prortype repo](https://github.com/fjThomasStanley/AutisticaPlatformPrototype/blob/master/skeleton/templates/application.html). 

### Who can help?
 
Georgia is on it, but this is a relatively easy change to make so if you would like to work on it just link to this comment tagging in @GeorgiaHCA. You can also tag Georgia if you'd like to work on this but get stuck.

**Comment by NEERAJAP2001** [comment]
Hello @GeorgiaHCA, I'm working on this issue but where should I change the Html Code in https://github.com/GeorgiaHCA/AutSPACEs/blob/main/server/apps/main/templates/main/index.html 
I'm assuming it's [Here](https://github.com/GeorgiaHCA/AutSPACEs/blob/2392e4ee731c44661059b35cc205613697c782d6/server/apps/main/templates/main/index.html#L140)
Creating and new class and adding the images?



> New imags can be included by adding them to the folder https://github.com/GeorgiaHCA/AutSPACEs/blob/main/,

The Folder link is broken so where should I add images?
