### ISSUE TITLE
Integrate gov.uk components 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#81]
### Summary

Investigate proposed gov.uk components to make sure that they are suitable in their current place for the MVP 

They should:

- function with Django framework and fit with Open Humans backend
- be accessible to diverse users
- be sufficiently well-documented that they can easily be picked up by other open source developers

**Comment by GeorgiaHCA** [comment]
Thank you for agreeing to help @MaxwellRiess !

**Comment by jhlink** [comment]
Removing the milestone 2 tag, and replacing it with the enhancement. 

Integrating gov.uk components is outside of implementing the bare minimum wireframes.
