### ISSUE TITLE
GSoC 2021: Project ideas and assessment requirements

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#88]
## :tada: **Welcome GSoC Contributors! This is The AutSPACEs platform development repository** :tada:

:dizzy: _We're excited that you're here and want to contribute._ :dizzy:

### Summary

* INCF is accepted as [Google Summer of Code](https://summerofcode.withgoogle.com/) (GSoC) organisation, & _AutSPACEs_ is listed as one of the projects ([see the proposal](https://docs.google.com/document/d/14wnNV-cIqTIF3eE9QJXtkwyW7lQomUiCLVVPFafX6Js/edit#heading=h.qdrtn5iywj8e))
* March 9 to March 28 is an exploration phase for the students who would like to work on the project.
* We urge all the candidates to work on a minimum of 2 projects simultaneously so that they are not completely relying on their selection in AutSPACEs if we end up not selecting them.
* We will not be handling communication via personal emails. All responses will be directed to this issue. You are welcome to join our Slack channel, here is a link to the [full Slack Workspace for Open Humans](https://slackin.openhumans.org). Please join **#autistica-turing** to connect with others about the project and for GSoC discussions.

### Assessing GSoC candidates

Contributing during the GSoC exploration phase is meant to assess how well the candidates’ work fit the requirement of a project.

We are seeking a GSOC mentee with web development skills to work on building the platform in Django with a researcher and an experienced developer. This is a complex project with multiple elements, and the repository still needs refining. Being able to work with this repository and deal well with complexity is key to doing well on these tasks, and will be a criteria of success. Building the platform will involve elements of UX/UI design focussing on the needs and preferences of autistic collaborators. 

We are therefore looking for the ability to **deploy an app on Heroku which works with [Open Humans](https://www.openhumans.org/)**, as well as **evidence of Django experience**, and a **demonstration of understanding of, and interest in, the features in the requirements list**.  

Other technical contributions are always welcome, but non-assessable contributions like fixing a broken link or typos will not be sufficient to build a proposal with AutSPACEs - we need to learn about your ability to work on the technical aspects as well as your collaboration skills, while offering you a welcoming environment to participate in an Open Source project.

**It should NOT be assumed that contributing to the project will automatically secure you a position as a GSoC participant.**

### Specific tasks for assessment

We will assess interested GSOC students against the following criteria:

* have read the [contribution guidelines](https://github.com/GeorgiaHCA/AutSPACEs/blob/main/contributing-guidelines.md), [Code of Conduct](https://github.com/GeorgiaHCA/AutSPACEs/blob/main/code-of-conduct.md) and our [GSoC proposal](https://docs.google.com/document/d/14wnNV-cIqTIF3eE9QJXtkwyW7lQomUiCLVVPFafX6Js/edit#heading=h.qdrtn5iywj8e)
* knows how to work on GitHub
* understands the Open Humans backend that the AutSPACEs platform interfaces with
* has experience with the Django framework
* understands the web design requirements we have described in our proposal and have the skill set to help address them

#### Step 0: Familiarise yourself with our project

Take some time to explore the repositories which are associated with AutSPACEs, and familiarise yourself with the project, and where different aspects of the project are held and discussed:
* AutSPACEs Repository: https://github.com/GeorgiaHCA/AutSPACEs
  * This repository is where the (very early) development of the platform is happening.
* Project Management Repository: https://github.com/alan-turing-institute/AutisticaCitizenScience
  * This repository gives a general overview of the project, as well as data, resources, and tasks not specifically to do with platform development. 
* Recorded talks and webinars. We recommend watching two recorded presentations about the project
  * @GeorgiaHCA and Otis' webinar with Autistia. Their presentation starts around 20 minutes into the session: https://youtu.be/QDWpykMPxQ8.
  * @KirstieJane and @GeorgiaHCA's presentation at a recent Open Humans Community Call: https://youtu.be/YeVML0j8XoE

#### Step 1: Deploy an Open Humans data upload project on Heroku

Use the guide at https://github.com/gedankenstuecke/oh_data_uploader to create an Open Humans data upload project.

As part of setting up the project, you will need to enter some information into the Open Humans website to describe your project. We have developed some recommended entries for the form to help you create the project. We have listed those under **Resources** at the end of this issue.

We will be looking for a working project which is created on Open Humans and deployed on Heroku. When it is successfully deployed you should see a page looking like this:

![image](https://user-images.githubusercontent.com/46889966/112129996-e14f0a00-8bbf-11eb-97cf-3bb2e58a335c.png)

Once you have linked the page to the project you set up on the Open Humans website, you should be able to login and go to the Project Config page:

![](https://i.imgur.com/pBLeIem.png)

Our goal with this requirement is to **check that you have the skills to follow the instructions at Open Humans to launch an example project**. Please make sure that your project is configured so that we can upload some data. If you would like to customise your deployment in other ways, we encourage you to experiment with the html / css and text to do so.

#### Step 2: show us your Django skills!

This project is quite early in its development and we are aware that you the github repositories can be a little challenging to contribute to. (We're working on it! And we're looking forward to having a GSOC student who can help us!)

In lieu of it being easy for you to contribute to _this_ project we'd like to see your skills in Django development. We'd like to see a GitHub repository and associated deployment of a Django webapp.

Our goal with this requirement is to **check that you have the Python and web development skills** to work on the platform this summer.

#### Step 3: Choose a platform feature that you could work on during GSOC

We have a list of requirements for the platform listed in this repository in the [platform-design/requirements-list.md](https://github.com/GeorgiaHCA/AutSPACEs/blob/main/platform-design/requirements-list.md)

Choose one of those requirements and write a short paragraph of **no more than 500 words** that explains how you would implement that requirement.

Our goal with this requirement is to check that you **understand the purpose of the development requirements** that we have in mind, and that you can communicate that understanding clearly.

### What can AutSPACEs offer during this period?

As an Open Source and contribution-driven project, we would like to invite interested candidates to start engaging with the project as a contributor. Please be sure that you follow our contribution guidelines and code of conduct.

* We would like to encourage interested members to work openly and collaboratively in line with the community participation guidelines
* This will allow interested members to learn about the project while helping us see their enthusiasm and willingness to work on this project
* By completing the task, they would be able to provide us examples of their technical skills through contributing to our project on GitHub
* This will also allow them to generate ideas for their proposal or consider if contributing to _AutSPACEs_ is the right fit for them 
* If they end up getting selected, they will be able to keep on working with mentorship and guidance to further enhance their work within the project
* If they don't get selected or decide to not go ahead with the proposal, their contributions will still be counted and they will be listed as one of our community members.

*For any further questions, please comment below!*

### Submitting your work

Please open a pull request to add a markdown file to the [GSoC-2021](https://github.com/GeorgiaHCA/AutSPACEs/tree/main/GSoC-2021) folder.

Name the file using your first and last names (`first-last.md`) and complete the following information inside the file.

```
# GSOC2021 Expression of Interest: [NAME] (replace with your name)

## Assessment step 1

*Add a link to your deployed heroku app here.*

## Assessment step 2

*Add a link to your Django project's GitHub repository here.*

## Assessment step 3

*Add a short paragraph explaining one of the development requirements that you'd like to work on, how you'd address the need, and why you consider it to be of interest.*
```

## Templated answers for setting up a project on Open Humans

Here you can see our suggested answers to help you create a sample project on Open Humans.

> ## Open Humans: create a project
> 
> Is this project a study or an activity?
> **Activity*
> 
> Project name: [Choose your own name]
> 
> Leader(s) or principal investigator(s): [Your name]
> 
> Organization or institution: **Alan Turing Institute**
> 
> Is this institution or organization an academic institution or non-profit organization?
> **Yes**
> 
> If your project collects data, choose "Add data" here. If you choose "Add data", you will need to provide a "Returned data description" below.
> **Add data**
> 
> If your project performs analysis on data, choose "Explore & share".
> **Explore & share**
> 
> Contact email for your project: [Your email]
> 
> URL for general information about your project:
> https://alan-turing-institute.github.io/AutisticaCitizenScience/
> 
> A short description
> **Testing application for submission to GSoC to work on the Autistica/Turing AutSPACEs project**
> 
> A long description
> "This is a test application for the Turing/Autistica citizen scieence project. Numerous studies have confirmed that autistic people experience sensory processing differences, and that this can significantly impact their lives. One aspect which is not yet fully understood is how these differences affect the ways in which autistic people navigate different environments. Using participatory methods, this project will build a citizen scientist platform which will collect rich information about people's experiences navigating the world. The data can be used to improve public and private spaces for autistic people, educate the public, and help create strategies to cope with, and remove, barriers autistic people may face."
> 
> Description of data you plan to upload to member accounts 
> **This application is a test only and will only upload test, made-up data.**
> 
> Active
> **Yes**
> 
> **Badge image**: [Choose your own image]
> 
> Are you requesting Open Humans usernames?
> **Yes**
> 
> Erasure supported
> **Yes**
> 
> Deauthorize email notifications
> **No**
> 
> Requested sources
> **None as yet**
> 
> Enrollment URL
> [yourprojecturl]
> 
> Information URL
> https://github.com/GeorgiaHCA/AutSPACEs
> 
> Terms of Use URL
> https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/project-management/ethics-applications/stage-1-co-design-phase/A8_DataManagement.pdf
> 
> Redirect URL
> [yourprojecturl/complete]
> 
> Webhook secret
> **leave blank for now**
> 
> Deauthorization Webhook URL
> https://www.turing.ac.uk/research/research-projects/citizen-science-platform-autistica

**Comment by anoura12** [comment]
Hi!
Since this issue is a WIP, should we go ahead and familiarize ourselves with the repositories to start with?

**Comment by GeorgiaHCA** [comment]
Hiya, thanks for your comment and welcome @anoura12 ! Yes, please do take a look through the repositories until the issue above is no longer a work in progress. I'm still getting feedback and wouldn't want you to lose any time on something which might change.
Should be open soon and I'll keep everyone posted on the #autistica-turing slack channel as well. You are welcome to join our Slack channel, here is a link to the full [Slack Workspace for Open Humans](https://slackin.openhumans.org). Please join #autistica-turing to connect with others about the project and for GSoC discussions.

**Comment by anoura12** [comment]
Hi, is this issue complete or still a WIP? I was just wondering since the feedback date is on the 25th.

**Comment by GeorgiaHCA** [comment]
This issue is now OPEN for GSoC students to work on! 🎉

**Comment by anoura12** [comment]
This is with regard to uploading data to your project in Step 1 of the issue.

By @KirstieJane - We'll test by uploading, but we'll be looking to see your instructions etc so it makes sense for you to have a think about what data you're expecting us to upload. Which means I'd expect for you to have uploaded some as an example.

**Comment by GeorgiaHCA** [comment]
Closing this now - fabulous work @anoura12 ! ❤️
