### ISSUE TITLE
Integrate moderation into platform 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#97]
### Summary

We will need to build the moderation process into the platform once the MVP has been created and the moderation process has been defined.  This requires the moderation created and the MVP built.

**Comment by GeorgiaHCA** [comment]
Does this issue look good to you @JamesSCTJ?

**Comment by JamesSCTJ** [comment]
Yes it does @GeorgiaHCA !

**Comment by GeorgiaHCA** [comment]
I see - I think that would depend a lot on the degree of separation/integration we would want and how feasible the different options are. I think probably the easiest way would be to have a "safe site" option which would fiilter things out rather than building a whole new platform? I'm wary of stalling on the MVP build while we decide on this, and think it could probably best be implemented afterwards.

**Comment by GeorgiaHCA** [comment]
Would you be able to create a separate issue for this @JamesSCTJ? It would be amazing if it could 
1) link to the discussion on moderation in the other repo
2) be labelled with 'roadmap'
3) tagging in the dev team and Lotty to see what they think it should be labelled as/where it should sit in the roadmap/which milestone it should go under. 
Probs also best to get Kirstie's view! 

Thank you so much for bringing this up @JamesSCTJ! I think i's a great idea and one that could really make the platform useable for a diverse range of people while aso mitigating a range of the risks you identified in your moderation strategy doc.

**Comment by sowmya9507** [comment]
@GeorgiaHCA the option of implementing a safe site is really a great idea. I was wondering what all should be included while implementing this option. Can we also create a list for this?

**Comment by GeorgiaHCA** [comment]
Hi @sowmya9507 - so my feeling on this is that we should focus on the MVP for now because the safe site would take a whole lot of extra thinking and planning and it needs to be decided whether we want to do it in that way, whereas the MVP is good place to start so we know we have the main features built. But I also think it's a great idea! Just maybe one to focus on as a less immediate priority for the development. What do you think @lottycoupat ? @KirstieJane?

**Comment by gedankenstuecke** [comment]
These things are now all implemented 🙂
