### ISSUE TITLE
Document Open Humans Link

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#98]
### Summary

Document how Open Humans and the platform interface will operate together, including the file management flow and security and database management.

**Comment by GeorgiaHCA** [comment]
![image](https://user-images.githubusercontent.com/46889966/119486575-4eae2100-bd50-11eb-830c-830a2f29a039.png)

**Comment by GeorgiaHCA** [comment]
![image](https://user-images.githubusercontent.com/46889966/119486876-a2206f00-bd50-11eb-99ce-472ac556bfd3.png)

**Comment by jhlink** [comment]
This should be a PR, not an issue ticket as all information seems to have been already completed. 
Closing.
