### ISSUE TITLE
 Store text input in Open Humans back end with appropriate tags

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutSPACEs#99]
### What needs to be done?

- [ ] Text inputted into the share experience component of the "share experiences page" gets stored securely and in the Open Humans backend database with a user ID
- [ ] The experience is tagged with the user's privacy choices and autism status such that the dataset can be automatically filtered on that basis
- [ ] experiences must be matched with the user so that they will be able to see their own experience
- [ ] experiences with permission to be used publicly must go to a moderation process.

**Comment by GeorgiaHCA** [comment]
This links to #16

**Comment by GeorgiaHCA** [comment]
are you working on this issue @sowmya9507 ?

**Comment by jhlink** [comment]
Tasks described here are captured in #156 . Closing.
